../src/alu.sv
../src/bu.sv
../src/cu.sv
../src/dec.sv
../src/exe.sv
../src/fet.sv
../src/fetcher.sv
../src/fu.sv
../src/hu.sv
../src/imm_gen.sv
../src/lsu.sv
../src/obi_intf.sv
../src/reg_file.sv
../src/riscv_core.sv
../src/riscv_pkg.sv
../src/ssram_wrap.sv
../src/wb.sv
../tb/tb.sv
