[rules]
blocking_assignment_in_always_ff = true
case_default = false
operator_case_equality = true
default_nettype_none = false
enum_with_type = true
for_with_begin = true
function_same_as_system_function = false
function_with_automatic = false
generate_for_with_label = true
generate_if_with_label = true
generate_keyword_forbidden = true
generate_keyword_required = true
genvar_declaration_in_loop = true
genvar_declaration_out_loop = true
if_with_begin = false
inout_with_tri = false
input_with_var = false
interface_port_with_modport = true
legacy_always = true
level_sensitive_always = true
loop_variable_declaration = true
non_ansi_module = true
non_blocking_assignment_in_always_comb = true
output_with_var = false
parameter_in_package = true
priority_keyword = true
tab_character = false
unique0_keyword = true
unique_keyword = true
wire_reg = true
