/*
###############################################################
#  Generated by:      Cadence Innovus 20.11-s130_1
#  OS:                Linux x86_64(Host ID isaserver)
#  Generated on:      Sun Nov  5 18:47:27 2023
#  Design:            IIR
#  Command:           saveNetlist IIR.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : S-2021.06-SP4
// Date      : Sun Nov  5 16:29:08 2023
/////////////////////////////////////////////////////////////
module IIR_DW01_add_1 (
	A, 
	B, 
	CI, 
	SUM, 
	CO);
   input [10:0] A;
   input [10:0] B;
   input CI;
   output [10:0] SUM;
   output CO;

   // Internal wires
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire [10:6] carry;

   assign SUM[3] = A[3] ;
   assign SUM[2] = A[2] ;
   assign SUM[1] = A[1] ;
   assign SUM[0] = A[0] ;

   FA_X1 U1_10 (.A(A[10]),
	.B(carry[10]),
	.CI(B[10]),
	.S(SUM[10]));
   FA_X1 U1_9 (.A(A[9]),
	.B(B[9]),
	.CI(carry[9]),
	.CO(carry[10]),
	.S(SUM[9]));
   FA_X1 U1_7 (.A(B[7]),
	.B(A[7]),
	.CI(carry[7]),
	.CO(carry[8]),
	.S(SUM[7]));
   XNOR2_X1 U1 (.A(n12),
	.B(B[6]),
	.ZN(SUM[6]));
   XNOR2_X1 U3 (.A(n8),
	.B(carry[8]),
	.ZN(SUM[8]));
   AND2_X1 U5 (.A1(B[4]),
	.A2(A[4]),
	.ZN(n16));
   XNOR2_X1 U6 (.A(B[5]),
	.B(n4),
	.ZN(SUM[5]));
   NAND3_X1 U7 (.A1(n5),
	.A2(n6),
	.A3(n7),
	.ZN(n3));
   XNOR2_X1 U8 (.A(n16),
	.B(A[5]),
	.ZN(n4));
   NAND2_X1 U9 (.A1(n16),
	.A2(B[5]),
	.ZN(n5));
   NAND2_X1 U10 (.A1(B[5]),
	.A2(A[5]),
	.ZN(n6));
   NAND2_X1 U11 (.A1(n16),
	.A2(A[5]),
	.ZN(n7));
   NAND3_X1 U12 (.A1(n5),
	.A2(n7),
	.A3(n6),
	.ZN(carry[6]));
   XOR2_X1 U13 (.A(B[4]),
	.B(A[4]),
	.Z(SUM[4]));
   XNOR2_X1 U14 (.A(B[8]),
	.B(A[8]),
	.ZN(n8));
   NAND2_X1 U15 (.A1(B[8]),
	.A2(carry[8]),
	.ZN(n9));
   NAND2_X1 U16 (.A1(carry[8]),
	.A2(A[8]),
	.ZN(n10));
   NAND2_X1 U17 (.A1(B[8]),
	.A2(A[8]),
	.ZN(n11));
   NAND3_X1 U18 (.A1(n9),
	.A2(n10),
	.A3(n11),
	.ZN(carry[9]));
   XNOR2_X1 U19 (.A(n3),
	.B(A[6]),
	.ZN(n12));
   NAND2_X1 U20 (.A1(B[6]),
	.A2(carry[6]),
	.ZN(n13));
   NAND2_X1 U21 (.A1(B[6]),
	.A2(A[6]),
	.ZN(n14));
   NAND2_X1 U22 (.A1(carry[6]),
	.A2(A[6]),
	.ZN(n15));
   NAND3_X1 U23 (.A1(n13),
	.A2(n15),
	.A3(n14),
	.ZN(carry[7]));
endmodule

module IIR_DW_mult_tc_2 (
	a, 
	b, 
	product);
   input [9:0] a;
   input [10:0] b;
   output [20:0] product;

   // Internal wires
   wire FE_OFN1_n504;
   wire n5;
   wire n6;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n49;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n60;
   wire n61;
   wire n63;
   wire n64;
   wire n65;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n112;
   wire n113;
   wire n114;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n162;
   wire n163;
   wire n164;
   wire n165;
   wire n166;
   wire n167;
   wire n168;
   wire n169;
   wire n324;
   wire n325;
   wire n330;
   wire n335;
   wire n336;
   wire n337;
   wire n341;
   wire n342;
   wire n343;
   wire n344;
   wire n346;
   wire n347;
   wire n348;
   wire n349;
   wire n350;
   wire n352;
   wire n353;
   wire n354;
   wire n355;
   wire n356;
   wire n357;
   wire n358;
   wire n359;
   wire n360;
   wire n361;
   wire n362;
   wire n364;
   wire n365;
   wire n367;
   wire n368;
   wire n369;
   wire n370;
   wire n371;
   wire n372;
   wire n373;
   wire n374;
   wire n376;
   wire n377;
   wire n378;
   wire n379;
   wire n380;
   wire n381;
   wire n383;
   wire n384;
   wire n385;
   wire n386;
   wire n387;
   wire n388;
   wire n389;
   wire n390;
   wire n392;
   wire n393;
   wire n395;
   wire n399;
   wire n400;
   wire n401;
   wire n402;
   wire n403;
   wire n404;
   wire n405;
   wire n406;
   wire n407;
   wire n408;
   wire n409;
   wire n410;
   wire n411;
   wire n412;
   wire n413;
   wire n414;
   wire n415;
   wire n416;
   wire n417;
   wire n420;
   wire n421;
   wire n422;
   wire n423;
   wire n424;
   wire n425;
   wire n426;
   wire n427;
   wire n428;
   wire n429;
   wire n430;
   wire n431;
   wire n432;
   wire n433;
   wire n434;
   wire n435;
   wire n436;
   wire n437;
   wire n438;
   wire n439;
   wire n440;
   wire n441;
   wire n442;
   wire n443;
   wire n444;
   wire n445;
   wire n446;
   wire n447;
   wire n448;
   wire n449;
   wire n451;
   wire n452;
   wire n453;
   wire n454;
   wire n455;
   wire n456;
   wire n458;
   wire n459;
   wire n460;
   wire n461;
   wire n462;
   wire n463;
   wire n464;
   wire n465;
   wire n466;
   wire n467;
   wire n468;
   wire n469;
   wire n470;
   wire n471;
   wire n472;
   wire n473;
   wire n474;
   wire n475;
   wire n476;
   wire n477;
   wire n478;
   wire n479;
   wire n480;
   wire n481;
   wire n482;
   wire n483;
   wire n484;
   wire n485;
   wire n486;
   wire n487;
   wire n488;
   wire n489;
   wire n490;
   wire n491;
   wire n492;
   wire n493;
   wire n494;
   wire n495;
   wire n496;
   wire n497;
   wire n499;
   wire n500;
   wire n501;
   wire n502;
   wire n503;
   wire n504;
   wire n505;
   wire n506;
   wire n507;
   wire n508;
   wire n509;
   wire n510;
   wire n511;
   wire n512;
   wire n513;
   wire n514;
   wire n515;
   wire n516;
   wire n517;
   wire n518;
   wire n519;
   wire n520;
   wire n521;
   wire n522;
   wire n523;
   wire n524;
   wire n525;
   wire n526;
   wire n527;
   wire n528;
   wire n529;
   wire n530;
   wire n531;
   wire n532;
   wire n533;
   wire n534;
   wire n535;
   wire n536;
   wire n537;
   wire n538;
   wire n539;
   wire n540;
   wire n541;
   wire n542;
   wire n543;
   wire n544;
   wire n545;
   wire n546;
   wire n547;
   wire n548;
   wire n549;
   wire n550;
   wire n551;
   wire n552;
   wire n553;
   wire n554;
   wire n555;
   wire n556;
   wire n557;
   wire n558;
   wire n559;
   wire n560;
   wire n561;
   wire n562;
   wire n563;
   wire n564;
   wire n565;
   wire n566;
   wire n567;
   wire n568;
   wire n569;
   wire n570;
   wire n571;
   wire n572;
   wire n573;
   wire n574;
   wire n575;
   wire n576;

   AOI21_X1 FE_RC_11_0 (.A(n525),
	.B1(n517),
	.B2(n516),
	.ZN(n561));
   AOI21_X1 FE_RC_10_0 (.A(n523),
	.B1(n522),
	.B2(n521),
	.ZN(n553));
   OAI21_X1 FE_RC_9_0 (.A(n519),
	.B1(n480),
	.B2(n481),
	.ZN(n150));
   AOI21_X1 FE_RC_8_0 (.A(n392),
	.B1(n479),
	.B2(n509),
	.ZN(n533));
   CLKBUF_X1 FE_OFC1_n504 (.A(n504),
	.Z(FE_OFN1_n504));
   FA_X1 U21 (.A(n118),
	.B(n24),
	.CI(n475),
	.CO(n20),
	.S(n21));
   FA_X1 U22 (.A(n476),
	.B(n119),
	.CI(n28),
	.CO(n22),
	.S(n23));
   FA_X1 U24 (.A(n32),
	.B(n120),
	.CI(n29),
	.CO(n26),
	.S(n27));
   FA_X1 U25 (.A(n129),
	.B(n34),
	.CI(n473),
	.CO(n28),
	.S(n29));
   FA_X1 U26 (.A(n33),
	.B(n40),
	.CI(n38),
	.CO(n30),
	.S(n31));
   FA_X1 U27 (.A(n121),
	.B(n130),
	.CI(n474),
	.CO(n32),
	.S(n33));
   FA_X1 U29 (.A(n44),
	.B(n41),
	.CI(n39),
	.CO(n36),
	.S(n37));
   FA_X1 U30 (.A(n472),
	.B(n140),
	.CI(n46),
	.CO(n38),
	.S(n39));
   FA_X1 U31 (.A(n131),
	.B(n122),
	.CI(n150),
	.CO(n40),
	.S(n41));
   FA_X1 U33 (.A(n56),
	.B(n49),
	.CI(n54),
	.CO(n44),
	.S(n45));
   FA_X1 U34 (.A(n132),
	.B(n123),
	.CI(n141),
	.CO(n46),
	.S(n47));
   FA_X1 U42 (.A(n65),
	.B(n72),
	.CI(n70),
	.CO(n60),
	.S(n61));
   HA_X1 U44 (.A(n125),
	.B(n134),
	.CO(n64),
	.S(n65));
   FA_X1 U46 (.A(n73),
	.B(n78),
	.CI(n163),
	.CO(n68),
	.S(n69));
   FA_X1 U47 (.A(n135),
	.B(n144),
	.CI(n153),
	.CO(n70),
	.S(n71));
   HA_X1 U48 (.A(n112),
	.B(n126),
	.CO(n72),
	.S(n73));
   FA_X1 U50 (.A(n136),
	.B(n154),
	.CI(n84),
	.CO(n76),
	.S(n77));
   HA_X1 U54 (.A(n113),
	.B(n137),
	.CO(n84),
	.S(n85));
   FA_X1 U57 (.A(n157),
	.B(n93),
	.CI(n167),
	.CO(n90),
	.S(n91));
   HA_X1 U58 (.A(n114),
	.B(n148),
	.CO(n92),
	.S(n93));
   FA_X1 U59 (.A(n168),
	.B(n149),
	.CI(n158),
	.CO(n94),
	.S(n95));
   HA_X1 U60 (.A(n159),
	.B(n169),
	.CO(n96),
	.S(n97));
   INV_X1 U247 (.A(n20),
	.ZN(n353));
   OAI22_X1 U248 (.A1(n546),
	.A2(n521),
	.B1(n522),
	.B2(n547),
	.ZN(n146));
   INV_X1 U249 (.A(a[0]),
	.ZN(n479));
   OAI22_X1 U250 (.A1(n550),
	.A2(n521),
	.B1(n522),
	.B2(n551),
	.ZN(n142));
   OAI22_X1 U251 (.A1(n564),
	.A2(n492),
	.B1(n491),
	.B2(n565),
	.ZN(n124));
   AND3_X1 U252 (.A1(n454),
	.A2(n455),
	.A3(n456),
	.ZN(n494));
   AND3_X1 U253 (.A1(n420),
	.A2(n421),
	.A3(n422),
	.ZN(n324));
   AND3_X1 U254 (.A1(n404),
	.A2(n405),
	.A3(n406),
	.ZN(n325));
   XNOR2_X1 U256 (.A(b[10]),
	.B(n483),
	.ZN(n519));
   INV_X1 U257 (.A(n85),
	.ZN(n343));
   AND3_X1 U258 (.A1(n409),
	.A2(n408),
	.A3(n407),
	.ZN(n458));
   NAND3_X1 U259 (.A1(n434),
	.A2(n433),
	.A3(n432),
	.ZN(n336));
   XNOR2_X1 U260 (.A(n478),
	.B(n512),
	.ZN(n57));
   OAI222_X1 U265 (.A1(n499),
	.A2(n469),
	.B1(n499),
	.B2(n467),
	.C1(n467),
	.C2(n469),
	.ZN(n330));
   OAI22_X1 U270 (.A1(n529),
	.A2(n509),
	.B1(n530),
	.B2(n479),
	.ZN(n165));
   XNOR2_X1 U272 (.A(b[4]),
	.B(a[1]),
	.ZN(n527));
   XNOR2_X1 U273 (.A(n471),
	.B(n335),
	.ZN(n55));
   XNOR2_X1 U274 (.A(n142),
	.B(n124),
	.ZN(n335));
   NAND3_X1 U276 (.A1(n433),
	.A2(n432),
	.A3(n434),
	.ZN(n337));
   XNOR2_X1 U279 (.A(n337),
	.B(n341),
	.ZN(n53));
   XNOR2_X1 U280 (.A(n57),
	.B(n64),
	.ZN(n341));
   AND3_X1 U282 (.A1(n388),
	.A2(n390),
	.A3(n389),
	.ZN(n342));
   XNOR2_X1 U283 (.A(n88),
	.B(n343),
	.ZN(n410));
   XNOR2_X1 U284 (.A(n83),
	.B(n410),
	.ZN(n344));
   OAI222_X1 U286 (.A1(n352),
	.A2(n393),
	.B1(n494),
	.B2(n458),
	.C1(n352),
	.C2(n458),
	.ZN(n346));
   XNOR2_X1 U287 (.A(n377),
	.B(n45),
	.ZN(n352));
   OR2_X1 U288 (.A1(n495),
	.A2(n324),
	.ZN(n448));
   XNOR2_X1 U289 (.A(n347),
	.B(n89),
	.ZN(n87));
   XNOR2_X1 U290 (.A(n92),
	.B(n147),
	.ZN(n347));
   NAND2_X1 U291 (.A1(n471),
	.A2(n142),
	.ZN(n348));
   NAND2_X1 U292 (.A1(n471),
	.A2(n124),
	.ZN(n349));
   NAND2_X1 U293 (.A1(n142),
	.A2(n124),
	.ZN(n350));
   NAND3_X1 U294 (.A1(n348),
	.A2(n349),
	.A3(n350),
	.ZN(n54));
   XNOR2_X1 U296 (.A(n354),
	.B(n353),
	.ZN(n489));
   NAND3_X1 U297 (.A1(n427),
	.A2(n426),
	.A3(n428),
	.ZN(n354));
   NAND3_X1 U298 (.A1(n442),
	.A2(n441),
	.A3(n443),
	.ZN(n355));
   AND2_X1 U299 (.A1(n330),
	.A2(n87),
	.ZN(n356));
   AND2_X1 U300 (.A1(n330),
	.A2(n90),
	.ZN(n357));
   AND2_X1 U301 (.A1(n90),
	.A2(n87),
	.ZN(n358));
   NOR3_X1 U302 (.A1(n356),
	.A2(n357),
	.A3(n358),
	.ZN(n459));
   XOR2_X1 U303 (.A(n145),
	.B(n127),
	.Z(n359));
   XOR2_X1 U304 (.A(n164),
	.B(n359),
	.Z(n79));
   NAND2_X1 U305 (.A1(n164),
	.A2(n145),
	.ZN(n360));
   NAND2_X1 U306 (.A1(n164),
	.A2(n127),
	.ZN(n361));
   NAND2_X1 U307 (.A1(n145),
	.A2(n127),
	.ZN(n362));
   NAND3_X1 U308 (.A1(n360),
	.A2(n361),
	.A3(n362),
	.ZN(n78));
   NAND3_X1 U310 (.A1(n439),
	.A2(n438),
	.A3(n440),
	.ZN(n364));
   NAND3_X1 U311 (.A1(n438),
	.A2(n439),
	.A3(n440),
	.ZN(n365));
   XNOR2_X1 U312 (.A(n431),
	.B(n63),
	.ZN(n367));
   XNOR2_X1 U313 (.A(n346),
	.B(n368),
	.ZN(product[13]));
   XNOR2_X1 U314 (.A(n37),
	.B(n42),
	.ZN(n368));
   XNOR2_X1 U315 (.A(n429),
	.B(n369),
	.ZN(product[16]));
   XNOR2_X1 U316 (.A(n23),
	.B(n26),
	.ZN(n369));
   XNOR2_X1 U317 (.A(n365),
	.B(n370),
	.ZN(product[17]));
   XNOR2_X1 U318 (.A(n22),
	.B(n21),
	.ZN(n370));
   NAND3_X1 U320 (.A1(n460),
	.A2(n461),
	.A3(n462),
	.ZN(n371));
   NAND2_X1 U321 (.A1(n336),
	.A2(n57),
	.ZN(n372));
   NAND2_X1 U322 (.A1(n336),
	.A2(n64),
	.ZN(n373));
   NAND2_X1 U323 (.A1(n57),
	.A2(n64),
	.ZN(n374));
   NAND3_X1 U324 (.A1(n372),
	.A2(n373),
	.A3(n374),
	.ZN(n52));
   XNOR2_X1 U325 (.A(n376),
	.B(n166),
	.ZN(n89));
   XNOR2_X1 U326 (.A(n156),
	.B(n138),
	.ZN(n376));
   XOR2_X1 U327 (.A(n52),
	.B(n47),
	.Z(n377));
   NAND2_X1 U328 (.A1(n45),
	.A2(n52),
	.ZN(n378));
   NAND2_X1 U329 (.A1(n45),
	.A2(n47),
	.ZN(n379));
   NAND2_X1 U330 (.A1(n52),
	.A2(n47),
	.ZN(n380));
   NAND3_X1 U331 (.A1(n378),
	.A2(n379),
	.A3(n380),
	.ZN(n42));
   XNOR2_X1 U332 (.A(n162),
	.B(n381),
	.ZN(n63));
   XNOR2_X1 U333 (.A(n152),
	.B(n143),
	.ZN(n381));
   NAND3_X1 U334 (.A1(n451),
	.A2(n452),
	.A3(n453),
	.ZN(n383));
   NAND2_X1 U335 (.A1(n330),
	.A2(n87),
	.ZN(n384));
   NAND2_X1 U336 (.A1(n330),
	.A2(n90),
	.ZN(n385));
   NAND2_X1 U337 (.A1(n90),
	.A2(n87),
	.ZN(n386));
   AND3_X1 U338 (.A1(n384),
	.A2(n385),
	.A3(n386),
	.ZN(n497));
   NAND3_X1 U339 (.A1(n447),
	.A2(n448),
	.A3(n449),
	.ZN(n387));
   NAND2_X1 U340 (.A1(n67),
	.A2(n383),
	.ZN(n388));
   NAND2_X1 U341 (.A1(n383),
	.A2(n74),
	.ZN(n389));
   NAND2_X1 U342 (.A1(n67),
	.A2(n74),
	.ZN(n390));
   AND3_X1 U343 (.A1(n390),
	.A2(n388),
	.A3(n389),
	.ZN(n495));
   XNOR2_X1 U345 (.A(b[10]),
	.B(a[1]),
	.ZN(n392));
   AND3_X1 U346 (.A1(n455),
	.A2(n454),
	.A3(n456),
	.ZN(n393));
   NAND3_X1 U348 (.A1(n445),
	.A2(n444),
	.A3(n446),
	.ZN(n395));
   AOI222_X1 U352 (.A1(n500),
	.A2(n95),
	.B1(n500),
	.B2(n96),
	.C1(n96),
	.C2(n95),
	.ZN(n499));
   XNOR2_X1 U353 (.A(n399),
	.B(n53),
	.ZN(n51));
   XNOR2_X1 U354 (.A(n55),
	.B(n60),
	.ZN(n399));
   XNOR2_X1 U355 (.A(b[9]),
	.B(a[1]),
	.ZN(n532));
   XNOR2_X1 U356 (.A(n69),
	.B(n400),
	.ZN(n67));
   XNOR2_X1 U357 (.A(n71),
	.B(n76),
	.ZN(n400));
   NAND2_X1 U358 (.A1(n156),
	.A2(n138),
	.ZN(n401));
   NAND2_X1 U359 (.A1(n156),
	.A2(n166),
	.ZN(n402));
   NAND2_X1 U360 (.A1(n138),
	.A2(n166),
	.ZN(n403));
   NAND3_X1 U361 (.A1(n401),
	.A2(n402),
	.A3(n403),
	.ZN(n88));
   NAND2_X1 U362 (.A1(n92),
	.A2(n147),
	.ZN(n404));
   NAND2_X1 U363 (.A1(n92),
	.A2(n89),
	.ZN(n405));
   NAND2_X1 U364 (.A1(n147),
	.A2(n89),
	.ZN(n406));
   NAND2_X1 U365 (.A1(n53),
	.A2(n55),
	.ZN(n407));
   NAND2_X1 U366 (.A1(n53),
	.A2(n60),
	.ZN(n408));
   NAND2_X1 U367 (.A1(n55),
	.A2(n60),
	.ZN(n409));
   NAND2_X1 U368 (.A1(n83),
	.A2(n88),
	.ZN(n411));
   NAND2_X1 U369 (.A1(n83),
	.A2(n85),
	.ZN(n412));
   NAND2_X1 U370 (.A1(n88),
	.A2(n85),
	.ZN(n413));
   NAND3_X1 U371 (.A1(n411),
	.A2(n412),
	.A3(n413),
	.ZN(n80));
   XOR2_X1 U372 (.A(n155),
	.B(n146),
	.Z(n414));
   XOR2_X1 U373 (.A(n165),
	.B(n414),
	.Z(n83));
   NAND2_X1 U374 (.A1(n165),
	.A2(n155),
	.ZN(n415));
   NAND2_X1 U375 (.A1(n165),
	.A2(n146),
	.ZN(n416));
   NAND2_X1 U376 (.A1(n155),
	.A2(n146),
	.ZN(n417));
   NAND3_X1 U377 (.A1(n415),
	.A2(n416),
	.A3(n417),
	.ZN(n82));
   XNOR2_X1 U379 (.A(b[6]),
	.B(a[1]),
	.ZN(n529));
   NAND2_X1 U380 (.A1(n69),
	.A2(n71),
	.ZN(n420));
   NAND2_X1 U381 (.A1(n69),
	.A2(n76),
	.ZN(n421));
   NAND2_X1 U382 (.A1(n71),
	.A2(n76),
	.ZN(n422));
   OR2_X1 U383 (.A1(n531),
	.A2(n509),
	.ZN(n423));
   OR2_X1 U384 (.A1(n532),
	.A2(n479),
	.ZN(n424));
   NAND2_X1 U385 (.A1(n424),
	.A2(n423),
	.ZN(n163));
   XNOR2_X1 U386 (.A(b[8]),
	.B(a[1]),
	.ZN(n531));
   XNOR2_X1 U387 (.A(n371),
	.B(n425),
	.ZN(product[15]));
   XNOR2_X1 U388 (.A(n27),
	.B(n30),
	.ZN(n425));
   NAND2_X1 U389 (.A1(n364),
	.A2(n22),
	.ZN(n426));
   NAND2_X1 U390 (.A1(n364),
	.A2(n21),
	.ZN(n427));
   NAND2_X1 U391 (.A1(n22),
	.A2(n21),
	.ZN(n428));
   XNOR2_X1 U392 (.A(b[7]),
	.B(a[1]),
	.ZN(n530));
   NAND3_X1 U393 (.A1(n441),
	.A2(n442),
	.A3(n443),
	.ZN(n429));
   XNOR2_X1 U394 (.A(n6),
	.B(n430),
	.ZN(product[14]));
   XNOR2_X1 U395 (.A(n36),
	.B(n31),
	.ZN(n430));
   XOR2_X1 U396 (.A(n68),
	.B(n61),
	.Z(n431));
   NAND2_X1 U397 (.A1(n152),
	.A2(n143),
	.ZN(n432));
   NAND2_X1 U398 (.A1(n152),
	.A2(n162),
	.ZN(n433));
   NAND2_X1 U399 (.A1(n143),
	.A2(n162),
	.ZN(n434));
   NAND2_X1 U400 (.A1(n68),
	.A2(n61),
	.ZN(n435));
   NAND2_X1 U401 (.A1(n68),
	.A2(n63),
	.ZN(n436));
   NAND2_X1 U402 (.A1(n61),
	.A2(n63),
	.ZN(n437));
   NAND3_X1 U403 (.A1(n435),
	.A2(n436),
	.A3(n437),
	.ZN(n58));
   NAND2_X1 U404 (.A1(n355),
	.A2(n23),
	.ZN(n438));
   NAND2_X1 U405 (.A1(n355),
	.A2(n26),
	.ZN(n439));
   NAND2_X1 U406 (.A1(n23),
	.A2(n26),
	.ZN(n440));
   NAND2_X1 U407 (.A1(n5),
	.A2(n27),
	.ZN(n441));
   NAND2_X1 U408 (.A1(n371),
	.A2(n30),
	.ZN(n442));
   NAND2_X1 U409 (.A1(n27),
	.A2(n30),
	.ZN(n443));
   NAND2_X1 U410 (.A1(n346),
	.A2(n37),
	.ZN(n444));
   NAND2_X1 U411 (.A1(n346),
	.A2(n42),
	.ZN(n445));
   NAND2_X1 U412 (.A1(n37),
	.A2(n42),
	.ZN(n446));
   NAND3_X1 U413 (.A1(n444),
	.A2(n445),
	.A3(n446),
	.ZN(n6));
   OR2_X1 U414 (.A1(n342),
	.A2(n367),
	.ZN(n447));
   OR2_X1 U415 (.A1(n367),
	.A2(n324),
	.ZN(n449));
   NAND2_X1 U417 (.A1(n496),
	.A2(n75),
	.ZN(n451));
   NAND2_X1 U418 (.A1(n496),
	.A2(n80),
	.ZN(n452));
   NAND2_X1 U419 (.A1(n80),
	.A2(n75),
	.ZN(n453));
   NAND2_X1 U420 (.A1(n387),
	.A2(n51),
	.ZN(n454));
   NAND2_X1 U421 (.A1(n387),
	.A2(n58),
	.ZN(n455));
   NAND2_X1 U422 (.A1(n51),
	.A2(n58),
	.ZN(n456));
   INV_X1 U424 (.A(n511),
	.ZN(n478));
   INV_X1 U425 (.A(n533),
	.ZN(n471));
   INV_X1 U426 (.A(n94),
	.ZN(n467));
   INV_X1 U427 (.A(n91),
	.ZN(n469));
   INV_X1 U428 (.A(n514),
	.ZN(n477));
   INV_X1 U429 (.A(n49),
	.ZN(n472));
   INV_X1 U430 (.A(n34),
	.ZN(n474));
   INV_X1 U431 (.A(n553),
	.ZN(n473));
   INV_X1 U432 (.A(n24),
	.ZN(n476));
   INV_X1 U433 (.A(n561),
	.ZN(n475));
   INV_X1 U434 (.A(n535),
	.ZN(n481));
   INV_X1 U435 (.A(FE_OFN1_n504),
	.ZN(n480));
   INV_X1 U436 (.A(n508),
	.ZN(n470));
   XOR2_X1 U437 (.A(a[2]),
	.B(n482),
	.Z(n504));
   INV_X1 U438 (.A(a[1]),
	.ZN(n482));
   INV_X1 U439 (.A(n97),
	.ZN(n468));
   INV_X1 U440 (.A(a[3]),
	.ZN(n483));
   INV_X1 U441 (.A(a[5]),
	.ZN(n484));
   INV_X1 U442 (.A(b[0]),
	.ZN(n487));
   NAND2_X1 U443 (.A1(a[1]),
	.A2(n479),
	.ZN(n509));
   INV_X1 U444 (.A(a[7]),
	.ZN(n485));
   INV_X1 U445 (.A(a[9]),
	.ZN(n486));
   NAND2_X1 U446 (.A1(n395),
	.A2(n36),
	.ZN(n460));
   NAND2_X1 U447 (.A1(n395),
	.A2(n31),
	.ZN(n461));
   NAND2_X1 U448 (.A1(n36),
	.A2(n31),
	.ZN(n462));
   NAND3_X1 U449 (.A1(n461),
	.A2(n462),
	.A3(n460),
	.ZN(n5));
   XOR2_X1 U450 (.A(n82),
	.B(n77),
	.Z(n463));
   XOR2_X1 U451 (.A(n79),
	.B(n463),
	.Z(n75));
   NAND2_X1 U452 (.A1(n79),
	.A2(n82),
	.ZN(n464));
   NAND2_X1 U453 (.A1(n79),
	.A2(n77),
	.ZN(n465));
   NAND2_X1 U454 (.A1(n82),
	.A2(n77),
	.ZN(n466));
   NAND3_X1 U455 (.A1(n464),
	.A2(n465),
	.A3(n466),
	.ZN(n74));
   XNOR2_X2 U456 (.A(a[4]),
	.B(a[3]),
	.ZN(n522));
   XNOR2_X2 U457 (.A(a[6]),
	.B(a[5]),
	.ZN(n517));
   XNOR2_X2 U458 (.A(a[8]),
	.B(a[7]),
	.ZN(n491));
   XNOR2_X1 U459 (.A(n489),
	.B(n488),
	.ZN(product[18]));
   OAI22_X1 U460 (.A1(n490),
	.A2(n491),
	.B1(n492),
	.B2(n493),
	.ZN(n488));
   XOR2_X1 U461 (.A(b[10]),
	.B(n486),
	.Z(n490));
   OAI222_X1 U462 (.A1(n459),
	.A2(n344),
	.B1(n497),
	.B2(n325),
	.C1(n344),
	.C2(n325),
	.ZN(n496));
   OAI222_X1 U464 (.A1(n501),
	.A2(n468),
	.B1(n502),
	.B2(n501),
	.C1(n502),
	.C2(n468),
	.ZN(n500));
   AOI21_X1 U465 (.A(n503),
	.B1(a[3]),
	.B2(n481),
	.ZN(n502));
   NOR3_X1 U466 (.A1(FE_OFN1_n504),
	.A2(b[0]),
	.A3(n483),
	.ZN(n503));
   MUX2_X1 U467 (.A(n505),
	.B(n506),
	.S(b[0]),
	.Z(n501));
   NAND2_X1 U468 (.A1(n480),
	.A2(n507),
	.ZN(n506));
   NAND2_X1 U469 (.A1(n508),
	.A2(n507),
	.ZN(n505));
   OAI22_X1 U470 (.A1(n470),
	.A2(n509),
	.B1(n510),
	.B2(n479),
	.ZN(n507));
   NOR2_X1 U471 (.A1(n482),
	.A2(b[1]),
	.ZN(n508));
   NAND2_X1 U472 (.A1(n478),
	.A2(n512),
	.ZN(n56));
   AOI22_X1 U473 (.A1(n477),
	.A2(n481),
	.B1(n480),
	.B2(n513),
	.ZN(n512));
   OAI22_X1 U474 (.A1(n515),
	.A2(n516),
	.B1(n517),
	.B2(n518),
	.ZN(n511));
   AOI22_X1 U475 (.A1(n513),
	.A2(n481),
	.B1(n480),
	.B2(n519),
	.ZN(n49));
   XOR2_X1 U476 (.A(b[9]),
	.B(a[3]),
	.Z(n513));
   OAI22_X1 U477 (.A1(n520),
	.A2(n521),
	.B1(n522),
	.B2(n523),
	.ZN(n34));
   OAI22_X1 U478 (.A1(n524),
	.A2(n516),
	.B1(n517),
	.B2(n525),
	.ZN(n24));
   OAI22_X1 U479 (.A1(n510),
	.A2(n509),
	.B1(n526),
	.B2(n479),
	.ZN(n169));
   XOR2_X1 U480 (.A(b[2]),
	.B(n482),
	.Z(n510));
   OAI22_X1 U481 (.A1(n526),
	.A2(n509),
	.B1(n527),
	.B2(n479),
	.ZN(n168));
   XOR2_X1 U482 (.A(b[3]),
	.B(n482),
	.Z(n526));
   OAI22_X1 U483 (.A1(n527),
	.A2(n509),
	.B1(n528),
	.B2(n479),
	.ZN(n167));
   OAI22_X1 U484 (.A1(n528),
	.A2(n509),
	.B1(n529),
	.B2(n479),
	.ZN(n166));
   XOR2_X1 U485 (.A(b[5]),
	.B(n482),
	.Z(n528));
   OAI22_X1 U486 (.A1(n530),
	.A2(n509),
	.B1(n531),
	.B2(n479),
	.ZN(n164));
   OAI22_X1 U487 (.A1(n532),
	.A2(n509),
	.B1(n392),
	.B2(n479),
	.ZN(n162));
   OAI22_X1 U489 (.A1(n534),
	.A2(n535),
	.B1(FE_OFN1_n504),
	.B2(n536),
	.ZN(n159));
   XOR2_X1 U490 (.A(n487),
	.B(a[3]),
	.Z(n534));
   OAI22_X1 U491 (.A1(n536),
	.A2(n535),
	.B1(FE_OFN1_n504),
	.B2(n537),
	.ZN(n158));
   XOR2_X1 U492 (.A(b[1]),
	.B(n483),
	.Z(n536));
   OAI22_X1 U493 (.A1(n537),
	.A2(n535),
	.B1(FE_OFN1_n504),
	.B2(n538),
	.ZN(n157));
   XOR2_X1 U494 (.A(b[2]),
	.B(n483),
	.Z(n537));
   OAI22_X1 U495 (.A1(n538),
	.A2(n535),
	.B1(FE_OFN1_n504),
	.B2(n539),
	.ZN(n156));
   XOR2_X1 U496 (.A(b[3]),
	.B(n483),
	.Z(n538));
   OAI22_X1 U497 (.A1(n539),
	.A2(n535),
	.B1(FE_OFN1_n504),
	.B2(n540),
	.ZN(n155));
   XOR2_X1 U498 (.A(b[4]),
	.B(n483),
	.Z(n539));
   OAI22_X1 U499 (.A1(n540),
	.A2(n535),
	.B1(FE_OFN1_n504),
	.B2(n541),
	.ZN(n154));
   XOR2_X1 U500 (.A(b[5]),
	.B(n483),
	.Z(n540));
   OAI22_X1 U501 (.A1(n541),
	.A2(n535),
	.B1(FE_OFN1_n504),
	.B2(n542),
	.ZN(n153));
   XOR2_X1 U502 (.A(b[6]),
	.B(n483),
	.Z(n541));
   OAI22_X1 U503 (.A1(n542),
	.A2(n535),
	.B1(FE_OFN1_n504),
	.B2(n514),
	.ZN(n152));
   XOR2_X1 U504 (.A(b[8]),
	.B(n483),
	.Z(n514));
   XOR2_X1 U505 (.A(b[7]),
	.B(n483),
	.Z(n542));
   NAND2_X1 U507 (.A1(FE_OFN1_n504),
	.A2(n543),
	.ZN(n535));
   XOR2_X1 U508 (.A(a[3]),
	.B(a[2]),
	.Z(n543));
   NOR2_X1 U509 (.A1(n522),
	.A2(n487),
	.ZN(n149));
   OAI22_X1 U510 (.A1(n544),
	.A2(n521),
	.B1(n522),
	.B2(n545),
	.ZN(n148));
   XOR2_X1 U511 (.A(n487),
	.B(a[5]),
	.Z(n544));
   OAI22_X1 U512 (.A1(n545),
	.A2(n521),
	.B1(n522),
	.B2(n546),
	.ZN(n147));
   XOR2_X1 U513 (.A(b[1]),
	.B(n484),
	.Z(n545));
   XOR2_X1 U514 (.A(b[2]),
	.B(n484),
	.Z(n546));
   OAI22_X1 U515 (.A1(n547),
	.A2(n521),
	.B1(n522),
	.B2(n548),
	.ZN(n145));
   XOR2_X1 U516 (.A(b[3]),
	.B(n484),
	.Z(n547));
   OAI22_X1 U517 (.A1(n548),
	.A2(n521),
	.B1(n522),
	.B2(n549),
	.ZN(n144));
   XOR2_X1 U518 (.A(b[4]),
	.B(n484),
	.Z(n548));
   OAI22_X1 U519 (.A1(n549),
	.A2(n521),
	.B1(n522),
	.B2(n550),
	.ZN(n143));
   XOR2_X1 U520 (.A(b[5]),
	.B(n484),
	.Z(n549));
   XOR2_X1 U521 (.A(b[6]),
	.B(n484),
	.Z(n550));
   OAI22_X1 U522 (.A1(n551),
	.A2(n521),
	.B1(n522),
	.B2(n552),
	.ZN(n141));
   XOR2_X1 U523 (.A(b[7]),
	.B(n484),
	.Z(n551));
   OAI22_X1 U524 (.A1(n552),
	.A2(n521),
	.B1(n522),
	.B2(n520),
	.ZN(n140));
   XOR2_X1 U525 (.A(b[9]),
	.B(n484),
	.Z(n520));
   XOR2_X1 U526 (.A(b[8]),
	.B(n484),
	.Z(n552));
   XOR2_X1 U528 (.A(b[10]),
	.B(n484),
	.Z(n523));
   NOR2_X1 U529 (.A1(n517),
	.A2(n487),
	.ZN(n138));
   OAI22_X1 U530 (.A1(n554),
	.A2(n516),
	.B1(n517),
	.B2(n555),
	.ZN(n137));
   XOR2_X1 U531 (.A(n487),
	.B(a[7]),
	.Z(n554));
   OAI22_X1 U532 (.A1(n555),
	.A2(n516),
	.B1(n517),
	.B2(n556),
	.ZN(n136));
   XOR2_X1 U533 (.A(b[1]),
	.B(n485),
	.Z(n555));
   OAI22_X1 U534 (.A1(n556),
	.A2(n516),
	.B1(n517),
	.B2(n557),
	.ZN(n135));
   XOR2_X1 U535 (.A(b[2]),
	.B(n485),
	.Z(n556));
   OAI22_X1 U536 (.A1(n557),
	.A2(n516),
	.B1(n517),
	.B2(n515),
	.ZN(n134));
   XOR2_X1 U537 (.A(b[4]),
	.B(n485),
	.Z(n515));
   XOR2_X1 U538 (.A(b[3]),
	.B(n485),
	.Z(n557));
   OAI22_X1 U539 (.A1(n518),
	.A2(n516),
	.B1(n517),
	.B2(n558),
	.ZN(n132));
   XOR2_X1 U540 (.A(b[5]),
	.B(n485),
	.Z(n518));
   OAI22_X1 U541 (.A1(n558),
	.A2(n516),
	.B1(n517),
	.B2(n559),
	.ZN(n131));
   XOR2_X1 U542 (.A(b[6]),
	.B(n485),
	.Z(n558));
   OAI22_X1 U543 (.A1(n559),
	.A2(n516),
	.B1(n517),
	.B2(n560),
	.ZN(n130));
   XOR2_X1 U544 (.A(b[7]),
	.B(n485),
	.Z(n559));
   OAI22_X1 U545 (.A1(n560),
	.A2(n516),
	.B1(n517),
	.B2(n524),
	.ZN(n129));
   XOR2_X1 U546 (.A(b[9]),
	.B(n485),
	.Z(n524));
   XOR2_X1 U547 (.A(b[8]),
	.B(n485),
	.Z(n560));
   XOR2_X1 U549 (.A(b[10]),
	.B(n485),
	.Z(n525));
   NOR2_X1 U550 (.A1(n491),
	.A2(n487),
	.ZN(n127));
   OAI22_X1 U551 (.A1(n562),
	.A2(n492),
	.B1(n491),
	.B2(n563),
	.ZN(n126));
   XOR2_X1 U552 (.A(n487),
	.B(a[9]),
	.Z(n562));
   OAI22_X1 U553 (.A1(n563),
	.A2(n492),
	.B1(n491),
	.B2(n564),
	.ZN(n125));
   XOR2_X1 U554 (.A(b[1]),
	.B(n486),
	.Z(n563));
   XOR2_X1 U555 (.A(b[2]),
	.B(n486),
	.Z(n564));
   OAI22_X1 U556 (.A1(n565),
	.A2(n492),
	.B1(n491),
	.B2(n566),
	.ZN(n123));
   XOR2_X1 U557 (.A(b[3]),
	.B(n486),
	.Z(n565));
   OAI22_X1 U558 (.A1(n566),
	.A2(n492),
	.B1(n491),
	.B2(n567),
	.ZN(n122));
   XOR2_X1 U559 (.A(b[4]),
	.B(n486),
	.Z(n566));
   OAI22_X1 U560 (.A1(n567),
	.A2(n492),
	.B1(n491),
	.B2(n568),
	.ZN(n121));
   XOR2_X1 U561 (.A(b[5]),
	.B(n486),
	.Z(n567));
   OAI22_X1 U562 (.A1(n568),
	.A2(n492),
	.B1(n491),
	.B2(n569),
	.ZN(n120));
   XOR2_X1 U563 (.A(b[6]),
	.B(n486),
	.Z(n568));
   OAI22_X1 U564 (.A1(n569),
	.A2(n492),
	.B1(n491),
	.B2(n570),
	.ZN(n119));
   XOR2_X1 U565 (.A(b[7]),
	.B(n486),
	.Z(n569));
   OAI22_X1 U566 (.A1(n570),
	.A2(n492),
	.B1(n491),
	.B2(n493),
	.ZN(n118));
   XNOR2_X1 U567 (.A(b[9]),
	.B(a[9]),
	.ZN(n493));
   XOR2_X1 U568 (.A(b[8]),
	.B(n486),
	.Z(n570));
   OAI21_X1 U569 (.A(n571),
	.B1(n484),
	.B2(n521),
	.ZN(n114));
   OR3_X1 U570 (.A1(n522),
	.A2(b[0]),
	.A3(n484),
	.ZN(n571));
   NAND2_X1 U571 (.A1(n522),
	.A2(n572),
	.ZN(n521));
   XOR2_X1 U572 (.A(a[5]),
	.B(a[4]),
	.Z(n572));
   OAI21_X1 U573 (.A(n573),
	.B1(n485),
	.B2(n516),
	.ZN(n113));
   OR3_X1 U574 (.A1(n517),
	.A2(b[0]),
	.A3(n485),
	.ZN(n573));
   NAND2_X1 U575 (.A1(n517),
	.A2(n574),
	.ZN(n516));
   XOR2_X1 U576 (.A(a[7]),
	.B(a[6]),
	.Z(n574));
   OAI21_X1 U577 (.A(n575),
	.B1(n486),
	.B2(n492),
	.ZN(n112));
   OR3_X1 U578 (.A1(n491),
	.A2(b[0]),
	.A3(n486),
	.ZN(n575));
   NAND2_X1 U579 (.A1(n491),
	.A2(n576),
	.ZN(n492));
   XOR2_X1 U580 (.A(a[9]),
	.B(a[8]),
	.Z(n576));
endmodule

module IIR_DW_mult_tc_1 (
	a, 
	b, 
	product, 
	p_1, 
	p_2, 
	p_3);
   input [9:0] a;
   input [10:0] b;
   output [20:0] product;
   input p_1;
   input p_2;
   input p_3;

   // Internal wires
   wire FE_OFN3_n506;
   wire n2;
   wire n5;
   wire n6;
   wire n7;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n115;
   wire n116;
   wire n117;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n160;
   wire n161;
   wire n162;
   wire n165;
   wire n166;
   wire n167;
   wire n168;
   wire n169;
   wire n170;
   wire n171;
   wire n172;
   wire n329;
   wire n330;
   wire n331;
   wire n332;
   wire n333;
   wire n334;
   wire n337;
   wire n341;
   wire n343;
   wire n344;
   wire n346;
   wire n347;
   wire n349;
   wire n350;
   wire n351;
   wire n352;
   wire n353;
   wire n354;
   wire n355;
   wire n356;
   wire n357;
   wire n359;
   wire n364;
   wire n365;
   wire n366;
   wire n367;
   wire n368;
   wire n369;
   wire n370;
   wire n371;
   wire n376;
   wire n377;
   wire n378;
   wire n379;
   wire n381;
   wire n382;
   wire n383;
   wire n384;
   wire n389;
   wire n390;
   wire n392;
   wire n393;
   wire n394;
   wire n395;
   wire n399;
   wire n400;
   wire n401;
   wire n404;
   wire n406;
   wire n407;
   wire n408;
   wire n409;
   wire n410;
   wire n411;
   wire n412;
   wire n413;
   wire n414;
   wire n415;
   wire n416;
   wire n418;
   wire n419;
   wire n422;
   wire n423;
   wire n424;
   wire n425;
   wire n426;
   wire n427;
   wire n428;
   wire n429;
   wire n432;
   wire n435;
   wire n436;
   wire n437;
   wire n438;
   wire n439;
   wire n440;
   wire n441;
   wire n442;
   wire n443;
   wire n444;
   wire n445;
   wire n446;
   wire n447;
   wire n449;
   wire n450;
   wire n451;
   wire n452;
   wire n453;
   wire n454;
   wire n455;
   wire n456;
   wire n458;
   wire n459;
   wire n460;
   wire n461;
   wire n463;
   wire n464;
   wire n465;
   wire n466;
   wire n467;
   wire n468;
   wire n469;
   wire n470;
   wire n471;
   wire n472;
   wire n473;
   wire n476;
   wire n477;
   wire n478;
   wire n479;
   wire n481;
   wire n482;
   wire n483;
   wire n484;
   wire n485;
   wire n486;
   wire n488;
   wire n489;
   wire n490;
   wire n491;
   wire n492;
   wire n493;
   wire n494;
   wire n495;
   wire n496;
   wire n497;
   wire n498;
   wire n499;
   wire n500;
   wire n501;
   wire n502;
   wire n503;
   wire n504;
   wire n505;
   wire n506;
   wire n507;
   wire n508;
   wire n509;
   wire n510;
   wire n511;
   wire n512;
   wire n513;
   wire n514;
   wire n515;
   wire n516;
   wire n517;
   wire n518;
   wire n519;
   wire n520;
   wire n521;
   wire n522;
   wire n523;
   wire n524;
   wire n525;
   wire n526;
   wire n527;
   wire n528;
   wire n529;
   wire n530;
   wire n531;
   wire n532;
   wire n533;
   wire n534;
   wire n535;
   wire n536;
   wire n537;
   wire n538;
   wire n539;
   wire n540;
   wire n541;
   wire n542;
   wire n543;
   wire n544;
   wire n545;
   wire n546;
   wire n547;
   wire n548;
   wire n549;
   wire n550;
   wire n551;
   wire n552;
   wire n553;
   wire n554;
   wire n555;
   wire n556;
   wire n557;
   wire n558;
   wire n559;
   wire n560;
   wire n561;
   wire n562;
   wire n563;

   AOI21_X1 FE_RC_6_0 (.A(n507),
	.B1(FE_OFN3_n506),
	.B2(n442),
	.ZN(n540));
   OAI21_X1 FE_RC_5_0 (.A(n503),
	.B1(n459),
	.B2(n460),
	.ZN(n153));
   OAI21_X1 FE_RC_4_0 (.A(n478),
	.B1(n479),
	.B2(n470),
	.ZN(n477));
   AOI21_X1 FE_RC_1_0 (.A(n509),
	.B1(n501),
	.B2(n365),
	.ZN(n548));
   AOI21_X1 FE_RC_0_0 (.A(n519),
	.B1(a[0]),
	.B2(n493),
	.ZN(n520));
   CLKBUF_X1 FE_OFC3_n506 (.A(n506),
	.Z(FE_OFN3_n506));
   FA_X1 U22 (.A(n121),
	.B(n26),
	.CI(n466),
	.CO(n22),
	.S(n23));
   FA_X1 U23 (.A(n467),
	.B(n122),
	.CI(n30),
	.CO(n24),
	.S(n25));
   FA_X1 U25 (.A(n34),
	.B(n123),
	.CI(n31),
	.CO(n28),
	.S(n29));
   FA_X1 U26 (.A(n132),
	.B(n36),
	.CI(n463),
	.CO(n30),
	.S(n31));
   FA_X1 U27 (.A(n35),
	.B(n42),
	.CI(n40),
	.CO(n32),
	.S(n33));
   FA_X1 U28 (.A(n124),
	.B(n133),
	.CI(n464),
	.CO(n34),
	.S(n35));
   FA_X1 U30 (.A(n46),
	.B(n43),
	.CI(n41),
	.CO(n38),
	.S(n39));
   FA_X1 U31 (.A(n458),
	.B(n143),
	.CI(n48),
	.CO(n40),
	.S(n41));
   FA_X1 U32 (.A(n134),
	.B(n125),
	.CI(n153),
	.CO(n42),
	.S(n43));
   FA_X1 U33 (.A(n54),
	.B(n49),
	.CI(n47),
	.CO(n44),
	.S(n45));
   FA_X1 U34 (.A(n58),
	.B(n51),
	.CI(n56),
	.CO(n46),
	.S(n47));
   FA_X1 U35 (.A(n135),
	.B(n126),
	.CI(n144),
	.CO(n48),
	.S(n49));
   FA_X1 U37 (.A(n62),
	.B(n57),
	.CI(n55),
	.CO(n52),
	.S(n53));
   FA_X1 U38 (.A(n59),
	.B(n66),
	.CI(n64),
	.CO(n54),
	.S(n55));
   FA_X1 U39 (.A(n145),
	.B(n127),
	.CI(n453),
	.CO(n56),
	.S(n57));
   FA_X1 U42 (.A(n70),
	.B(n65),
	.CI(n63),
	.CO(n60),
	.S(n61));
   FA_X1 U43 (.A(n67),
	.B(n74),
	.CI(n72),
	.CO(n62),
	.S(n63));
   FA_X1 U44 (.A(n155),
	.B(n146),
	.CI(n165),
	.CO(n64),
	.S(n65));
   HA_X1 U45 (.A(n128),
	.B(n137),
	.CO(n66),
	.S(n67));
   FA_X1 U46 (.A(n73),
	.B(n78),
	.CI(n71),
	.CO(n68),
	.S(n69));
   FA_X1 U47 (.A(n75),
	.B(n166),
	.CI(n80),
	.CO(n70),
	.S(n71));
   FA_X1 U48 (.A(n138),
	.B(n147),
	.CI(n156),
	.CO(n72),
	.S(n73));
   HA_X1 U49 (.A(n115),
	.B(n129),
	.CO(n74),
	.S(n75));
   FA_X1 U50 (.A(n81),
	.B(n84),
	.CI(n79),
	.CO(n76),
	.S(n77));
   FA_X1 U51 (.A(n139),
	.B(n157),
	.CI(n86),
	.CO(n78),
	.S(n79));
   FA_X1 U52 (.A(n148),
	.B(n130),
	.CI(n167),
	.CO(n80),
	.S(n81));
   FA_X1 U53 (.A(n90),
	.B(n85),
	.CI(n87),
	.CO(n82),
	.S(n83));
   FA_X1 U54 (.A(n158),
	.B(n168),
	.CI(n149),
	.CO(n84),
	.S(n85));
   HA_X1 U55 (.A(n116),
	.B(n140),
	.CO(n86),
	.S(n87));
   HA_X1 U59 (.A(n151),
	.B(n117),
	.CO(n94),
	.S(n95));
   FA_X1 U60 (.A(n152),
	.B(n171),
	.CI(n161),
	.CO(n96),
	.S(n97));
   NAND2_X1 U253 (.A1(n450),
	.A2(n53),
	.ZN(n329));
   OAI22_X1 U254 (.A1(n524),
	.A2(n522),
	.B1(n432),
	.B2(n525),
	.ZN(n160));
   AND3_X1 U255 (.A1(n418),
	.A2(n329),
	.A3(n419),
	.ZN(n412));
   XOR2_X1 U256 (.A(a[8]),
	.B(a[7]),
	.Z(n479));
   OAI22_X1 U257 (.A1(n494),
	.A2(n493),
	.B1(n512),
	.B2(a[0]),
	.ZN(n172));
   NAND2_X1 U258 (.A1(n82),
	.A2(n77),
	.ZN(n416));
   INV_X1 U259 (.A(n45),
	.ZN(n423));
   INV_X1 U260 (.A(n52),
	.ZN(n422));
   INV_X1 U261 (.A(n479),
	.ZN(n471));
   AOI22_X1 U262 (.A1(n472),
	.A2(n470),
	.B1(n479),
	.B2(n478),
	.ZN(n21));
   NAND3_X1 U263 (.A1(n414),
	.A2(n415),
	.A3(n416),
	.ZN(n330));
   AND2_X1 U264 (.A1(n162),
	.A2(n172),
	.ZN(n331));
   AND3_X1 U265 (.A1(n355),
	.A2(n356),
	.A3(n357),
	.ZN(n332));
   XNOR2_X1 U266 (.A(n25),
	.B(n28),
	.ZN(n333));
   XNOR2_X1 U267 (.A(n22),
	.B(n21),
	.ZN(n334));
   NAND2_X1 U270 (.A1(n93),
	.A2(n96),
	.ZN(n446));
   INV_X1 U271 (.A(n83),
	.ZN(n454));
   AOI21_X1 U272 (.A(n488),
	.B1(a[3]),
	.B2(n460),
	.ZN(n337));
   OAI22_X1 U277 (.A1(n522),
	.A2(n521),
	.B1(n523),
	.B2(n432),
	.ZN(n162));
   XNOR2_X1 U279 (.A(n162),
	.B(n172),
	.ZN(n341));
   INV_X1 U281 (.A(n477),
	.ZN(n413));
   AND4_X1 U282 (.A1(n162),
	.A2(n172),
	.A3(n343),
	.A4(n344),
	.ZN(n390));
   INV_X1 U283 (.A(n486),
	.ZN(n343));
   INV_X1 U284 (.A(n337),
	.ZN(n344));
   NAND3_X1 U286 (.A1(n394),
	.A2(n393),
	.A3(n395),
	.ZN(n346));
   NAND3_X1 U287 (.A1(n408),
	.A2(n407),
	.A3(n406),
	.ZN(n347));
   XNOR2_X1 U288 (.A(n378),
	.B(n334),
	.ZN(product[18]));
   XNOR2_X1 U290 (.A(n349),
	.B(n399),
	.ZN(product[13]));
   XNOR2_X1 U291 (.A(n39),
	.B(n44),
	.ZN(n349));
   XOR2_X1 U292 (.A(n169),
	.B(n141),
	.Z(n350));
   XOR2_X1 U293 (.A(n350),
	.B(n159),
	.Z(n91));
   XOR2_X1 U294 (.A(n94),
	.B(n150),
	.Z(n351));
   XOR2_X1 U295 (.A(n351),
	.B(n91),
	.Z(n89));
   NAND2_X1 U296 (.A1(n169),
	.A2(n141),
	.ZN(n352));
   NAND2_X1 U297 (.A1(n169),
	.A2(n159),
	.ZN(n353));
   NAND2_X1 U298 (.A1(n141),
	.A2(n159),
	.ZN(n354));
   NAND3_X1 U299 (.A1(n352),
	.A2(n353),
	.A3(n354),
	.ZN(n90));
   NAND2_X1 U300 (.A1(n94),
	.A2(n150),
	.ZN(n355));
   NAND2_X1 U301 (.A1(n94),
	.A2(n91),
	.ZN(n356));
   NAND2_X1 U302 (.A1(n150),
	.A2(n91),
	.ZN(n357));
   AND2_X1 U304 (.A1(n97),
	.A2(n331),
	.ZN(n359));
   AND3_X1 U306 (.A1(n424),
	.A2(n425),
	.A3(n426),
	.ZN(n371));
   XNOR2_X1 U310 (.A(n364),
	.B(n95),
	.ZN(n93));
   XNOR2_X1 U311 (.A(n160),
	.B(n170),
	.ZN(n364));
   XNOR2_X1 U313 (.A(a[3]),
	.B(a[4]),
	.ZN(n506));
   NAND2_X1 U314 (.A1(n501),
	.A2(n561),
	.ZN(n365));
   NAND2_X1 U315 (.A1(n501),
	.A2(n561),
	.ZN(n366));
   NAND2_X1 U316 (.A1(n501),
	.A2(n561),
	.ZN(n500));
   AND3_X1 U317 (.A1(n329),
	.A2(n418),
	.A3(n419),
	.ZN(n367));
   NAND2_X1 U320 (.A1(n95),
	.A2(n160),
	.ZN(n368));
   NAND2_X1 U321 (.A1(n95),
	.A2(n170),
	.ZN(n369));
   NAND2_X1 U322 (.A1(n160),
	.A2(n170),
	.ZN(n370));
   NAND3_X1 U323 (.A1(n368),
	.A2(n369),
	.A3(n370),
	.ZN(n92));
   XNOR2_X1 U326 (.A(n5),
	.B(n333),
	.ZN(product[16]));
   NAND2_X1 U330 (.A1(n471),
	.A2(n563),
	.ZN(n510));
   XNOR2_X1 U331 (.A(p_2),
	.B(p_1),
	.ZN(n521));
   NAND3_X1 U332 (.A1(n411),
	.A2(n410),
	.A3(n409),
	.ZN(n376));
   NAND3_X1 U333 (.A1(n440),
	.A2(n441),
	.A3(n439),
	.ZN(n377));
   NAND3_X1 U334 (.A1(n410),
	.A2(n411),
	.A3(n409),
	.ZN(n378));
   OR2_X1 U335 (.A1(n481),
	.A2(n451),
	.ZN(n379));
   XNOR2_X1 U337 (.A(n347),
	.B(n381),
	.ZN(product[17]));
   XNOR2_X1 U338 (.A(n24),
	.B(n23),
	.ZN(n381));
   NAND2_X1 U339 (.A1(n376),
	.A2(n22),
	.ZN(n382));
   NAND2_X1 U340 (.A1(n378),
	.A2(n21),
	.ZN(n383));
   NAND2_X1 U341 (.A1(n22),
	.A2(n21),
	.ZN(n384));
   NAND3_X1 U342 (.A1(n383),
	.A2(n382),
	.A3(n384),
	.ZN(n2));
   INV_X1 U345 (.A(a[5]),
	.ZN(n465));
   XNOR2_X1 U346 (.A(b[1]),
	.B(a[5]),
	.ZN(n532));
   AND2_X1 U349 (.A1(n97),
	.A2(n485),
	.ZN(n389));
   NOR3_X1 U351 (.A1(n389),
	.A2(n359),
	.A3(n390),
	.ZN(n484));
   XOR2_X1 U352 (.A(n32),
	.B(n29),
	.Z(n392));
   XOR2_X1 U353 (.A(n377),
	.B(n392),
	.Z(product[15]));
   NAND2_X1 U354 (.A1(n6),
	.A2(n32),
	.ZN(n393));
   NAND2_X1 U355 (.A1(n6),
	.A2(n29),
	.ZN(n394));
   NAND2_X1 U356 (.A1(n32),
	.A2(n29),
	.ZN(n395));
   NAND3_X1 U357 (.A1(n393),
	.A2(n394),
	.A3(n395),
	.ZN(n5));
   OAI222_X1 U359 (.A1(n412),
	.A2(n423),
	.B1(n367),
	.B2(n422),
	.C1(n422),
	.C2(n423),
	.ZN(n399));
   XNOR2_X1 U360 (.A(a[1]),
	.B(a[2]),
	.ZN(n432));
   XNOR2_X1 U361 (.A(a[3]),
	.B(b[1]),
	.ZN(n523));
   AND3_X1 U362 (.A1(n425),
	.A2(n424),
	.A3(n426),
	.ZN(n400));
   AND3_X1 U363 (.A1(n428),
	.A2(n427),
	.A3(n429),
	.ZN(n401));
   NAND2_X1 U364 (.A1(n489),
	.A2(n530),
	.ZN(n522));
   XNOR2_X1 U366 (.A(n404),
	.B(n435),
	.ZN(product[14]));
   XNOR2_X1 U367 (.A(n33),
	.B(n38),
	.ZN(n404));
   NAND2_X1 U369 (.A1(n25),
	.A2(n28),
	.ZN(n406));
   NAND2_X1 U370 (.A1(n346),
	.A2(n25),
	.ZN(n407));
   NAND2_X1 U371 (.A1(n346),
	.A2(n28),
	.ZN(n408));
   NAND2_X1 U372 (.A1(n24),
	.A2(n23),
	.ZN(n409));
   NAND2_X1 U373 (.A1(n347),
	.A2(n24),
	.ZN(n410));
   NAND2_X1 U374 (.A1(n347),
	.A2(n23),
	.ZN(n411));
   XNOR2_X1 U375 (.A(n2),
	.B(n413),
	.ZN(n476));
   NAND2_X1 U376 (.A1(n482),
	.A2(n77),
	.ZN(n414));
   NAND2_X1 U377 (.A1(n482),
	.A2(n82),
	.ZN(n415));
   NAND2_X1 U379 (.A1(n450),
	.A2(n60),
	.ZN(n418));
   NAND2_X1 U380 (.A1(n60),
	.A2(n53),
	.ZN(n419));
   NAND2_X1 U382 (.A1(n483),
	.A2(n89),
	.ZN(n424));
   NAND2_X1 U383 (.A1(n483),
	.A2(n92),
	.ZN(n425));
   NAND2_X1 U384 (.A1(n92),
	.A2(n89),
	.ZN(n426));
   NAND2_X1 U385 (.A1(n330),
	.A2(n69),
	.ZN(n427));
   NAND2_X1 U386 (.A1(n330),
	.A2(n76),
	.ZN(n428));
   NAND2_X1 U387 (.A1(n76),
	.A2(n69),
	.ZN(n429));
   AND3_X1 U388 (.A1(n427),
	.A2(n428),
	.A3(n429),
	.ZN(n481));
   INV_X1 U389 (.A(n495),
	.ZN(n468));
   INV_X1 U390 (.A(n498),
	.ZN(n461));
   INV_X1 U391 (.A(n520),
	.ZN(n453));
   INV_X1 U392 (.A(n51),
	.ZN(n458));
   INV_X1 U393 (.A(n36),
	.ZN(n464));
   INV_X1 U394 (.A(n540),
	.ZN(n463));
   INV_X1 U395 (.A(n26),
	.ZN(n467));
   INV_X1 U396 (.A(n548),
	.ZN(n466));
   INV_X1 U397 (.A(n511),
	.ZN(n472));
   INV_X1 U398 (.A(n510),
	.ZN(n470));
   XNOR2_X1 U399 (.A(a[1]),
	.B(a[2]),
	.ZN(n489));
   INV_X1 U402 (.A(a[7]),
	.ZN(n469));
   INV_X1 U403 (.A(a[9]),
	.ZN(n473));
   NAND3_X1 U408 (.A1(n438),
	.A2(n436),
	.A3(n437),
	.ZN(n435));
   NAND2_X1 U409 (.A1(n39),
	.A2(n44),
	.ZN(n436));
   NAND2_X1 U410 (.A1(n39),
	.A2(n399),
	.ZN(n437));
   NAND2_X1 U411 (.A1(n399),
	.A2(n44),
	.ZN(n438));
   NAND3_X1 U412 (.A1(n438),
	.A2(n437),
	.A3(n436),
	.ZN(n7));
   NAND2_X1 U413 (.A1(n33),
	.A2(n38),
	.ZN(n439));
   NAND2_X1 U414 (.A1(n7),
	.A2(n33),
	.ZN(n440));
   NAND2_X1 U415 (.A1(n7),
	.A2(n38),
	.ZN(n441));
   NAND3_X1 U416 (.A1(n441),
	.A2(n440),
	.A3(n439),
	.ZN(n6));
   INV_X1 U417 (.A(n522),
	.ZN(n460));
   NAND2_X1 U418 (.A1(FE_OFN3_n506),
	.A2(n559),
	.ZN(n442));
   NAND2_X1 U419 (.A1(FE_OFN3_n506),
	.A2(n559),
	.ZN(n443));
   NAND2_X1 U420 (.A1(n559),
	.A2(FE_OFN3_n506),
	.ZN(n505));
   OR2_X1 U421 (.A1(n455),
	.A2(n484),
	.ZN(n444));
   OR2_X1 U422 (.A1(n484),
	.A2(n456),
	.ZN(n445));
   NAND3_X1 U423 (.A1(n444),
	.A2(n445),
	.A3(n446),
	.ZN(n483));
   OR2_X1 U424 (.A1(n401),
	.A2(n452),
	.ZN(n447));
   OR2_X1 U426 (.A1(n451),
	.A2(n452),
	.ZN(n449));
   NAND3_X1 U427 (.A1(n447),
	.A2(n379),
	.A3(n449),
	.ZN(n450));
   INV_X1 U428 (.A(n96),
	.ZN(n456));
   INV_X1 U429 (.A(n61),
	.ZN(n452));
   INV_X1 U430 (.A(n68),
	.ZN(n451));
   INV_X1 U431 (.A(n93),
	.ZN(n455));
   INV_X1 U432 (.A(n432),
	.ZN(n459));
   XNOR2_X2 U433 (.A(a[6]),
	.B(a[5]),
	.ZN(n501));
   XNOR2_X1 U434 (.A(n476),
	.B(n21),
	.ZN(product[19]));
   OAI222_X1 U436 (.A1(n400),
	.A2(n454),
	.B1(n371),
	.B2(n332),
	.C1(n332),
	.C2(n454),
	.ZN(n482));
   OAI222_X1 U437 (.A1(n341),
	.A2(n486),
	.B1(n486),
	.B2(n337),
	.C1(n341),
	.C2(n337),
	.ZN(n485));
   NOR3_X1 U439 (.A1(n432),
	.A2(b[0]),
	.A3(p_1),
	.ZN(n488));
   MUX2_X1 U440 (.A(n490),
	.B(n491),
	.S(b[0]),
	.Z(n486));
   NAND2_X1 U441 (.A1(n459),
	.A2(n492),
	.ZN(n491));
   NAND3_X1 U442 (.A1(n492),
	.A2(p_3),
	.A3(a[1]),
	.ZN(n490));
   OAI22_X1 U443 (.A1(b[1]),
	.A2(n493),
	.B1(n494),
	.B2(a[0]),
	.ZN(n492));
   XOR2_X1 U444 (.A(n495),
	.B(n496),
	.Z(n59));
   NAND2_X1 U445 (.A1(n468),
	.A2(n496),
	.ZN(n58));
   AOI22_X1 U446 (.A1(n461),
	.A2(n460),
	.B1(n459),
	.B2(n497),
	.ZN(n496));
   OAI22_X1 U447 (.A1(n499),
	.A2(n365),
	.B1(n501),
	.B2(n502),
	.ZN(n495));
   AOI22_X1 U448 (.A1(n497),
	.A2(n460),
	.B1(n459),
	.B2(n503),
	.ZN(n51));
   XOR2_X1 U449 (.A(b[9]),
	.B(a[3]),
	.Z(n497));
   OAI22_X1 U450 (.A1(n504),
	.A2(n443),
	.B1(FE_OFN3_n506),
	.B2(n507),
	.ZN(n36));
   OAI22_X1 U451 (.A1(n508),
	.A2(n365),
	.B1(n501),
	.B2(n509),
	.ZN(n26));
   XOR2_X1 U452 (.A(b[10]),
	.B(a[9]),
	.Z(n478));
   XNOR2_X1 U453 (.A(a[1]),
	.B(b[2]),
	.ZN(n494));
   OAI22_X1 U454 (.A1(n512),
	.A2(n493),
	.B1(n513),
	.B2(a[0]),
	.ZN(n171));
   XNOR2_X1 U455 (.A(a[1]),
	.B(b[3]),
	.ZN(n512));
   OAI22_X1 U456 (.A1(n513),
	.A2(n493),
	.B1(n514),
	.B2(a[0]),
	.ZN(n170));
   XNOR2_X1 U457 (.A(a[1]),
	.B(b[4]),
	.ZN(n513));
   OAI22_X1 U458 (.A1(n514),
	.A2(n493),
	.B1(n515),
	.B2(a[0]),
	.ZN(n169));
   XNOR2_X1 U459 (.A(b[5]),
	.B(a[1]),
	.ZN(n514));
   OAI22_X1 U460 (.A1(n515),
	.A2(n493),
	.B1(n516),
	.B2(a[0]),
	.ZN(n168));
   XNOR2_X1 U461 (.A(b[6]),
	.B(a[1]),
	.ZN(n515));
   OAI22_X1 U462 (.A1(n516),
	.A2(n493),
	.B1(n517),
	.B2(a[0]),
	.ZN(n167));
   XNOR2_X1 U463 (.A(b[7]),
	.B(a[1]),
	.ZN(n516));
   OAI22_X1 U464 (.A1(n517),
	.A2(n493),
	.B1(n518),
	.B2(a[0]),
	.ZN(n166));
   XNOR2_X1 U465 (.A(b[8]),
	.B(a[1]),
	.ZN(n517));
   OAI22_X1 U466 (.A1(n518),
	.A2(n493),
	.B1(n519),
	.B2(a[0]),
	.ZN(n165));
   XNOR2_X1 U467 (.A(b[9]),
	.B(a[1]),
	.ZN(n518));
   NAND2_X1 U469 (.A1(a[1]),
	.A2(a[0]),
	.ZN(n493));
   XNOR2_X1 U470 (.A(b[10]),
	.B(a[1]),
	.ZN(n519));
   OAI22_X1 U471 (.A1(n523),
	.A2(n522),
	.B1(n432),
	.B2(n524),
	.ZN(n161));
   XOR2_X1 U472 (.A(p_1),
	.B(b[2]),
	.Z(n524));
   OAI22_X1 U473 (.A1(n525),
	.A2(n522),
	.B1(n526),
	.B2(n432),
	.ZN(n159));
   XOR2_X1 U474 (.A(b[3]),
	.B(p_1),
	.Z(n525));
   OAI22_X1 U475 (.A1(n526),
	.A2(n522),
	.B1(n432),
	.B2(n527),
	.ZN(n158));
   XOR2_X1 U476 (.A(b[4]),
	.B(p_1),
	.Z(n526));
   OAI22_X1 U477 (.A1(n527),
	.A2(n522),
	.B1(n432),
	.B2(n528),
	.ZN(n157));
   XOR2_X1 U478 (.A(b[5]),
	.B(p_1),
	.Z(n527));
   OAI22_X1 U479 (.A1(n528),
	.A2(n522),
	.B1(n432),
	.B2(n529),
	.ZN(n156));
   XOR2_X1 U480 (.A(b[6]),
	.B(p_1),
	.Z(n528));
   OAI22_X1 U481 (.A1(n529),
	.A2(n522),
	.B1(n432),
	.B2(n498),
	.ZN(n155));
   XOR2_X1 U482 (.A(b[8]),
	.B(p_1),
	.Z(n498));
   XOR2_X1 U483 (.A(b[7]),
	.B(p_1),
	.Z(n529));
   XOR2_X1 U485 (.A(a[3]),
	.B(a[2]),
	.Z(n530));
   XOR2_X1 U486 (.A(b[10]),
	.B(a[3]),
	.Z(n503));
   NOR2_X1 U487 (.A1(FE_OFN3_n506),
	.A2(p_2),
	.ZN(n152));
   OAI22_X1 U488 (.A1(n505),
	.A2(n531),
	.B1(FE_OFN3_n506),
	.B2(n532),
	.ZN(n151));
   XOR2_X1 U489 (.A(p_2),
	.B(a[5]),
	.Z(n531));
   OAI22_X1 U490 (.A1(n532),
	.A2(n443),
	.B1(FE_OFN3_n506),
	.B2(n533),
	.ZN(n150));
   OAI22_X1 U491 (.A1(n533),
	.A2(n442),
	.B1(FE_OFN3_n506),
	.B2(n534),
	.ZN(n149));
   XOR2_X1 U492 (.A(b[2]),
	.B(n465),
	.Z(n533));
   OAI22_X1 U493 (.A1(n534),
	.A2(n442),
	.B1(FE_OFN3_n506),
	.B2(n535),
	.ZN(n148));
   XOR2_X1 U494 (.A(b[3]),
	.B(n465),
	.Z(n534));
   OAI22_X1 U495 (.A1(n535),
	.A2(n443),
	.B1(FE_OFN3_n506),
	.B2(n536),
	.ZN(n147));
   XOR2_X1 U496 (.A(b[4]),
	.B(n465),
	.Z(n535));
   OAI22_X1 U497 (.A1(n536),
	.A2(n442),
	.B1(FE_OFN3_n506),
	.B2(n537),
	.ZN(n146));
   XOR2_X1 U498 (.A(b[5]),
	.B(n465),
	.Z(n536));
   OAI22_X1 U499 (.A1(n537),
	.A2(n443),
	.B1(FE_OFN3_n506),
	.B2(n538),
	.ZN(n145));
   XOR2_X1 U500 (.A(b[6]),
	.B(n465),
	.Z(n537));
   OAI22_X1 U501 (.A1(n538),
	.A2(n442),
	.B1(FE_OFN3_n506),
	.B2(n539),
	.ZN(n144));
   XOR2_X1 U502 (.A(b[7]),
	.B(n465),
	.Z(n538));
   OAI22_X1 U503 (.A1(n539),
	.A2(n443),
	.B1(FE_OFN3_n506),
	.B2(n504),
	.ZN(n143));
   XOR2_X1 U504 (.A(b[9]),
	.B(n465),
	.Z(n504));
   XOR2_X1 U505 (.A(b[8]),
	.B(n465),
	.Z(n539));
   XOR2_X1 U507 (.A(b[10]),
	.B(n465),
	.Z(n507));
   NOR2_X1 U508 (.A1(n501),
	.A2(p_2),
	.ZN(n141));
   OAI22_X1 U509 (.A1(n541),
	.A2(n500),
	.B1(n501),
	.B2(n542),
	.ZN(n140));
   XOR2_X1 U510 (.A(p_2),
	.B(a[7]),
	.Z(n541));
   OAI22_X1 U511 (.A1(n542),
	.A2(n365),
	.B1(n501),
	.B2(n543),
	.ZN(n139));
   XOR2_X1 U512 (.A(p_3),
	.B(a[7]),
	.Z(n542));
   OAI22_X1 U513 (.A1(n543),
	.A2(n365),
	.B1(n501),
	.B2(n544),
	.ZN(n138));
   XOR2_X1 U514 (.A(b[2]),
	.B(n469),
	.Z(n543));
   OAI22_X1 U515 (.A1(n544),
	.A2(n366),
	.B1(n501),
	.B2(n499),
	.ZN(n137));
   XOR2_X1 U516 (.A(b[4]),
	.B(n469),
	.Z(n499));
   XOR2_X1 U517 (.A(b[3]),
	.B(n469),
	.Z(n544));
   OAI22_X1 U518 (.A1(n502),
	.A2(n366),
	.B1(n501),
	.B2(n545),
	.ZN(n135));
   XOR2_X1 U519 (.A(b[5]),
	.B(n469),
	.Z(n502));
   OAI22_X1 U520 (.A1(n545),
	.A2(n366),
	.B1(n501),
	.B2(n546),
	.ZN(n134));
   XOR2_X1 U521 (.A(b[6]),
	.B(n469),
	.Z(n545));
   OAI22_X1 U522 (.A1(n546),
	.A2(n366),
	.B1(n501),
	.B2(n547),
	.ZN(n133));
   XOR2_X1 U523 (.A(b[7]),
	.B(n469),
	.Z(n546));
   OAI22_X1 U524 (.A1(n547),
	.A2(n366),
	.B1(n501),
	.B2(n508),
	.ZN(n132));
   XOR2_X1 U525 (.A(b[9]),
	.B(n469),
	.Z(n508));
   XOR2_X1 U526 (.A(b[8]),
	.B(n469),
	.Z(n547));
   XOR2_X1 U528 (.A(b[10]),
	.B(n469),
	.Z(n509));
   NOR2_X1 U529 (.A1(n471),
	.A2(p_2),
	.ZN(n130));
   OAI22_X1 U530 (.A1(n549),
	.A2(n510),
	.B1(n471),
	.B2(n550),
	.ZN(n129));
   XOR2_X1 U531 (.A(p_2),
	.B(a[9]),
	.Z(n549));
   OAI22_X1 U532 (.A1(n550),
	.A2(n510),
	.B1(n471),
	.B2(n551),
	.ZN(n128));
   XOR2_X1 U533 (.A(p_3),
	.B(a[9]),
	.Z(n550));
   OAI22_X1 U534 (.A1(n551),
	.A2(n510),
	.B1(n471),
	.B2(n552),
	.ZN(n127));
   XOR2_X1 U535 (.A(b[2]),
	.B(n473),
	.Z(n551));
   OAI22_X1 U536 (.A1(n552),
	.A2(n510),
	.B1(n471),
	.B2(n553),
	.ZN(n126));
   XOR2_X1 U537 (.A(b[3]),
	.B(n473),
	.Z(n552));
   OAI22_X1 U538 (.A1(n553),
	.A2(n510),
	.B1(n471),
	.B2(n554),
	.ZN(n125));
   XOR2_X1 U539 (.A(b[4]),
	.B(n473),
	.Z(n553));
   OAI22_X1 U540 (.A1(n554),
	.A2(n510),
	.B1(n471),
	.B2(n555),
	.ZN(n124));
   XOR2_X1 U541 (.A(b[5]),
	.B(n473),
	.Z(n554));
   OAI22_X1 U542 (.A1(n555),
	.A2(n510),
	.B1(n471),
	.B2(n556),
	.ZN(n123));
   XOR2_X1 U543 (.A(b[6]),
	.B(n473),
	.Z(n555));
   OAI22_X1 U544 (.A1(n556),
	.A2(n510),
	.B1(n471),
	.B2(n557),
	.ZN(n122));
   XOR2_X1 U545 (.A(b[7]),
	.B(n473),
	.Z(n556));
   OAI22_X1 U546 (.A1(n557),
	.A2(n510),
	.B1(n471),
	.B2(n511),
	.ZN(n121));
   XOR2_X1 U547 (.A(b[9]),
	.B(n473),
	.Z(n511));
   XOR2_X1 U548 (.A(b[8]),
	.B(n473),
	.Z(n557));
   OAI21_X1 U549 (.A(n558),
	.B1(n505),
	.B2(n465),
	.ZN(n117));
   OR3_X1 U550 (.A1(FE_OFN3_n506),
	.A2(b[0]),
	.A3(n465),
	.ZN(n558));
   XOR2_X1 U551 (.A(a[5]),
	.B(a[4]),
	.Z(n559));
   OAI21_X1 U552 (.A(n560),
	.B1(n469),
	.B2(n500),
	.ZN(n116));
   OR3_X1 U553 (.A1(n501),
	.A2(b[0]),
	.A3(n469),
	.ZN(n560));
   XOR2_X1 U554 (.A(a[7]),
	.B(a[6]),
	.Z(n561));
   OAI21_X1 U555 (.A(n562),
	.B1(n473),
	.B2(n510),
	.ZN(n115));
   NAND3_X1 U556 (.A1(n479),
	.A2(p_2),
	.A3(a[9]),
	.ZN(n562));
   XOR2_X1 U557 (.A(a[9]),
	.B(a[8]),
	.Z(n563));
endmodule

module IIR_DW_mult_tc_0 (
	a, 
	b, 
	product);
   input [9:0] a;
   input [10:0] b;
   output [20:0] product;

   // Internal wires
   wire FE_OFN4_n371;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n112;
   wire n113;
   wire n114;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n162;
   wire n163;
   wire n164;
   wire n165;
   wire n166;
   wire n167;
   wire n168;
   wire n169;
   wire n324;
   wire n325;
   wire n326;
   wire n327;
   wire n328;
   wire n329;
   wire n330;
   wire n331;
   wire n332;
   wire n333;
   wire n334;
   wire n335;
   wire n336;
   wire n337;
   wire n338;
   wire n339;
   wire n340;
   wire n341;
   wire n342;
   wire n343;
   wire n344;
   wire n345;
   wire n346;
   wire n347;
   wire n348;
   wire n349;
   wire n350;
   wire n351;
   wire n352;
   wire n353;
   wire n354;
   wire n355;
   wire n356;
   wire n357;
   wire n358;
   wire n359;
   wire n360;
   wire n361;
   wire n362;
   wire n363;
   wire n364;
   wire n365;
   wire n366;
   wire n367;
   wire n368;
   wire n369;
   wire n370;
   wire n371;
   wire n372;
   wire n373;
   wire n374;
   wire n375;
   wire n376;
   wire n377;
   wire n378;
   wire n379;
   wire n380;
   wire n381;
   wire n382;
   wire n383;
   wire n384;
   wire n385;
   wire n386;
   wire n387;
   wire n388;
   wire n389;
   wire n390;
   wire n391;
   wire n392;
   wire n393;
   wire n394;
   wire n395;
   wire n396;
   wire n397;
   wire n398;
   wire n399;
   wire n400;
   wire n401;
   wire n402;
   wire n403;
   wire n404;
   wire n405;
   wire n406;
   wire n407;
   wire n408;
   wire n409;
   wire n410;
   wire n411;
   wire n412;
   wire n413;
   wire n414;
   wire n415;
   wire n416;
   wire n417;
   wire n418;
   wire n419;
   wire n420;
   wire n421;
   wire n422;
   wire n423;
   wire n424;
   wire n425;
   wire n426;
   wire n427;
   wire n428;
   wire n429;
   wire n430;
   wire n431;
   wire n432;
   wire n433;
   wire n434;
   wire n435;
   wire n436;
   wire n437;
   wire n438;
   wire n439;
   wire n440;
   wire n441;
   wire n442;
   wire n443;
   wire n444;

   OAI21_X1 FE_RC_7_0 (.A(n386),
	.B1(n337),
	.B2(n338),
	.ZN(n150));
   AOI21_X1 FE_RC_3_0 (.A(n390),
	.B1(n389),
	.B2(n388),
	.ZN(n421));
   AOI21_X1 FE_RC_2_0 (.A(n400),
	.B1(n335),
	.B2(n376),
	.ZN(n401));
   CLKBUF_X1 FE_OFC4_n371 (.A(n371),
	.Z(FE_OFN4_n371));
   FA_X1 U3 (.A(n22),
	.B(n21),
	.CI(n3),
	.CO(n2),
	.S(product[17]));
   FA_X1 U4 (.A(n23),
	.B(n26),
	.CI(n4),
	.CO(n3),
	.S(product[16]));
   FA_X1 U5 (.A(n27),
	.B(n30),
	.CI(n5),
	.CO(n4),
	.S(product[15]));
   FA_X1 U6 (.A(n31),
	.B(n36),
	.CI(n6),
	.CO(n5),
	.S(product[14]));
   FA_X1 U7 (.A(n37),
	.B(n42),
	.CI(n324),
	.CO(n6),
	.S(product[13]));
   FA_X1 U21 (.A(n118),
	.B(n24),
	.CI(n346),
	.CO(n20),
	.S(n21));
   FA_X1 U22 (.A(n347),
	.B(n119),
	.CI(n28),
	.CO(n22),
	.S(n23));
   FA_X1 U24 (.A(n32),
	.B(n120),
	.CI(n29),
	.CO(n26),
	.S(n27));
   FA_X1 U25 (.A(n129),
	.B(n34),
	.CI(n343),
	.CO(n28),
	.S(n29));
   FA_X1 U26 (.A(n33),
	.B(n40),
	.CI(n38),
	.CO(n30),
	.S(n31));
   FA_X1 U27 (.A(n121),
	.B(n130),
	.CI(n344),
	.CO(n32),
	.S(n33));
   FA_X1 U29 (.A(n44),
	.B(n41),
	.CI(n39),
	.CO(n36),
	.S(n37));
   FA_X1 U30 (.A(n336),
	.B(n140),
	.CI(n46),
	.CO(n38),
	.S(n39));
   FA_X1 U31 (.A(n131),
	.B(n122),
	.CI(n150),
	.CO(n40),
	.S(n41));
   FA_X1 U32 (.A(n52),
	.B(n47),
	.CI(n45),
	.CO(n42),
	.S(n43));
   FA_X1 U33 (.A(n56),
	.B(n49),
	.CI(n54),
	.CO(n44),
	.S(n45));
   FA_X1 U34 (.A(n132),
	.B(n123),
	.CI(n141),
	.CO(n46),
	.S(n47));
   FA_X1 U36 (.A(n60),
	.B(n55),
	.CI(n53),
	.CO(n50),
	.S(n51));
   FA_X1 U37 (.A(n57),
	.B(n64),
	.CI(n62),
	.CO(n52),
	.S(n53));
   FA_X1 U38 (.A(n142),
	.B(n124),
	.CI(n326),
	.CO(n54),
	.S(n55));
   FA_X1 U41 (.A(n68),
	.B(n63),
	.CI(n61),
	.CO(n58),
	.S(n59));
   FA_X1 U42 (.A(n65),
	.B(n72),
	.CI(n70),
	.CO(n60),
	.S(n61));
   FA_X1 U43 (.A(n152),
	.B(n143),
	.CI(n162),
	.CO(n62),
	.S(n63));
   HA_X1 U44 (.A(n125),
	.B(n134),
	.CO(n64),
	.S(n65));
   FA_X1 U45 (.A(n71),
	.B(n76),
	.CI(n69),
	.CO(n66),
	.S(n67));
   FA_X1 U46 (.A(n73),
	.B(n163),
	.CI(n78),
	.CO(n68),
	.S(n69));
   FA_X1 U47 (.A(n135),
	.B(n144),
	.CI(n153),
	.CO(n70),
	.S(n71));
   HA_X1 U48 (.A(n112),
	.B(n126),
	.CO(n72),
	.S(n73));
   FA_X1 U49 (.A(n79),
	.B(n82),
	.CI(n77),
	.CO(n74),
	.S(n75));
   FA_X1 U50 (.A(n136),
	.B(n154),
	.CI(n84),
	.CO(n76),
	.S(n77));
   FA_X1 U51 (.A(n145),
	.B(n127),
	.CI(n164),
	.CO(n78),
	.S(n79));
   FA_X1 U52 (.A(n88),
	.B(n85),
	.CI(n83),
	.CO(n80),
	.S(n81));
   FA_X1 U53 (.A(n146),
	.B(n165),
	.CI(n155),
	.CO(n82),
	.S(n83));
   HA_X1 U54 (.A(n113),
	.B(n137),
	.CO(n84),
	.S(n85));
   FA_X1 U55 (.A(n92),
	.B(n147),
	.CI(n89),
	.CO(n86),
	.S(n87));
   FA_X1 U56 (.A(n166),
	.B(n138),
	.CI(n156),
	.CO(n88),
	.S(n89));
   FA_X1 U57 (.A(n157),
	.B(n167),
	.CI(n93),
	.CO(n90),
	.S(n91));
   HA_X1 U58 (.A(n114),
	.B(n148),
	.CO(n92),
	.S(n93));
   FA_X1 U59 (.A(n168),
	.B(n149),
	.CI(n158),
	.CO(n94),
	.S(n95));
   HA_X1 U60 (.A(n159),
	.B(n169),
	.CO(n96),
	.S(n97));
   INV_X1 U247 (.A(a[1]),
	.ZN(n340));
   XOR2_X1 U248 (.A(a[2]),
	.B(n340),
	.Z(n371));
   NAND2_X1 U249 (.A1(FE_OFN4_n371),
	.A2(n411),
	.ZN(n403));
   XNOR2_X1 U250 (.A(n352),
	.B(n353),
	.ZN(product[18]));
   INV_X1 U251 (.A(n359),
	.ZN(n325));
   INV_X1 U252 (.A(n360),
	.ZN(n327));
   INV_X1 U253 (.A(n358),
	.ZN(n324));
   INV_X1 U254 (.A(n86),
	.ZN(n331));
   INV_X1 U255 (.A(n81),
	.ZN(n330));
   INV_X1 U256 (.A(n361),
	.ZN(n328));
   INV_X1 U257 (.A(n362),
	.ZN(n329));
   INV_X1 U258 (.A(n378),
	.ZN(n348));
   INV_X1 U259 (.A(n94),
	.ZN(n333));
   INV_X1 U260 (.A(n91),
	.ZN(n332));
   INV_X1 U261 (.A(n403),
	.ZN(n338));
   INV_X1 U262 (.A(FE_OFN4_n371),
	.ZN(n337));
   INV_X1 U263 (.A(n375),
	.ZN(n339));
   INV_X1 U264 (.A(n381),
	.ZN(n341));
   INV_X1 U265 (.A(n401),
	.ZN(n326));
   INV_X1 U266 (.A(n49),
	.ZN(n336));
   INV_X1 U267 (.A(n34),
	.ZN(n344));
   INV_X1 U268 (.A(n421),
	.ZN(n343));
   INV_X1 U269 (.A(n24),
	.ZN(n347));
   INV_X1 U270 (.A(n429),
	.ZN(n346));
   INV_X1 U271 (.A(n97),
	.ZN(n334));
   INV_X1 U272 (.A(a[3]),
	.ZN(n342));
   INV_X1 U273 (.A(b[0]),
	.ZN(n351));
   INV_X1 U274 (.A(a[5]),
	.ZN(n345));
   INV_X1 U275 (.A(a[0]),
	.ZN(n335));
   NAND2_X1 U276 (.A1(a[1]),
	.A2(n335),
	.ZN(n376));
   INV_X1 U277 (.A(a[7]),
	.ZN(n349));
   INV_X1 U278 (.A(a[9]),
	.ZN(n350));
   XNOR2_X2 U279 (.A(a[4]),
	.B(a[3]),
	.ZN(n389));
   XNOR2_X2 U280 (.A(a[6]),
	.B(a[5]),
	.ZN(n384));
   XNOR2_X2 U281 (.A(a[8]),
	.B(a[7]),
	.ZN(n355));
   XOR2_X1 U282 (.A(n20),
	.B(n2),
	.Z(n353));
   OAI22_X1 U283 (.A1(n354),
	.A2(n355),
	.B1(n356),
	.B2(n357),
	.ZN(n352));
   XOR2_X1 U284 (.A(b[10]),
	.B(n350),
	.Z(n354));
   AOI222_X1 U285 (.A1(n325),
	.A2(n43),
	.B1(n325),
	.B2(n50),
	.C1(n50),
	.C2(n43),
	.ZN(n358));
   AOI222_X1 U286 (.A1(n327),
	.A2(n51),
	.B1(n327),
	.B2(n58),
	.C1(n58),
	.C2(n51),
	.ZN(n359));
   AOI222_X1 U287 (.A1(n328),
	.A2(n59),
	.B1(n328),
	.B2(n66),
	.C1(n66),
	.C2(n59),
	.ZN(n360));
   AOI222_X1 U288 (.A1(n329),
	.A2(n67),
	.B1(n329),
	.B2(n74),
	.C1(n74),
	.C2(n67),
	.ZN(n361));
   AOI222_X1 U289 (.A1(n363),
	.A2(n75),
	.B1(n363),
	.B2(n80),
	.C1(n80),
	.C2(n75),
	.ZN(n362));
   OAI222_X1 U290 (.A1(n364),
	.A2(n330),
	.B1(n364),
	.B2(n331),
	.C1(n331),
	.C2(n330),
	.ZN(n363));
   AOI222_X1 U291 (.A1(n365),
	.A2(n87),
	.B1(n365),
	.B2(n90),
	.C1(n90),
	.C2(n87),
	.ZN(n364));
   OAI222_X1 U292 (.A1(n366),
	.A2(n332),
	.B1(n366),
	.B2(n333),
	.C1(n333),
	.C2(n332),
	.ZN(n365));
   AOI222_X1 U293 (.A1(n367),
	.A2(n95),
	.B1(n367),
	.B2(n96),
	.C1(n96),
	.C2(n95),
	.ZN(n366));
   OAI222_X1 U294 (.A1(n368),
	.A2(n334),
	.B1(n369),
	.B2(n368),
	.C1(n369),
	.C2(n334),
	.ZN(n367));
   AOI21_X1 U295 (.A(n370),
	.B1(a[3]),
	.B2(n338),
	.ZN(n369));
   NOR3_X1 U296 (.A1(FE_OFN4_n371),
	.A2(b[0]),
	.A3(n342),
	.ZN(n370));
   MUX2_X1 U297 (.A(n372),
	.B(n373),
	.S(b[0]),
	.Z(n368));
   NAND2_X1 U298 (.A1(n337),
	.A2(n374),
	.ZN(n373));
   NAND2_X1 U299 (.A1(n375),
	.A2(n374),
	.ZN(n372));
   OAI22_X1 U300 (.A1(n339),
	.A2(n376),
	.B1(n377),
	.B2(n335),
	.ZN(n374));
   NOR2_X1 U301 (.A1(n340),
	.A2(b[1]),
	.ZN(n375));
   XOR2_X1 U302 (.A(n378),
	.B(n379),
	.Z(n57));
   NAND2_X1 U303 (.A1(n348),
	.A2(n379),
	.ZN(n56));
   AOI22_X1 U304 (.A1(n341),
	.A2(n338),
	.B1(n337),
	.B2(n380),
	.ZN(n379));
   OAI22_X1 U305 (.A1(n382),
	.A2(n383),
	.B1(n384),
	.B2(n385),
	.ZN(n378));
   AOI22_X1 U306 (.A1(n380),
	.A2(n338),
	.B1(n337),
	.B2(n386),
	.ZN(n49));
   XOR2_X1 U307 (.A(b[9]),
	.B(a[3]),
	.Z(n380));
   OAI22_X1 U308 (.A1(n387),
	.A2(n388),
	.B1(n389),
	.B2(n390),
	.ZN(n34));
   OAI22_X1 U309 (.A1(n391),
	.A2(n383),
	.B1(n384),
	.B2(n392),
	.ZN(n24));
   OAI22_X1 U310 (.A1(n377),
	.A2(n376),
	.B1(n393),
	.B2(n335),
	.ZN(n169));
   XOR2_X1 U311 (.A(b[2]),
	.B(n340),
	.Z(n377));
   OAI22_X1 U312 (.A1(n393),
	.A2(n376),
	.B1(n394),
	.B2(n335),
	.ZN(n168));
   XOR2_X1 U313 (.A(b[3]),
	.B(n340),
	.Z(n393));
   OAI22_X1 U314 (.A1(n394),
	.A2(n376),
	.B1(n395),
	.B2(n335),
	.ZN(n167));
   XOR2_X1 U315 (.A(b[4]),
	.B(n340),
	.Z(n394));
   OAI22_X1 U316 (.A1(n395),
	.A2(n376),
	.B1(n396),
	.B2(n335),
	.ZN(n166));
   XOR2_X1 U317 (.A(b[5]),
	.B(n340),
	.Z(n395));
   OAI22_X1 U318 (.A1(n396),
	.A2(n376),
	.B1(n397),
	.B2(n335),
	.ZN(n165));
   XOR2_X1 U319 (.A(b[6]),
	.B(n340),
	.Z(n396));
   OAI22_X1 U320 (.A1(n397),
	.A2(n376),
	.B1(n398),
	.B2(n335),
	.ZN(n164));
   XOR2_X1 U321 (.A(b[7]),
	.B(n340),
	.Z(n397));
   OAI22_X1 U322 (.A1(n398),
	.A2(n376),
	.B1(n399),
	.B2(n335),
	.ZN(n163));
   XOR2_X1 U323 (.A(b[8]),
	.B(n340),
	.Z(n398));
   OAI22_X1 U324 (.A1(n399),
	.A2(n376),
	.B1(n400),
	.B2(n335),
	.ZN(n162));
   XOR2_X1 U325 (.A(b[9]),
	.B(n340),
	.Z(n399));
   XNOR2_X1 U327 (.A(b[10]),
	.B(a[1]),
	.ZN(n400));
   OAI22_X1 U328 (.A1(n402),
	.A2(n403),
	.B1(FE_OFN4_n371),
	.B2(n404),
	.ZN(n159));
   XOR2_X1 U329 (.A(n351),
	.B(a[3]),
	.Z(n402));
   OAI22_X1 U330 (.A1(n404),
	.A2(n403),
	.B1(FE_OFN4_n371),
	.B2(n405),
	.ZN(n158));
   XOR2_X1 U331 (.A(b[1]),
	.B(n342),
	.Z(n404));
   OAI22_X1 U332 (.A1(n405),
	.A2(n403),
	.B1(FE_OFN4_n371),
	.B2(n406),
	.ZN(n157));
   XOR2_X1 U333 (.A(b[2]),
	.B(n342),
	.Z(n405));
   OAI22_X1 U334 (.A1(n406),
	.A2(n403),
	.B1(FE_OFN4_n371),
	.B2(n407),
	.ZN(n156));
   XOR2_X1 U335 (.A(b[3]),
	.B(n342),
	.Z(n406));
   OAI22_X1 U336 (.A1(n407),
	.A2(n403),
	.B1(FE_OFN4_n371),
	.B2(n408),
	.ZN(n155));
   XOR2_X1 U337 (.A(b[4]),
	.B(n342),
	.Z(n407));
   OAI22_X1 U338 (.A1(n408),
	.A2(n403),
	.B1(FE_OFN4_n371),
	.B2(n409),
	.ZN(n154));
   XOR2_X1 U339 (.A(b[5]),
	.B(n342),
	.Z(n408));
   OAI22_X1 U340 (.A1(n409),
	.A2(n403),
	.B1(FE_OFN4_n371),
	.B2(n410),
	.ZN(n153));
   XOR2_X1 U341 (.A(b[6]),
	.B(n342),
	.Z(n409));
   OAI22_X1 U342 (.A1(n410),
	.A2(n403),
	.B1(FE_OFN4_n371),
	.B2(n381),
	.ZN(n152));
   XOR2_X1 U343 (.A(b[8]),
	.B(n342),
	.Z(n381));
   XOR2_X1 U344 (.A(b[7]),
	.B(n342),
	.Z(n410));
   XOR2_X1 U346 (.A(a[3]),
	.B(a[2]),
	.Z(n411));
   XOR2_X1 U347 (.A(b[10]),
	.B(a[3]),
	.Z(n386));
   NOR2_X1 U348 (.A1(n389),
	.A2(n351),
	.ZN(n149));
   OAI22_X1 U349 (.A1(n412),
	.A2(n388),
	.B1(n389),
	.B2(n413),
	.ZN(n148));
   XOR2_X1 U350 (.A(n351),
	.B(a[5]),
	.Z(n412));
   OAI22_X1 U351 (.A1(n413),
	.A2(n388),
	.B1(n389),
	.B2(n414),
	.ZN(n147));
   XOR2_X1 U352 (.A(b[1]),
	.B(n345),
	.Z(n413));
   OAI22_X1 U353 (.A1(n414),
	.A2(n388),
	.B1(n389),
	.B2(n415),
	.ZN(n146));
   XOR2_X1 U354 (.A(b[2]),
	.B(n345),
	.Z(n414));
   OAI22_X1 U355 (.A1(n415),
	.A2(n388),
	.B1(n389),
	.B2(n416),
	.ZN(n145));
   XOR2_X1 U356 (.A(b[3]),
	.B(n345),
	.Z(n415));
   OAI22_X1 U357 (.A1(n416),
	.A2(n388),
	.B1(n389),
	.B2(n417),
	.ZN(n144));
   XOR2_X1 U358 (.A(b[4]),
	.B(n345),
	.Z(n416));
   OAI22_X1 U359 (.A1(n417),
	.A2(n388),
	.B1(n389),
	.B2(n418),
	.ZN(n143));
   XOR2_X1 U360 (.A(b[5]),
	.B(n345),
	.Z(n417));
   OAI22_X1 U361 (.A1(n418),
	.A2(n388),
	.B1(n389),
	.B2(n419),
	.ZN(n142));
   XOR2_X1 U362 (.A(b[6]),
	.B(n345),
	.Z(n418));
   OAI22_X1 U363 (.A1(n419),
	.A2(n388),
	.B1(n389),
	.B2(n420),
	.ZN(n141));
   XOR2_X1 U364 (.A(b[7]),
	.B(n345),
	.Z(n419));
   OAI22_X1 U365 (.A1(n420),
	.A2(n388),
	.B1(n389),
	.B2(n387),
	.ZN(n140));
   XOR2_X1 U366 (.A(b[9]),
	.B(n345),
	.Z(n387));
   XOR2_X1 U367 (.A(b[8]),
	.B(n345),
	.Z(n420));
   XOR2_X1 U369 (.A(b[10]),
	.B(n345),
	.Z(n390));
   NOR2_X1 U370 (.A1(n384),
	.A2(n351),
	.ZN(n138));
   OAI22_X1 U371 (.A1(n422),
	.A2(n383),
	.B1(n384),
	.B2(n423),
	.ZN(n137));
   XOR2_X1 U372 (.A(n351),
	.B(a[7]),
	.Z(n422));
   OAI22_X1 U373 (.A1(n423),
	.A2(n383),
	.B1(n384),
	.B2(n424),
	.ZN(n136));
   XOR2_X1 U374 (.A(b[1]),
	.B(n349),
	.Z(n423));
   OAI22_X1 U375 (.A1(n424),
	.A2(n383),
	.B1(n384),
	.B2(n425),
	.ZN(n135));
   XOR2_X1 U376 (.A(b[2]),
	.B(n349),
	.Z(n424));
   OAI22_X1 U377 (.A1(n425),
	.A2(n383),
	.B1(n384),
	.B2(n382),
	.ZN(n134));
   XOR2_X1 U378 (.A(b[4]),
	.B(n349),
	.Z(n382));
   XOR2_X1 U379 (.A(b[3]),
	.B(n349),
	.Z(n425));
   OAI22_X1 U380 (.A1(n385),
	.A2(n383),
	.B1(n384),
	.B2(n426),
	.ZN(n132));
   XOR2_X1 U381 (.A(b[5]),
	.B(n349),
	.Z(n385));
   OAI22_X1 U382 (.A1(n426),
	.A2(n383),
	.B1(n384),
	.B2(n427),
	.ZN(n131));
   XOR2_X1 U383 (.A(b[6]),
	.B(n349),
	.Z(n426));
   OAI22_X1 U384 (.A1(n427),
	.A2(n383),
	.B1(n384),
	.B2(n428),
	.ZN(n130));
   XOR2_X1 U385 (.A(b[7]),
	.B(n349),
	.Z(n427));
   OAI22_X1 U386 (.A1(n428),
	.A2(n383),
	.B1(n384),
	.B2(n391),
	.ZN(n129));
   XOR2_X1 U387 (.A(b[9]),
	.B(n349),
	.Z(n391));
   XOR2_X1 U388 (.A(b[8]),
	.B(n349),
	.Z(n428));
   OAI22_X1 U389 (.A1(n392),
	.A2(n384),
	.B1(n383),
	.B2(n392),
	.ZN(n429));
   XOR2_X1 U390 (.A(b[10]),
	.B(n349),
	.Z(n392));
   NOR2_X1 U391 (.A1(n355),
	.A2(n351),
	.ZN(n127));
   OAI22_X1 U392 (.A1(n430),
	.A2(n356),
	.B1(n355),
	.B2(n431),
	.ZN(n126));
   XOR2_X1 U393 (.A(n351),
	.B(a[9]),
	.Z(n430));
   OAI22_X1 U394 (.A1(n431),
	.A2(n356),
	.B1(n355),
	.B2(n432),
	.ZN(n125));
   XOR2_X1 U395 (.A(b[1]),
	.B(n350),
	.Z(n431));
   OAI22_X1 U396 (.A1(n432),
	.A2(n356),
	.B1(n355),
	.B2(n433),
	.ZN(n124));
   XOR2_X1 U397 (.A(b[2]),
	.B(n350),
	.Z(n432));
   OAI22_X1 U398 (.A1(n433),
	.A2(n356),
	.B1(n355),
	.B2(n434),
	.ZN(n123));
   XOR2_X1 U399 (.A(b[3]),
	.B(n350),
	.Z(n433));
   OAI22_X1 U400 (.A1(n434),
	.A2(n356),
	.B1(n355),
	.B2(n435),
	.ZN(n122));
   XOR2_X1 U401 (.A(b[4]),
	.B(n350),
	.Z(n434));
   OAI22_X1 U402 (.A1(n435),
	.A2(n356),
	.B1(n355),
	.B2(n436),
	.ZN(n121));
   XOR2_X1 U403 (.A(b[5]),
	.B(n350),
	.Z(n435));
   OAI22_X1 U404 (.A1(n436),
	.A2(n356),
	.B1(n355),
	.B2(n437),
	.ZN(n120));
   XOR2_X1 U405 (.A(b[6]),
	.B(n350),
	.Z(n436));
   OAI22_X1 U406 (.A1(n437),
	.A2(n356),
	.B1(n355),
	.B2(n438),
	.ZN(n119));
   XOR2_X1 U407 (.A(b[7]),
	.B(n350),
	.Z(n437));
   OAI22_X1 U408 (.A1(n438),
	.A2(n356),
	.B1(n355),
	.B2(n357),
	.ZN(n118));
   XNOR2_X1 U409 (.A(b[9]),
	.B(a[9]),
	.ZN(n357));
   XOR2_X1 U410 (.A(b[8]),
	.B(n350),
	.Z(n438));
   OAI21_X1 U411 (.A(n439),
	.B1(n345),
	.B2(n388),
	.ZN(n114));
   OR3_X1 U412 (.A1(n389),
	.A2(b[0]),
	.A3(n345),
	.ZN(n439));
   NAND2_X1 U413 (.A1(n389),
	.A2(n440),
	.ZN(n388));
   XOR2_X1 U414 (.A(a[5]),
	.B(a[4]),
	.Z(n440));
   OAI21_X1 U415 (.A(n441),
	.B1(n349),
	.B2(n383),
	.ZN(n113));
   OR3_X1 U416 (.A1(n384),
	.A2(b[0]),
	.A3(n349),
	.ZN(n441));
   NAND2_X1 U417 (.A1(n384),
	.A2(n442),
	.ZN(n383));
   XOR2_X1 U418 (.A(a[7]),
	.B(a[6]),
	.Z(n442));
   OAI21_X1 U419 (.A(n443),
	.B1(n350),
	.B2(n356),
	.ZN(n112));
   OR3_X1 U420 (.A1(n355),
	.A2(b[0]),
	.A3(n350),
	.ZN(n443));
   NAND2_X1 U421 (.A1(n355),
	.A2(n444),
	.ZN(n356));
   XOR2_X1 U422 (.A(a[9]),
	.B(a[8]),
	.Z(n444));
endmodule

module IIR (
	CLK, 
	RST_N, 
	VIN, 
	A1, 
	B0, 
	B1, 
	X, 
	Y, 
	VOUT);
   input CLK;
   input RST_N;
   input VIN;
   input [9:0] A1;
   input [9:0] B0;
   input [9:0] B1;
   input [9:0] X;
   output [9:0] Y;
   output VOUT;

   // Internal wires
   wire FE_DBTN0_n50;
   wire vin_d1;
   wire n1;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n26;
   wire n27;
   wire n30;
   wire n31;
   wire n32;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n39;
   wire n40;
   wire n43;
   wire n44;
   wire n46;
   wire n47;
   wire n48;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n68;
   wire n69;
   wire n71;
   wire n72;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire SYNOPSYS_UNCONNECTED_1;
   wire SYNOPSYS_UNCONNECTED_2;
   wire SYNOPSYS_UNCONNECTED_3;
   wire SYNOPSYS_UNCONNECTED_4;
   wire SYNOPSYS_UNCONNECTED_5;
   wire SYNOPSYS_UNCONNECTED_6;
   wire SYNOPSYS_UNCONNECTED_7;
   wire SYNOPSYS_UNCONNECTED_8;
   wire SYNOPSYS_UNCONNECTED_9;
   wire SYNOPSYS_UNCONNECTED_10;
   wire SYNOPSYS_UNCONNECTED_11;
   wire SYNOPSYS_UNCONNECTED_12;
   wire SYNOPSYS_UNCONNECTED_13;
   wire SYNOPSYS_UNCONNECTED_14;
   wire SYNOPSYS_UNCONNECTED_15;
   wire SYNOPSYS_UNCONNECTED_16;
   wire SYNOPSYS_UNCONNECTED_17;
   wire SYNOPSYS_UNCONNECTED_18;
   wire SYNOPSYS_UNCONNECTED_19;
   wire SYNOPSYS_UNCONNECTED_20;
   wire SYNOPSYS_UNCONNECTED_21;
   wire SYNOPSYS_UNCONNECTED_22;
   wire SYNOPSYS_UNCONNECTED_23;
   wire SYNOPSYS_UNCONNECTED_24;
   wire SYNOPSYS_UNCONNECTED_25;
   wire SYNOPSYS_UNCONNECTED_26;
   wire SYNOPSYS_UNCONNECTED_27;
   wire SYNOPSYS_UNCONNECTED_28;
   wire SYNOPSYS_UNCONNECTED_29;
   wire SYNOPSYS_UNCONNECTED_30;
   wire SYNOPSYS_UNCONNECTED_31;
   wire SYNOPSYS_UNCONNECTED_32;
   wire SYNOPSYS_UNCONNECTED_33;
   wire SYNOPSYS_UNCONNECTED_34;
   wire SYNOPSYS_UNCONNECTED_35;
   wire SYNOPSYS_UNCONNECTED_36;
   wire SYNOPSYS_UNCONNECTED_37;
   wire SYNOPSYS_UNCONNECTED_38;
   wire SYNOPSYS_UNCONNECTED_39;
   wire SYNOPSYS_UNCONNECTED_40;
   wire SYNOPSYS_UNCONNECTED_41;
   wire SYNOPSYS_UNCONNECTED_42;
   wire SYNOPSYS_UNCONNECTED_43;
   wire SYNOPSYS_UNCONNECTED_44;
   wire [9:4] a1_out;
   wire [9:0] b0_out;
   wire [9:0] b1_out;
   wire [9:0] x_d1;
   wire [10:0] sn;
   wire [10:0] sn_d1;
   wire [19:13] fb;
   wire [18:13] ff;
   wire [18:13] wb;
   wire [9:4] y_ext;
   wire [9:5] add_212_carry;

   assign Y[3] = 1'b0 ;
   assign Y[2] = 1'b0 ;
   assign Y[1] = 1'b0 ;
   assign Y[0] = 1'b0 ;

   INV_X1 FE_DBTC0_n50 (.A(n50),
	.ZN(FE_DBTN0_n50));
   DFFR_X1 VOUT_reg (.D(vin_d1),
	.RN(RST_N),
	.CK(CLK),
	.Q(VOUT));
   DFFR_X1 A1_IN_REG_data_out_reg_2_ (.D(A1[2]),
	.RN(RST_N),
	.CK(CLK),
	.QN(n30));
   DFFR_X1 A1_IN_REG_data_out_reg_4_ (.D(A1[4]),
	.RN(RST_N),
	.CK(CLK),
	.Q(a1_out[4]));
   DFFR_X1 A1_IN_REG_data_out_reg_5_ (.D(A1[5]),
	.RN(RST_N),
	.CK(CLK),
	.Q(n58));
   DFFR_X1 A1_IN_REG_data_out_reg_6_ (.D(A1[6]),
	.RN(RST_N),
	.CK(CLK),
	.Q(a1_out[6]));
   DFFR_X1 A1_IN_REG_data_out_reg_7_ (.D(A1[7]),
	.RN(RST_N),
	.CK(CLK),
	.Q(a1_out[7]));
   DFFR_X1 A1_IN_REG_data_out_reg_8_ (.D(A1[8]),
	.RN(RST_N),
	.CK(CLK),
	.Q(a1_out[8]));
   DFFR_X1 A1_IN_REG_data_out_reg_9_ (.D(A1[9]),
	.RN(RST_N),
	.CK(CLK),
	.Q(a1_out[9]));
   DFFR_X1 B0_IN_REG_data_out_reg_0_ (.D(B0[0]),
	.RN(RST_N),
	.CK(CLK),
	.Q(b0_out[0]));
   DFFR_X1 B0_IN_REG_data_out_reg_1_ (.D(B0[1]),
	.RN(RST_N),
	.CK(CLK),
	.Q(b0_out[1]));
   DFFR_X1 B0_IN_REG_data_out_reg_2_ (.D(B0[2]),
	.RN(RST_N),
	.CK(CLK),
	.Q(b0_out[2]));
   DFFR_X1 B0_IN_REG_data_out_reg_3_ (.D(B0[3]),
	.RN(RST_N),
	.CK(CLK),
	.Q(b0_out[3]));
   DFFR_X1 B0_IN_REG_data_out_reg_4_ (.D(B0[4]),
	.RN(RST_N),
	.CK(CLK),
	.Q(b0_out[4]));
   DFFR_X1 B0_IN_REG_data_out_reg_5_ (.D(B0[5]),
	.RN(RST_N),
	.CK(CLK),
	.Q(b0_out[5]));
   DFFR_X1 B0_IN_REG_data_out_reg_6_ (.D(B0[6]),
	.RN(RST_N),
	.CK(CLK),
	.Q(b0_out[6]));
   DFFR_X1 B0_IN_REG_data_out_reg_7_ (.D(B0[7]),
	.RN(RST_N),
	.CK(CLK),
	.Q(b0_out[7]));
   DFFR_X1 B0_IN_REG_data_out_reg_8_ (.D(B0[8]),
	.RN(RST_N),
	.CK(CLK),
	.Q(b0_out[8]));
   DFFR_X1 B0_IN_REG_data_out_reg_9_ (.D(B0[9]),
	.RN(RST_N),
	.CK(CLK),
	.Q(b0_out[9]));
   DFFR_X1 B1_IN_REG_data_out_reg_0_ (.D(B1[0]),
	.RN(RST_N),
	.CK(CLK),
	.Q(b1_out[0]));
   DFFR_X1 B1_IN_REG_data_out_reg_1_ (.D(B1[1]),
	.RN(RST_N),
	.CK(CLK),
	.Q(b1_out[1]));
   DFFR_X1 B1_IN_REG_data_out_reg_2_ (.D(B1[2]),
	.RN(RST_N),
	.CK(CLK),
	.Q(b1_out[2]));
   DFFR_X1 B1_IN_REG_data_out_reg_3_ (.D(B1[3]),
	.RN(RST_N),
	.CK(CLK),
	.Q(b1_out[3]));
   DFFR_X1 B1_IN_REG_data_out_reg_4_ (.D(B1[4]),
	.RN(RST_N),
	.CK(CLK),
	.Q(b1_out[4]));
   DFFR_X1 B1_IN_REG_data_out_reg_5_ (.D(B1[5]),
	.RN(RST_N),
	.CK(CLK),
	.Q(b1_out[5]));
   DFFR_X1 B1_IN_REG_data_out_reg_6_ (.D(B1[6]),
	.RN(RST_N),
	.CK(CLK),
	.Q(b1_out[6]));
   DFFR_X1 B1_IN_REG_data_out_reg_7_ (.D(B1[7]),
	.RN(RST_N),
	.CK(CLK),
	.Q(b1_out[7]));
   DFFR_X1 B1_IN_REG_data_out_reg_8_ (.D(B1[8]),
	.RN(RST_N),
	.CK(CLK),
	.Q(b1_out[8]));
   DFFR_X1 B1_IN_REG_data_out_reg_9_ (.D(B1[9]),
	.RN(RST_N),
	.CK(CLK),
	.Q(b1_out[9]));
   DFFR_X1 IN_REG_data_out_reg_0_ (.D(X[0]),
	.RN(RST_N),
	.CK(CLK),
	.Q(x_d1[0]));
   DFFR_X1 IN_REG_data_out_reg_1_ (.D(X[1]),
	.RN(RST_N),
	.CK(CLK),
	.Q(x_d1[1]));
   DFFR_X1 IN_REG_data_out_reg_2_ (.D(X[2]),
	.RN(RST_N),
	.CK(CLK),
	.Q(x_d1[2]));
   DFFR_X1 IN_REG_data_out_reg_3_ (.D(X[3]),
	.RN(RST_N),
	.CK(CLK),
	.Q(x_d1[3]));
   DFFR_X1 IN_REG_data_out_reg_4_ (.D(X[4]),
	.RN(RST_N),
	.CK(CLK),
	.Q(x_d1[4]));
   DFFR_X1 IN_REG_data_out_reg_6_ (.D(X[6]),
	.RN(RST_N),
	.CK(CLK),
	.Q(x_d1[6]));
   DFFR_X1 IN_REG_data_out_reg_7_ (.D(X[7]),
	.RN(RST_N),
	.CK(CLK),
	.Q(x_d1[7]));
   DFFR_X1 IN_REG_data_out_reg_8_ (.D(X[8]),
	.RN(RST_N),
	.CK(CLK),
	.Q(x_d1[8]));
   DFFR_X1 IN_REG_data_out_reg_9_ (.D(X[9]),
	.RN(RST_N),
	.CK(CLK),
	.Q(x_d1[9]));
   DFFR_X1 OUT_REG_data_out_reg_4_ (.D(y_ext[4]),
	.RN(RST_N),
	.CK(CLK),
	.Q(Y[4]));
   DFFR_X1 OUT_REG_data_out_reg_5_ (.D(y_ext[5]),
	.RN(RST_N),
	.CK(CLK),
	.Q(Y[5]));
   DFFR_X1 OUT_REG_data_out_reg_6_ (.D(y_ext[6]),
	.RN(RST_N),
	.CK(CLK),
	.Q(Y[6]));
   DFFR_X1 OUT_REG_data_out_reg_7_ (.D(y_ext[7]),
	.RN(RST_N),
	.CK(CLK),
	.Q(Y[7]));
   DFFR_X1 OUT_REG_data_out_reg_8_ (.D(y_ext[8]),
	.RN(RST_N),
	.CK(CLK),
	.Q(Y[8]));
   DFFR_X1 OUT_REG_data_out_reg_9_ (.D(y_ext[9]),
	.RN(RST_N),
	.CK(CLK),
	.Q(Y[9]));
   DFFR_X1 U_SN_REG_data_out_reg_5_ (.D(n89),
	.RN(RST_N),
	.CK(CLK),
	.Q(sn_d1[5]));
   DFFR_X1 U_SN_REG_data_out_reg_6_ (.D(n88),
	.RN(RST_N),
	.CK(CLK),
	.Q(sn_d1[6]));
   DFFR_X1 U_SN_REG_data_out_reg_7_ (.D(n87),
	.RN(RST_N),
	.CK(CLK),
	.Q(sn_d1[7]));
   DFFR_X1 U_SN_REG_data_out_reg_8_ (.D(n86),
	.RN(RST_N),
	.CK(CLK),
	.Q(sn_d1[8]));
   DFFR_X1 U_SN_REG_data_out_reg_9_ (.D(n85),
	.RN(RST_N),
	.CK(CLK),
	.Q(sn_d1[9]));
   DFFR_X1 U_SN_REG_data_out_reg_10_ (.D(n84),
	.RN(RST_N),
	.CK(CLK),
	.Q(sn_d1[10]));
   IIR_DW01_add_1 add_198 (.A({ x_d1[9],
		x_d1 }),
	.B({ fb,
		1'b0,
		1'b0,
		1'b0,
		1'b0 }),
	.CI(1'b0),
	.SUM(sn));
   IIR_DW_mult_tc_2 mult_208 (.a(b0_out),
	.b(sn),
	.product({ SYNOPSYS_UNCONNECTED_1,
		SYNOPSYS_UNCONNECTED_2,
		wb,
		SYNOPSYS_UNCONNECTED_3,
		SYNOPSYS_UNCONNECTED_4,
		SYNOPSYS_UNCONNECTED_5,
		SYNOPSYS_UNCONNECTED_6,
		SYNOPSYS_UNCONNECTED_7,
		SYNOPSYS_UNCONNECTED_8,
		SYNOPSYS_UNCONNECTED_9,
		SYNOPSYS_UNCONNECTED_10,
		SYNOPSYS_UNCONNECTED_11,
		SYNOPSYS_UNCONNECTED_12,
		SYNOPSYS_UNCONNECTED_13,
		SYNOPSYS_UNCONNECTED_14,
		SYNOPSYS_UNCONNECTED_15 }));
   IIR_DW_mult_tc_1 mult_193 (.a({ a1_out[9],
		a1_out[8],
		a1_out[7],
		a1_out[6],
		n58,
		a1_out[4],
		n69,
		n31,
		n72,
		FE_DBTN0_n50 }),
	.b({ sn_d1[10],
		sn_d1[9],
		sn_d1[8],
		sn_d1[7],
		sn_d1[6],
		sn_d1[5],
		sn_d1[4],
		n44,
		sn_d1[2],
		n40,
		n56 }),
	.product({ SYNOPSYS_UNCONNECTED_16,
		fb,
		SYNOPSYS_UNCONNECTED_17,
		SYNOPSYS_UNCONNECTED_18,
		SYNOPSYS_UNCONNECTED_19,
		SYNOPSYS_UNCONNECTED_20,
		SYNOPSYS_UNCONNECTED_21,
		SYNOPSYS_UNCONNECTED_22,
		SYNOPSYS_UNCONNECTED_23,
		SYNOPSYS_UNCONNECTED_24,
		SYNOPSYS_UNCONNECTED_25,
		SYNOPSYS_UNCONNECTED_26,
		SYNOPSYS_UNCONNECTED_27,
		SYNOPSYS_UNCONNECTED_28,
		SYNOPSYS_UNCONNECTED_29 }),
	.p_1(n68),
	.p_2(n55),
	.p_3(n39));
   IIR_DW_mult_tc_0 mult_204 (.a(b1_out),
	.b({ sn_d1[10],
		sn_d1[9],
		sn_d1[8],
		sn_d1[7],
		sn_d1[6],
		sn_d1[5],
		sn_d1[4],
		sn_d1[3],
		n47,
		sn_d1[1],
		sn_d1[0] }),
	.product({ SYNOPSYS_UNCONNECTED_30,
		SYNOPSYS_UNCONNECTED_31,
		ff,
		SYNOPSYS_UNCONNECTED_32,
		SYNOPSYS_UNCONNECTED_33,
		SYNOPSYS_UNCONNECTED_34,
		SYNOPSYS_UNCONNECTED_35,
		SYNOPSYS_UNCONNECTED_36,
		SYNOPSYS_UNCONNECTED_37,
		SYNOPSYS_UNCONNECTED_38,
		SYNOPSYS_UNCONNECTED_39,
		SYNOPSYS_UNCONNECTED_40,
		SYNOPSYS_UNCONNECTED_41,
		SYNOPSYS_UNCONNECTED_42,
		SYNOPSYS_UNCONNECTED_43,
		SYNOPSYS_UNCONNECTED_44 }));
   DFFR_X1 A1_IN_REG_data_out_reg_1_ (.D(A1[1]),
	.RN(RST_N),
	.CK(CLK),
	.QN(n71));
   DFFR_X1 vin_d1_reg (.D(VIN),
	.RN(RST_N),
	.CK(CLK),
	.Q(vin_d1),
	.QN(n26));
   DFFR_X1 A1_IN_REG_data_out_reg_3_ (.D(A1[3]),
	.RN(RST_N),
	.CK(CLK),
	.QN(n68));
   DFFR_X1 U_SN_REG_data_out_reg_0_ (.D(n91),
	.RN(RST_N),
	.CK(CLK),
	.Q(sn_d1[0]),
	.QN(n55));
   DFFR_X1 U_SN_REG_data_out_reg_2_ (.D(n82),
	.RN(RST_N),
	.CK(CLK),
	.Q(sn_d1[2]),
	.QN(n46));
   DFFR_X1 U_SN_REG_data_out_reg_3_ (.D(n81),
	.RN(RST_N),
	.CK(CLK),
	.Q(sn_d1[3]),
	.QN(n43));
   DFFR_X1 U_SN_REG_data_out_reg_1_ (.D(n83),
	.RN(RST_N),
	.CK(CLK),
	.Q(sn_d1[1]),
	.QN(n39));
   DFFR_X1 U_SN_REG_data_out_reg_4_ (.D(n90),
	.RN(RST_N),
	.CK(CLK),
	.Q(sn_d1[4]));
   DFFR_X1 A1_IN_REG_data_out_reg_0_ (.D(A1[0]),
	.RN(RST_N),
	.CK(CLK),
	.Q(n50));
   DFFR_X1 IN_REG_data_out_reg_5_ (.D(X[5]),
	.RN(RST_N),
	.CK(CLK),
	.Q(x_d1[5]));
   XNOR2_X1 U28 (.A(n27),
	.B(add_212_carry[8]),
	.ZN(y_ext[8]));
   XNOR2_X1 U29 (.A(wb[17]),
	.B(ff[17]),
	.ZN(n27));
   INV_X1 U32 (.A(n30),
	.ZN(n31));
   XNOR2_X1 U33 (.A(add_212_carry[9]),
	.B(ff[18]),
	.ZN(n32));
   XNOR2_X1 U34 (.A(n32),
	.B(wb[18]),
	.ZN(y_ext[9]));
   XOR2_X1 U36 (.A(add_212_carry[5]),
	.B(ff[14]),
	.Z(n34));
   XOR2_X1 U37 (.A(wb[14]),
	.B(n34),
	.Z(y_ext[5]));
   NAND2_X1 U38 (.A1(wb[14]),
	.A2(add_212_carry[5]),
	.ZN(n35));
   NAND2_X1 U39 (.A1(wb[14]),
	.A2(ff[14]),
	.ZN(n36));
   NAND2_X1 U40 (.A1(add_212_carry[5]),
	.A2(ff[14]),
	.ZN(n37));
   NAND3_X1 U41 (.A1(n35),
	.A2(n36),
	.A3(n37),
	.ZN(add_212_carry[6]));
   INV_X1 U43 (.A(n68),
	.ZN(n69));
   INV_X1 U44 (.A(n39),
	.ZN(n40));
   INV_X1 U47 (.A(n43),
	.ZN(n44));
   INV_X1 U49 (.A(n46),
	.ZN(n47));
   NAND3_X1 U50 (.A1(n52),
	.A2(n53),
	.A3(n54),
	.ZN(n48));
   XOR2_X1 U52 (.A(add_212_carry[6]),
	.B(ff[15]),
	.Z(n51));
   XOR2_X1 U53 (.A(wb[15]),
	.B(n51),
	.Z(y_ext[6]));
   NAND2_X1 U54 (.A1(wb[15]),
	.A2(add_212_carry[6]),
	.ZN(n52));
   NAND2_X1 U55 (.A1(wb[15]),
	.A2(ff[15]),
	.ZN(n53));
   NAND2_X1 U56 (.A1(add_212_carry[6]),
	.A2(ff[15]),
	.ZN(n54));
   NAND3_X1 U57 (.A1(n52),
	.A2(n54),
	.A3(n53),
	.ZN(add_212_carry[7]));
   INV_X1 U58 (.A(n55),
	.ZN(n56));
   INV_X1 U60 (.A(n71),
	.ZN(n72));
   XOR2_X1 U61 (.A(wb[16]),
	.B(ff[16]),
	.Z(n59));
   XOR2_X1 U62 (.A(n48),
	.B(n59),
	.Z(y_ext[7]));
   NAND2_X1 U63 (.A1(add_212_carry[7]),
	.A2(wb[16]),
	.ZN(n60));
   NAND2_X1 U64 (.A1(n48),
	.A2(ff[16]),
	.ZN(n61));
   NAND2_X1 U65 (.A1(wb[16]),
	.A2(ff[16]),
	.ZN(n62));
   NAND3_X1 U66 (.A1(n61),
	.A2(n60),
	.A3(n62),
	.ZN(add_212_carry[8]));
   NAND2_X1 U67 (.A1(add_212_carry[8]),
	.A2(wb[17]),
	.ZN(n63));
   NAND2_X1 U68 (.A1(add_212_carry[8]),
	.A2(ff[17]),
	.ZN(n64));
   NAND2_X1 U69 (.A1(wb[17]),
	.A2(ff[17]),
	.ZN(n65));
   NAND3_X1 U70 (.A1(n63),
	.A2(n65),
	.A3(n64),
	.ZN(add_212_carry[9]));
   INV_X1 U82 (.A(n1),
	.ZN(n84));
   AOI22_X1 U83 (.A1(vin_d1),
	.A2(sn[10]),
	.B1(sn_d1[10]),
	.B2(n26),
	.ZN(n1));
   INV_X1 U84 (.A(n3),
	.ZN(n85));
   AOI22_X1 U85 (.A1(sn[9]),
	.A2(vin_d1),
	.B1(sn_d1[9]),
	.B2(n26),
	.ZN(n3));
   INV_X1 U86 (.A(n4),
	.ZN(n86));
   AOI22_X1 U87 (.A1(sn[8]),
	.A2(vin_d1),
	.B1(sn_d1[8]),
	.B2(n26),
	.ZN(n4));
   INV_X1 U88 (.A(n5),
	.ZN(n87));
   INV_X1 U89 (.A(n6),
	.ZN(n88));
   INV_X1 U90 (.A(n7),
	.ZN(n89));
   AOI22_X1 U91 (.A1(sn[5]),
	.A2(vin_d1),
	.B1(sn_d1[5]),
	.B2(n26),
	.ZN(n7));
   INV_X1 U92 (.A(n8),
	.ZN(n90));
   AOI22_X1 U93 (.A1(sn[4]),
	.A2(vin_d1),
	.B1(sn_d1[4]),
	.B2(n26),
	.ZN(n8));
   INV_X1 U94 (.A(n9),
	.ZN(n81));
   AOI22_X1 U95 (.A1(sn[3]),
	.A2(vin_d1),
	.B1(sn_d1[3]),
	.B2(n26),
	.ZN(n9));
   INV_X1 U96 (.A(n10),
	.ZN(n82));
   AOI22_X1 U97 (.A1(sn[2]),
	.A2(vin_d1),
	.B1(n47),
	.B2(n26),
	.ZN(n10));
   INV_X1 U98 (.A(n12),
	.ZN(n91));
   AOI22_X1 U99 (.A1(sn[0]),
	.A2(vin_d1),
	.B1(sn_d1[0]),
	.B2(n26),
	.ZN(n12));
   INV_X1 U100 (.A(n11),
	.ZN(n83));
   AOI22_X1 U101 (.A1(sn[1]),
	.A2(vin_d1),
	.B1(sn_d1[1]),
	.B2(n26),
	.ZN(n11));
   AOI22_X1 U106 (.A1(sn[7]),
	.A2(vin_d1),
	.B1(sn_d1[7]),
	.B2(n26),
	.ZN(n5));
   AOI22_X1 U107 (.A1(sn[6]),
	.A2(vin_d1),
	.B1(sn_d1[6]),
	.B2(n26),
	.ZN(n6));
   AND2_X1 U108 (.A1(ff[13]),
	.A2(wb[13]),
	.ZN(add_212_carry[5]));
   XOR2_X1 U109 (.A(ff[13]),
	.B(wb[13]),
	.Z(y_ext[4]));
endmodule

