/*
###############################################################
#  Generated by:      Cadence Innovus 20.11-s130_1
#  OS:                Linux x86_64(Host ID isaserver)
#  Generated on:      Tue Nov 21 18:23:01 2023
#  Design:            iir
#  Command:           saveNetlist IIR.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : S-2021.06-SP4
// Date      : Tue Nov 21 18:11:19 2023
/////////////////////////////////////////////////////////////
module iir_DW01_add_1 (
	A, 
	B, 
	CI, 
	SUM, 
	CO);
   input [10:0] A;
   input [10:0] B;
   input CI;
   output [10:0] SUM;
   output CO;

   // Internal wires
   wire n2;
   wire [10:5] carry;

   FA_X1 U1_10 (.A(A[10]),
	.B(B[10]),
	.CI(carry[10]),
	.S(SUM[10]));
   FA_X1 U1_9 (.A(A[9]),
	.B(B[9]),
	.CI(carry[9]),
	.CO(carry[10]),
	.S(SUM[9]));
   FA_X1 U1_8 (.A(A[8]),
	.B(B[8]),
	.CI(carry[8]),
	.CO(carry[9]),
	.S(SUM[8]));
   FA_X1 U1_7 (.A(A[7]),
	.B(B[7]),
	.CI(carry[7]),
	.CO(carry[8]),
	.S(SUM[7]));
   FA_X1 U1_6 (.A(A[6]),
	.B(B[6]),
	.CI(carry[6]),
	.CO(carry[7]),
	.S(SUM[6]));
   FA_X1 U1_5 (.A(A[5]),
	.B(B[5]),
	.CI(carry[5]),
	.CO(carry[6]),
	.S(SUM[5]));
   FA_X1 U1_4 (.A(A[4]),
	.B(B[4]),
	.CI(n2),
	.CO(carry[5]),
	.S(SUM[4]));
   XOR2_X1 U1 (.A(B[3]),
	.B(A[3]),
	.Z(SUM[3]));
   AND2_X1 U2 (.A1(B[3]),
	.A2(A[3]),
	.ZN(n2));
endmodule

module iir_DW01_add_2 (
	A, 
	B, 
	CI, 
	SUM, 
	CO);
   input [10:0] A;
   input [10:0] B;
   input CI;
   output [10:0] SUM;
   output CO;

   // Internal wires
   wire n2;
   wire [10:5] carry;

   FA_X1 U1_10 (.A(A[10]),
	.B(B[10]),
	.CI(carry[10]),
	.S(SUM[10]));
   FA_X1 U1_9 (.A(A[9]),
	.B(B[9]),
	.CI(carry[9]),
	.CO(carry[10]),
	.S(SUM[9]));
   FA_X1 U1_8 (.A(A[8]),
	.B(B[8]),
	.CI(carry[8]),
	.CO(carry[9]),
	.S(SUM[8]));
   FA_X1 U1_7 (.A(A[7]),
	.B(B[7]),
	.CI(carry[7]),
	.CO(carry[8]),
	.S(SUM[7]));
   FA_X1 U1_6 (.A(A[6]),
	.B(B[6]),
	.CI(carry[6]),
	.CO(carry[7]),
	.S(SUM[6]));
   FA_X1 U1_5 (.A(A[5]),
	.B(B[5]),
	.CI(carry[5]),
	.CO(carry[6]),
	.S(SUM[5]));
   FA_X1 U1_4 (.A(A[4]),
	.B(B[4]),
	.CI(n2),
	.CO(carry[5]),
	.S(SUM[4]));
   XOR2_X1 U1 (.A(B[3]),
	.B(A[3]),
	.Z(SUM[3]));
   AND2_X1 U2 (.A1(B[3]),
	.A2(A[3]),
	.ZN(n2));
endmodule

module iir_DW_mult_tc_3 (
	a, 
	b, 
	product);
   input [10:0] a;
   input [10:0] b;
   output [21:0] product;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n19;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n106;
   wire n107;
   wire n108;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n337;
   wire n338;
   wire n339;
   wire n340;
   wire n341;
   wire n342;
   wire n343;
   wire n344;
   wire n345;
   wire n346;
   wire n347;
   wire n348;
   wire n349;
   wire n350;
   wire n351;
   wire n352;
   wire n353;
   wire n354;
   wire n355;
   wire n356;
   wire n357;
   wire n358;
   wire n359;
   wire n360;
   wire n361;
   wire n362;
   wire n363;
   wire n364;
   wire n365;
   wire n366;
   wire n367;
   wire n368;
   wire n369;
   wire n370;
   wire n371;
   wire n372;
   wire n373;
   wire n374;
   wire n375;
   wire n376;
   wire n377;
   wire n378;
   wire n379;
   wire n380;
   wire n381;
   wire n382;
   wire n383;
   wire n384;
   wire n385;
   wire n386;
   wire n387;
   wire n388;
   wire n389;
   wire n390;
   wire n391;
   wire n392;
   wire n393;
   wire n394;
   wire n395;
   wire n396;
   wire n397;
   wire n398;
   wire n399;
   wire n400;
   wire n401;
   wire n402;
   wire n403;
   wire n404;
   wire n405;
   wire n406;
   wire n407;
   wire n408;
   wire n409;
   wire n410;
   wire n411;
   wire n412;
   wire n413;
   wire n414;
   wire n415;
   wire n416;
   wire n417;
   wire n418;
   wire n419;
   wire n420;
   wire n421;
   wire n425;
   wire n426;
   wire n427;
   wire n428;
   wire n429;
   wire n430;
   wire n431;
   wire n432;
   wire n433;
   wire n434;
   wire n435;
   wire n436;
   wire n437;
   wire n438;
   wire n439;
   wire n440;
   wire n441;
   wire n442;
   wire n443;
   wire n444;
   wire n445;
   wire n446;
   wire n447;
   wire n448;
   wire n449;
   wire n450;
   wire n451;
   wire n452;
   wire n453;

   OAI21_X1 FE_RC_13_0 (.A(n363),
	.B1(n437),
	.B2(n438),
	.ZN(n141));
   AOI21_X1 FE_RC_3_0 (.A(n369),
	.B1(n361),
	.B2(n360),
	.ZN(n406));
   AOI21_X1 FE_RC_2_0 (.A(n367),
	.B1(n366),
	.B2(n365),
	.ZN(n399));
   AOI21_X1 FE_RC_1_0 (.A(n380),
	.B1(n435),
	.B2(n353),
	.ZN(n381));
   AOI21_X1 FE_RC_0_0 (.A(n373),
	.B1(n372),
	.B2(n371),
	.ZN(n415));
   FA_X1 U2 (.A(n451),
	.B(n19),
	.CI(n2),
	.CO(n1),
	.S(product[18]));
   FA_X1 U3 (.A(n21),
	.B(n450),
	.CI(n3),
	.CO(n2),
	.S(product[17]));
   FA_X1 U4 (.A(n23),
	.B(n22),
	.CI(n4),
	.CO(n3),
	.S(product[16]));
   FA_X1 U5 (.A(n24),
	.B(n27),
	.CI(n5),
	.CO(n4),
	.S(product[15]));
   FA_X1 U6 (.A(n28),
	.B(n31),
	.CI(n6),
	.CO(n5),
	.S(product[14]));
   FA_X1 U7 (.A(n32),
	.B(n37),
	.CI(n7),
	.CO(n6),
	.S(product[13]));
   FA_X1 U8 (.A(n38),
	.B(n43),
	.CI(n8),
	.CO(n7),
	.S(product[12]));
   FA_X1 U21 (.A(n112),
	.B(n25),
	.CI(n448),
	.CO(n21),
	.S(n22));
   FA_X1 U22 (.A(n447),
	.B(n113),
	.CI(n29),
	.CO(n23),
	.S(n24));
   FA_X1 U24 (.A(n33),
	.B(n114),
	.CI(n30),
	.CO(n27),
	.S(n28));
   FA_X1 U25 (.A(n122),
	.B(n35),
	.CI(n444),
	.CO(n29),
	.S(n30));
   FA_X1 U26 (.A(n34),
	.B(n41),
	.CI(n39),
	.CO(n31),
	.S(n32));
   FA_X1 U27 (.A(n115),
	.B(n123),
	.CI(n443),
	.CO(n33),
	.S(n34));
   FA_X1 U29 (.A(n45),
	.B(n42),
	.CI(n40),
	.CO(n37),
	.S(n38));
   FA_X1 U30 (.A(n436),
	.B(n132),
	.CI(n47),
	.CO(n39),
	.S(n40));
   FA_X1 U31 (.A(n124),
	.B(n116),
	.CI(n141),
	.CO(n41),
	.S(n42));
   FA_X1 U32 (.A(n53),
	.B(n48),
	.CI(n46),
	.CO(n43),
	.S(n44));
   FA_X1 U33 (.A(n57),
	.B(n50),
	.CI(n55),
	.CO(n45),
	.S(n46));
   FA_X1 U34 (.A(n125),
	.B(n117),
	.CI(n133),
	.CO(n47),
	.S(n48));
   FA_X1 U36 (.A(n61),
	.B(n56),
	.CI(n54),
	.CO(n51),
	.S(n52));
   FA_X1 U37 (.A(n58),
	.B(n65),
	.CI(n63),
	.CO(n53),
	.S(n54));
   FA_X1 U38 (.A(n134),
	.B(n118),
	.CI(n427),
	.CO(n55),
	.S(n56));
   FA_X1 U41 (.A(n64),
	.B(n69),
	.CI(n62),
	.CO(n59),
	.S(n60));
   FA_X1 U42 (.A(n66),
	.B(n152),
	.CI(n71),
	.CO(n61),
	.S(n62));
   FA_X1 U43 (.A(n127),
	.B(n135),
	.CI(n143),
	.CO(n63),
	.S(n64));
   HA_X1 U44 (.A(n106),
	.B(n119),
	.CO(n65),
	.S(n66));
   FA_X1 U45 (.A(n72),
	.B(n75),
	.CI(n70),
	.CO(n67),
	.S(n68));
   FA_X1 U46 (.A(n128),
	.B(n144),
	.CI(n77),
	.CO(n69),
	.S(n70));
   FA_X1 U47 (.A(n136),
	.B(n120),
	.CI(n153),
	.CO(n71),
	.S(n72));
   FA_X1 U48 (.A(n81),
	.B(n78),
	.CI(n76),
	.CO(n73),
	.S(n74));
   FA_X1 U49 (.A(n137),
	.B(n154),
	.CI(n145),
	.CO(n75),
	.S(n76));
   HA_X1 U50 (.A(n107),
	.B(n129),
	.CO(n77),
	.S(n78));
   FA_X1 U51 (.A(n85),
	.B(n138),
	.CI(n82),
	.CO(n79),
	.S(n80));
   FA_X1 U52 (.A(n155),
	.B(n130),
	.CI(n146),
	.CO(n81),
	.S(n82));
   FA_X1 U53 (.A(n147),
	.B(n156),
	.CI(n86),
	.CO(n83),
	.S(n84));
   HA_X1 U54 (.A(n108),
	.B(n139),
	.CO(n85),
	.S(n86));
   FA_X1 U55 (.A(n157),
	.B(n140),
	.CI(n148),
	.CO(n87),
	.S(n88));
   HA_X1 U56 (.A(n149),
	.B(n158),
	.CO(n89),
	.S(n90));
   XNOR2_X2 U266 (.A(a[4]),
	.B(a[3]),
	.ZN(n366));
   XNOR2_X2 U267 (.A(a[6]),
	.B(a[5]),
	.ZN(n361));
   XNOR2_X2 U268 (.A(a[8]),
	.B(a[7]),
	.ZN(n372));
   MUX2_X1 U280 (.A(n349),
	.B(n350),
	.S(b[0]),
	.Z(n345));
   XOR2_X1 U285 (.A(n355),
	.B(n356),
	.Z(n58));
   XOR2_X1 U290 (.A(b[8]),
	.B(a[3]),
	.Z(n357));
   XOR2_X1 U295 (.A(b[2]),
	.B(n440),
	.Z(n354));
   XOR2_X1 U297 (.A(b[3]),
	.B(n440),
	.Z(n374));
   XOR2_X1 U299 (.A(b[4]),
	.B(n440),
	.Z(n375));
   XOR2_X1 U301 (.A(b[5]),
	.B(n440),
	.Z(n376));
   XOR2_X1 U303 (.A(b[6]),
	.B(n440),
	.Z(n377));
   XOR2_X1 U305 (.A(b[7]),
	.B(n440),
	.Z(n378));
   XOR2_X1 U307 (.A(b[8]),
	.B(n440),
	.Z(n379));
   XOR2_X1 U311 (.A(n453),
	.B(a[3]),
	.Z(n382));
   XOR2_X1 U313 (.A(b[1]),
	.B(n442),
	.Z(n384));
   XOR2_X1 U315 (.A(b[2]),
	.B(n442),
	.Z(n385));
   XOR2_X1 U317 (.A(b[3]),
	.B(n442),
	.Z(n386));
   XOR2_X1 U319 (.A(b[4]),
	.B(n442),
	.Z(n387));
   XOR2_X1 U321 (.A(b[5]),
	.B(n442),
	.Z(n388));
   XOR2_X1 U323 (.A(b[7]),
	.B(n442),
	.Z(n358));
   XOR2_X1 U324 (.A(b[6]),
	.B(n442),
	.Z(n389));
   XOR2_X1 U327 (.A(a[3]),
	.B(a[2]),
	.Z(n390));
   XOR2_X1 U328 (.A(b[10]),
	.B(a[3]),
	.Z(n363));
   XOR2_X1 U331 (.A(n453),
	.B(a[5]),
	.Z(n391));
   XOR2_X1 U333 (.A(b[1]),
	.B(n445),
	.Z(n392));
   XOR2_X1 U335 (.A(b[2]),
	.B(n445),
	.Z(n393));
   XOR2_X1 U337 (.A(b[3]),
	.B(n445),
	.Z(n394));
   XOR2_X1 U339 (.A(b[4]),
	.B(n445),
	.Z(n395));
   XOR2_X1 U341 (.A(b[5]),
	.B(n445),
	.Z(n396));
   XOR2_X1 U343 (.A(b[6]),
	.B(n445),
	.Z(n397));
   XOR2_X1 U345 (.A(b[8]),
	.B(n445),
	.Z(n364));
   XOR2_X1 U346 (.A(b[7]),
	.B(n445),
	.Z(n398));
   XOR2_X1 U348 (.A(b[10]),
	.B(n445),
	.Z(n367));
   XOR2_X1 U351 (.A(n453),
	.B(a[7]),
	.Z(n400));
   XOR2_X1 U353 (.A(b[1]),
	.B(n449),
	.Z(n401));
   XOR2_X1 U355 (.A(b[3]),
	.B(n449),
	.Z(n359));
   XOR2_X1 U356 (.A(b[2]),
	.B(n449),
	.Z(n402));
   XOR2_X1 U358 (.A(b[4]),
	.B(n449),
	.Z(n362));
   XOR2_X1 U360 (.A(b[5]),
	.B(n449),
	.Z(n403));
   XOR2_X1 U362 (.A(b[6]),
	.B(n449),
	.Z(n404));
   XOR2_X1 U364 (.A(b[8]),
	.B(n449),
	.Z(n368));
   XOR2_X1 U365 (.A(b[7]),
	.B(n449),
	.Z(n405));
   XOR2_X1 U367 (.A(b[10]),
	.B(n449),
	.Z(n369));
   XOR2_X1 U370 (.A(n453),
	.B(a[10]),
	.Z(n407));
   XOR2_X1 U372 (.A(b[1]),
	.B(n452),
	.Z(n408));
   XOR2_X1 U374 (.A(b[2]),
	.B(n452),
	.Z(n409));
   XOR2_X1 U376 (.A(b[3]),
	.B(n452),
	.Z(n410));
   XOR2_X1 U378 (.A(b[4]),
	.B(n452),
	.Z(n411));
   XOR2_X1 U380 (.A(b[5]),
	.B(n452),
	.Z(n412));
   XOR2_X1 U382 (.A(b[6]),
	.B(n452),
	.Z(n413));
   XOR2_X1 U384 (.A(b[8]),
	.B(n452),
	.Z(n370));
   XOR2_X1 U385 (.A(b[7]),
	.B(n452),
	.Z(n414));
   XOR2_X1 U387 (.A(b[10]),
	.B(n452),
	.Z(n373));
   XOR2_X1 U391 (.A(a[5]),
	.B(a[4]),
	.Z(n417));
   XOR2_X1 U395 (.A(a[7]),
	.B(a[6]),
	.Z(n419));
   XOR2_X1 U399 (.A(a[10]),
	.B(a[8]),
	.Z(n421));
   XOR2_X1 U234 (.A(a[2]),
	.B(n440),
	.Z(n348));
   AOI222_X1 U235 (.A1(n338),
	.A2(n52),
	.B1(n338),
	.B2(n59),
	.C1(n59),
	.C2(n52),
	.ZN(n337));
   OAI222_X1 U236 (.A1(n339),
	.A2(n428),
	.B1(n339),
	.B2(n429),
	.C1(n429),
	.C2(n428),
	.ZN(n338));
   INV_X1 U237 (.A(n67),
	.ZN(n429));
   INV_X1 U238 (.A(n60),
	.ZN(n428));
   OAI222_X1 U239 (.A1(n337),
	.A2(n425),
	.B1(n337),
	.B2(n426),
	.C1(n426),
	.C2(n425),
	.ZN(n8));
   INV_X1 U240 (.A(n51),
	.ZN(n426));
   INV_X1 U241 (.A(n44),
	.ZN(n425));
   AOI222_X1 U242 (.A1(n340),
	.A2(n68),
	.B1(n340),
	.B2(n73),
	.C1(n73),
	.C2(n68),
	.ZN(n339));
   OAI222_X1 U243 (.A1(n341),
	.A2(n430),
	.B1(n341),
	.B2(n431),
	.C1(n431),
	.C2(n430),
	.ZN(n340));
   INV_X1 U244 (.A(n79),
	.ZN(n431));
   INV_X1 U245 (.A(n74),
	.ZN(n430));
   INV_X1 U246 (.A(n19),
	.ZN(n450));
   INV_X1 U247 (.A(n1),
	.ZN(product[19]));
   NAND2_X1 U248 (.A1(n437),
	.A2(n351),
	.ZN(n350));
   NAND2_X1 U249 (.A1(n446),
	.A2(n356),
	.ZN(n57));
   INV_X1 U250 (.A(n355),
	.ZN(n446));
   AOI222_X1 U251 (.A1(n342),
	.A2(n80),
	.B1(n342),
	.B2(n83),
	.C1(n83),
	.C2(n80),
	.ZN(n341));
   OAI222_X1 U252 (.A1(n343),
	.A2(n432),
	.B1(n343),
	.B2(n433),
	.C1(n433),
	.C2(n432),
	.ZN(n342));
   INV_X1 U253 (.A(n87),
	.ZN(n433));
   INV_X1 U254 (.A(n84),
	.ZN(n432));
   INV_X1 U255 (.A(n415),
	.ZN(n451));
   INV_X1 U257 (.A(n90),
	.ZN(n434));
   OAI22_X1 U258 (.A1(n374),
	.A2(n353),
	.B1(n375),
	.B2(n435),
	.ZN(n157));
   NOR2_X1 U259 (.A1(n366),
	.A2(n453),
	.ZN(n140));
   OAI22_X1 U260 (.A1(n384),
	.A2(n383),
	.B1(n348),
	.B2(n385),
	.ZN(n148));
   OAI22_X1 U261 (.A1(n375),
	.A2(n353),
	.B1(n376),
	.B2(n435),
	.ZN(n156));
   OAI22_X1 U262 (.A1(n385),
	.A2(n383),
	.B1(n348),
	.B2(n386),
	.ZN(n147));
   INV_X1 U263 (.A(n383),
	.ZN(n438));
   OAI22_X1 U264 (.A1(n392),
	.A2(n365),
	.B1(n366),
	.B2(n393),
	.ZN(n138));
   OAI22_X1 U265 (.A1(n376),
	.A2(n353),
	.B1(n377),
	.B2(n435),
	.ZN(n155));
   NOR2_X1 U269 (.A1(n361),
	.A2(n453),
	.ZN(n130));
   OAI22_X1 U270 (.A1(n386),
	.A2(n383),
	.B1(n348),
	.B2(n387),
	.ZN(n146));
   INV_X1 U271 (.A(n348),
	.ZN(n437));
   OAI22_X1 U272 (.A1(n439),
	.A2(n353),
	.B1(n354),
	.B2(n435),
	.ZN(n351));
   INV_X1 U273 (.A(n352),
	.ZN(n439));
   NAND2_X1 U274 (.A1(n352),
	.A2(n351),
	.ZN(n349));
   OAI22_X1 U275 (.A1(n377),
	.A2(n353),
	.B1(n378),
	.B2(n435),
	.ZN(n154));
   OAI22_X1 U276 (.A1(n393),
	.A2(n365),
	.B1(n366),
	.B2(n394),
	.ZN(n137));
   OAI22_X1 U277 (.A1(n387),
	.A2(n383),
	.B1(n348),
	.B2(n388),
	.ZN(n145));
   OAI22_X1 U278 (.A1(n401),
	.A2(n360),
	.B1(n361),
	.B2(n402),
	.ZN(n128));
   OAI22_X1 U279 (.A1(n388),
	.A2(n383),
	.B1(n348),
	.B2(n389),
	.ZN(n144));
   OAI22_X1 U281 (.A1(n378),
	.A2(n353),
	.B1(n379),
	.B2(n435),
	.ZN(n153));
   NOR2_X1 U282 (.A1(n372),
	.A2(n453),
	.ZN(n120));
   OAI22_X1 U283 (.A1(n394),
	.A2(n365),
	.B1(n366),
	.B2(n395),
	.ZN(n136));
   AOI22_X1 U284 (.A1(n441),
	.A2(n438),
	.B1(n437),
	.B2(n357),
	.ZN(n356));
   INV_X1 U286 (.A(n358),
	.ZN(n441));
   OAI22_X1 U287 (.A1(n379),
	.A2(n353),
	.B1(n380),
	.B2(n435),
	.ZN(n152));
   OAI22_X1 U288 (.A1(n402),
	.A2(n360),
	.B1(n361),
	.B2(n359),
	.ZN(n127));
   OAI22_X1 U289 (.A1(n395),
	.A2(n365),
	.B1(n366),
	.B2(n396),
	.ZN(n135));
   OAI22_X1 U291 (.A1(n389),
	.A2(n383),
	.B1(n348),
	.B2(n358),
	.ZN(n143));
   OAI22_X1 U292 (.A1(n359),
	.A2(n360),
	.B1(n361),
	.B2(n362),
	.ZN(n355));
   INV_X1 U293 (.A(n381),
	.ZN(n427));
   OAI22_X1 U294 (.A1(n408),
	.A2(n371),
	.B1(n372),
	.B2(n409),
	.ZN(n118));
   OAI22_X1 U296 (.A1(n396),
	.A2(n365),
	.B1(n366),
	.B2(n397),
	.ZN(n134));
   AOI22_X1 U298 (.A1(n357),
	.A2(n438),
	.B1(n437),
	.B2(n363),
	.ZN(n50));
   OAI22_X1 U300 (.A1(n398),
	.A2(n365),
	.B1(n366),
	.B2(n364),
	.ZN(n132));
   INV_X1 U302 (.A(n50),
	.ZN(n436));
   OAI22_X1 U304 (.A1(n362),
	.A2(n360),
	.B1(n361),
	.B2(n403),
	.ZN(n125));
   OAI22_X1 U306 (.A1(n409),
	.A2(n371),
	.B1(n372),
	.B2(n410),
	.ZN(n117));
   OAI22_X1 U308 (.A1(n397),
	.A2(n365),
	.B1(n366),
	.B2(n398),
	.ZN(n133));
   OAI22_X1 U309 (.A1(n403),
	.A2(n360),
	.B1(n361),
	.B2(n404),
	.ZN(n124));
   OAI22_X1 U310 (.A1(n410),
	.A2(n371),
	.B1(n372),
	.B2(n411),
	.ZN(n116));
   OAI22_X1 U316 (.A1(n364),
	.A2(n365),
	.B1(n366),
	.B2(n367),
	.ZN(n35));
   OAI22_X1 U318 (.A1(n411),
	.A2(n371),
	.B1(n372),
	.B2(n412),
	.ZN(n115));
   OAI22_X1 U320 (.A1(n404),
	.A2(n360),
	.B1(n361),
	.B2(n405),
	.ZN(n123));
   INV_X1 U322 (.A(n35),
	.ZN(n443));
   OAI22_X1 U325 (.A1(n412),
	.A2(n371),
	.B1(n372),
	.B2(n413),
	.ZN(n114));
   OAI22_X1 U326 (.A1(n405),
	.A2(n360),
	.B1(n361),
	.B2(n368),
	.ZN(n122));
   INV_X1 U329 (.A(n399),
	.ZN(n444));
   OAI22_X1 U332 (.A1(n413),
	.A2(n371),
	.B1(n372),
	.B2(n414),
	.ZN(n113));
   INV_X1 U334 (.A(n25),
	.ZN(n447));
   OAI22_X1 U336 (.A1(n368),
	.A2(n360),
	.B1(n361),
	.B2(n369),
	.ZN(n25));
   OAI22_X1 U338 (.A1(n414),
	.A2(n371),
	.B1(n372),
	.B2(n370),
	.ZN(n112));
   INV_X1 U340 (.A(n406),
	.ZN(n448));
   OAI22_X1 U344 (.A1(n370),
	.A2(n371),
	.B1(n372),
	.B2(n373),
	.ZN(n19));
   AOI222_X1 U347 (.A1(n344),
	.A2(n88),
	.B1(n344),
	.B2(n89),
	.C1(n89),
	.C2(n88),
	.ZN(n343));
   OAI222_X1 U349 (.A1(n345),
	.A2(n434),
	.B1(n346),
	.B2(n345),
	.C1(n346),
	.C2(n434),
	.ZN(n344));
   AOI21_X1 U350 (.A(n347),
	.B1(a[3]),
	.B2(n438),
	.ZN(n346));
   NAND2_X1 U352 (.A1(n348),
	.A2(n390),
	.ZN(n383));
   INV_X1 U354 (.A(a[1]),
	.ZN(n440));
   OAI22_X1 U357 (.A1(n354),
	.A2(n353),
	.B1(n374),
	.B2(n435),
	.ZN(n158));
   OAI22_X1 U359 (.A1(n382),
	.A2(n383),
	.B1(n348),
	.B2(n384),
	.ZN(n149));
   NAND2_X1 U361 (.A1(n366),
	.A2(n417),
	.ZN(n365));
   OAI21_X1 U363 (.A(n416),
	.B1(n445),
	.B2(n365),
	.ZN(n108));
   OAI22_X1 U366 (.A1(n391),
	.A2(n365),
	.B1(n366),
	.B2(n392),
	.ZN(n139));
   OR3_X1 U368 (.A1(n366),
	.A2(b[0]),
	.A3(n445),
	.ZN(n416));
   INV_X1 U369 (.A(a[3]),
	.ZN(n442));
   NOR3_X1 U371 (.A1(n348),
	.A2(b[0]),
	.A3(n442),
	.ZN(n347));
   INV_X1 U373 (.A(a[0]),
	.ZN(n435));
   NAND2_X1 U375 (.A1(a[1]),
	.A2(n435),
	.ZN(n353));
   INV_X1 U377 (.A(b[0]),
	.ZN(n453));
   INV_X1 U379 (.A(a[5]),
	.ZN(n445));
   NOR2_X1 U381 (.A1(n440),
	.A2(b[1]),
	.ZN(n352));
   NAND2_X1 U383 (.A1(n361),
	.A2(n419),
	.ZN(n360));
   OAI21_X1 U386 (.A(n418),
	.B1(n449),
	.B2(n360),
	.ZN(n107));
   OAI22_X1 U388 (.A1(n400),
	.A2(n360),
	.B1(n361),
	.B2(n401),
	.ZN(n129));
   OR3_X1 U389 (.A1(n361),
	.A2(b[0]),
	.A3(n449),
	.ZN(n418));
   NAND2_X1 U390 (.A1(n372),
	.A2(n421),
	.ZN(n371));
   OAI21_X1 U392 (.A(n420),
	.B1(n452),
	.B2(n371),
	.ZN(n106));
   OAI22_X1 U393 (.A1(n407),
	.A2(n371),
	.B1(n372),
	.B2(n408),
	.ZN(n119));
   OR3_X1 U394 (.A1(n372),
	.A2(b[0]),
	.A3(n452),
	.ZN(n420));
   INV_X1 U396 (.A(a[7]),
	.ZN(n449));
   INV_X1 U397 (.A(a[10]),
	.ZN(n452));
   XNOR2_X1 U398 (.A(b[10]),
	.B(a[1]),
	.ZN(n380));
endmodule

module iir_DW_mult_tc_2 (
	a, 
	b, 
	product);
   input [10:0] a;
   input [10:0] b;
   output [21:0] product;

   // Internal wires
   wire FE_OFN2_n370;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n115;
   wire n116;
   wire n117;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n160;
   wire n161;
   wire n162;
   wire n165;
   wire n166;
   wire n167;
   wire n168;
   wire n169;
   wire n170;
   wire n171;
   wire n172;
   wire n357;
   wire n358;
   wire n359;
   wire n360;
   wire n361;
   wire n362;
   wire n363;
   wire n364;
   wire n365;
   wire n366;
   wire n367;
   wire n368;
   wire n369;
   wire n370;
   wire n371;
   wire n372;
   wire n373;
   wire n374;
   wire n375;
   wire n376;
   wire n377;
   wire n378;
   wire n379;
   wire n380;
   wire n381;
   wire n382;
   wire n383;
   wire n384;
   wire n385;
   wire n386;
   wire n387;
   wire n388;
   wire n389;
   wire n390;
   wire n391;
   wire n392;
   wire n393;
   wire n394;
   wire n395;
   wire n396;
   wire n397;
   wire n398;
   wire n399;
   wire n400;
   wire n401;
   wire n402;
   wire n403;
   wire n404;
   wire n405;
   wire n406;
   wire n407;
   wire n408;
   wire n409;
   wire n410;
   wire n411;
   wire n412;
   wire n413;
   wire n414;
   wire n415;
   wire n416;
   wire n417;
   wire n418;
   wire n419;
   wire n420;
   wire n421;
   wire n422;
   wire n423;
   wire n424;
   wire n425;
   wire n426;
   wire n427;
   wire n428;
   wire n429;
   wire n430;
   wire n431;
   wire n432;
   wire n433;
   wire n434;
   wire n435;
   wire n436;
   wire n437;
   wire n438;
   wire n439;
   wire n440;
   wire n441;
   wire n442;
   wire n443;
   wire n444;
   wire n446;
   wire n447;
   wire n448;
   wire n449;
   wire n450;
   wire n451;
   wire n452;
   wire n453;
   wire n454;
   wire n455;
   wire n456;
   wire n457;
   wire n458;
   wire n459;
   wire n460;
   wire n461;
   wire n462;
   wire n463;
   wire n464;
   wire n465;
   wire n466;
   wire n467;
   wire n468;
   wire n469;
   wire n470;
   wire n471;
   wire n472;
   wire n473;
   wire n474;

   OAI21_X1 FE_RC_14_0 (.A(n384),
	.B1(n458),
	.B2(n459),
	.ZN(n153));
   AOI21_X1 FE_RC_6_0 (.A(n390),
	.B1(n382),
	.B2(n381),
	.ZN(n429));
   AOI21_X1 FE_RC_5_0 (.A(n388),
	.B1(n387),
	.B2(n386),
	.ZN(n421));
   AOI21_X1 FE_RC_4_0 (.A(n400),
	.B1(n456),
	.B2(n374),
	.ZN(n401));
   CLKBUF_X1 FE_OFC2_n370 (.A(n370),
	.Z(FE_OFN2_n370));
   FA_X1 U3 (.A(n22),
	.B(n21),
	.CI(n3),
	.S(product[18]));
   FA_X1 U4 (.A(n24),
	.B(n23),
	.CI(n4),
	.CO(n3),
	.S(product[17]));
   FA_X1 U5 (.A(n25),
	.B(n28),
	.CI(n5),
	.CO(n4),
	.S(product[16]));
   FA_X1 U6 (.A(n29),
	.B(n32),
	.CI(n6),
	.CO(n5),
	.S(product[15]));
   FA_X1 U7 (.A(n33),
	.B(n38),
	.CI(n7),
	.CO(n6),
	.S(product[14]));
   FA_X1 U8 (.A(n39),
	.B(n44),
	.CI(n8),
	.CO(n7),
	.S(product[13]));
   FA_X1 U9 (.A(n45),
	.B(n52),
	.CI(n9),
	.CO(n8),
	.S(product[12]));
   FA_X1 U22 (.A(n121),
	.B(n26),
	.CI(n467),
	.CO(n22),
	.S(n23));
   FA_X1 U23 (.A(n466),
	.B(n122),
	.CI(n30),
	.CO(n24),
	.S(n25));
   FA_X1 U25 (.A(n34),
	.B(n123),
	.CI(n31),
	.CO(n28),
	.S(n29));
   FA_X1 U26 (.A(n132),
	.B(n36),
	.CI(n463),
	.CO(n30),
	.S(n31));
   FA_X1 U27 (.A(n35),
	.B(n42),
	.CI(n40),
	.CO(n32),
	.S(n33));
   FA_X1 U28 (.A(n124),
	.B(n133),
	.CI(n462),
	.CO(n34),
	.S(n35));
   FA_X1 U30 (.A(n46),
	.B(n43),
	.CI(n41),
	.CO(n38),
	.S(n39));
   FA_X1 U31 (.A(n457),
	.B(n143),
	.CI(n48),
	.CO(n40),
	.S(n41));
   FA_X1 U32 (.A(n134),
	.B(n125),
	.CI(n153),
	.CO(n42),
	.S(n43));
   FA_X1 U33 (.A(n54),
	.B(n49),
	.CI(n47),
	.CO(n44),
	.S(n45));
   FA_X1 U34 (.A(n58),
	.B(n51),
	.CI(n56),
	.CO(n46),
	.S(n47));
   FA_X1 U35 (.A(n135),
	.B(n126),
	.CI(n144),
	.CO(n48),
	.S(n49));
   FA_X1 U37 (.A(n62),
	.B(n57),
	.CI(n55),
	.CO(n52),
	.S(n53));
   FA_X1 U38 (.A(n59),
	.B(n66),
	.CI(n64),
	.CO(n54),
	.S(n55));
   FA_X1 U39 (.A(n145),
	.B(n127),
	.CI(n455),
	.CO(n56),
	.S(n57));
   FA_X1 U42 (.A(n70),
	.B(n65),
	.CI(n63),
	.CO(n60),
	.S(n61));
   FA_X1 U43 (.A(n67),
	.B(n74),
	.CI(n72),
	.CO(n62),
	.S(n63));
   FA_X1 U44 (.A(n155),
	.B(n146),
	.CI(n165),
	.CO(n64),
	.S(n65));
   HA_X1 U45 (.A(n128),
	.B(n137),
	.CO(n66),
	.S(n67));
   FA_X1 U46 (.A(n73),
	.B(n78),
	.CI(n71),
	.CO(n68),
	.S(n69));
   FA_X1 U47 (.A(n75),
	.B(n166),
	.CI(n80),
	.CO(n70),
	.S(n71));
   FA_X1 U48 (.A(n138),
	.B(n147),
	.CI(n156),
	.CO(n72),
	.S(n73));
   HA_X1 U49 (.A(n115),
	.B(n129),
	.CO(n74),
	.S(n75));
   FA_X1 U50 (.A(n81),
	.B(n84),
	.CI(n79),
	.CO(n76),
	.S(n77));
   FA_X1 U51 (.A(n139),
	.B(n157),
	.CI(n86),
	.CO(n78),
	.S(n79));
   FA_X1 U52 (.A(n148),
	.B(n130),
	.CI(n167),
	.CO(n80),
	.S(n81));
   FA_X1 U53 (.A(n90),
	.B(n87),
	.CI(n85),
	.CO(n82),
	.S(n83));
   FA_X1 U54 (.A(n149),
	.B(n168),
	.CI(n158),
	.CO(n84),
	.S(n85));
   HA_X1 U55 (.A(n116),
	.B(n140),
	.CO(n86),
	.S(n87));
   FA_X1 U56 (.A(n94),
	.B(n150),
	.CI(n91),
	.CO(n88),
	.S(n89));
   FA_X1 U57 (.A(n169),
	.B(n141),
	.CI(n159),
	.CO(n90),
	.S(n91));
   FA_X1 U58 (.A(n160),
	.B(n170),
	.CI(n95),
	.CO(n92),
	.S(n93));
   HA_X1 U59 (.A(n117),
	.B(n151),
	.CO(n94),
	.S(n95));
   FA_X1 U60 (.A(n171),
	.B(n152),
	.CI(n161),
	.CO(n96),
	.S(n97));
   HA_X1 U61 (.A(n162),
	.B(n172),
	.CO(n98),
	.S(n99));
   XNOR2_X2 U279 (.A(a[4]),
	.B(a[3]),
	.ZN(n387));
   XNOR2_X2 U280 (.A(a[6]),
	.B(a[5]),
	.ZN(n382));
   MUX2_X1 U292 (.A(n371),
	.B(n372),
	.S(b[0]),
	.Z(n367));
   NAND3_X1 U294 (.A1(n373),
	.A2(n474),
	.A3(a[1]),
	.ZN(n371));
   XOR2_X1 U296 (.A(n376),
	.B(n377),
	.Z(n59));
   XOR2_X1 U301 (.A(b[9]),
	.B(a[3]),
	.Z(n378));
   XOR2_X1 U305 (.A(b[10]),
	.B(a[10]),
	.Z(n357));
   XOR2_X1 U326 (.A(n473),
	.B(a[3]),
	.Z(n402));
   XOR2_X1 U328 (.A(n474),
	.B(a[3]),
	.Z(n404));
   XOR2_X1 U330 (.A(b[2]),
	.B(n461),
	.Z(n405));
   XOR2_X1 U332 (.A(b[3]),
	.B(n461),
	.Z(n406));
   XOR2_X1 U334 (.A(b[4]),
	.B(n461),
	.Z(n407));
   XOR2_X1 U336 (.A(b[5]),
	.B(n461),
	.Z(n408));
   XOR2_X1 U338 (.A(b[6]),
	.B(n461),
	.Z(n409));
   XOR2_X1 U340 (.A(b[8]),
	.B(n461),
	.Z(n379));
   XOR2_X1 U341 (.A(b[7]),
	.B(n461),
	.Z(n410));
   XOR2_X1 U344 (.A(a[3]),
	.B(a[2]),
	.Z(n411));
   XOR2_X1 U346 (.A(b[10]),
	.B(a[3]),
	.Z(n384));
   XOR2_X1 U349 (.A(n473),
	.B(a[5]),
	.Z(n412));
   XOR2_X1 U351 (.A(n474),
	.B(a[5]),
	.Z(n413));
   XOR2_X1 U353 (.A(b[2]),
	.B(n464),
	.Z(n414));
   XOR2_X1 U355 (.A(b[3]),
	.B(n464),
	.Z(n415));
   XOR2_X1 U357 (.A(b[4]),
	.B(n464),
	.Z(n416));
   XOR2_X1 U359 (.A(b[5]),
	.B(n464),
	.Z(n417));
   XOR2_X1 U361 (.A(b[6]),
	.B(n464),
	.Z(n418));
   XOR2_X1 U363 (.A(b[7]),
	.B(n464),
	.Z(n419));
   XOR2_X1 U365 (.A(b[9]),
	.B(n464),
	.Z(n385));
   XOR2_X1 U366 (.A(b[8]),
	.B(n464),
	.Z(n420));
   XOR2_X1 U368 (.A(b[10]),
	.B(n464),
	.Z(n388));
   XOR2_X1 U371 (.A(n473),
	.B(a[7]),
	.Z(n422));
   XOR2_X1 U373 (.A(n474),
	.B(a[7]),
	.Z(n423));
   XOR2_X1 U375 (.A(b[2]),
	.B(n468),
	.Z(n424));
   XOR2_X1 U377 (.A(b[4]),
	.B(n468),
	.Z(n380));
   XOR2_X1 U378 (.A(b[3]),
	.B(n468),
	.Z(n425));
   XOR2_X1 U380 (.A(b[5]),
	.B(n468),
	.Z(n383));
   XOR2_X1 U382 (.A(b[6]),
	.B(n468),
	.Z(n426));
   XOR2_X1 U384 (.A(b[7]),
	.B(n468),
	.Z(n427));
   XOR2_X1 U386 (.A(b[9]),
	.B(n468),
	.Z(n389));
   XOR2_X1 U387 (.A(b[8]),
	.B(n468),
	.Z(n428));
   XOR2_X1 U389 (.A(b[10]),
	.B(n468),
	.Z(n390));
   XOR2_X1 U392 (.A(n473),
	.B(a[10]),
	.Z(n430));
   XOR2_X1 U394 (.A(n474),
	.B(a[10]),
	.Z(n431));
   XOR2_X1 U396 (.A(b[2]),
	.B(n472),
	.Z(n432));
   XOR2_X1 U398 (.A(b[3]),
	.B(n472),
	.Z(n433));
   XOR2_X1 U400 (.A(b[4]),
	.B(n472),
	.Z(n434));
   XOR2_X1 U402 (.A(b[5]),
	.B(n472),
	.Z(n435));
   XOR2_X1 U404 (.A(b[6]),
	.B(n472),
	.Z(n436));
   XOR2_X1 U406 (.A(b[7]),
	.B(n472),
	.Z(n437));
   XOR2_X1 U408 (.A(b[9]),
	.B(n472),
	.Z(n392));
   XOR2_X1 U409 (.A(b[8]),
	.B(n472),
	.Z(n438));
   XOR2_X1 U413 (.A(a[5]),
	.B(a[4]),
	.Z(n440));
   XOR2_X1 U417 (.A(a[7]),
	.B(a[6]),
	.Z(n442));
   NAND3_X1 U419 (.A1(n358),
	.A2(n473),
	.A3(a[10]),
	.ZN(n443));
   XOR2_X1 U421 (.A(a[10]),
	.B(a[8]),
	.Z(n444));
   XOR2_X1 U422 (.A(a[8]),
	.B(a[7]),
	.Z(n358));
   XNOR2_X1 U250 (.A(a[2]),
	.B(a[1]),
	.ZN(n370));
   AOI222_X1 U251 (.A1(n360),
	.A2(n61),
	.B1(n360),
	.B2(n68),
	.C1(n68),
	.C2(n61),
	.ZN(n359));
   OAI222_X1 U252 (.A1(n361),
	.A2(n453),
	.B1(n361),
	.B2(n451),
	.C1(n451),
	.C2(n453),
	.ZN(n360));
   INV_X1 U253 (.A(n76),
	.ZN(n451));
   INV_X1 U254 (.A(n69),
	.ZN(n453));
   OAI222_X1 U255 (.A1(n359),
	.A2(n454),
	.B1(n359),
	.B2(n452),
	.C1(n452),
	.C2(n454),
	.ZN(n9));
   INV_X1 U256 (.A(n60),
	.ZN(n452));
   INV_X1 U257 (.A(n53),
	.ZN(n454));
   AOI222_X1 U258 (.A1(n362),
	.A2(n77),
	.B1(n362),
	.B2(n82),
	.C1(n82),
	.C2(n77),
	.ZN(n361));
   OAI222_X1 U259 (.A1(n363),
	.A2(n449),
	.B1(n363),
	.B2(n450),
	.C1(n450),
	.C2(n449),
	.ZN(n362));
   INV_X1 U260 (.A(n88),
	.ZN(n450));
   INV_X1 U261 (.A(n83),
	.ZN(n449));
   NAND2_X1 U262 (.A1(n465),
	.A2(n377),
	.ZN(n58));
   INV_X1 U263 (.A(n376),
	.ZN(n465));
   AOI222_X1 U264 (.A1(n364),
	.A2(n89),
	.B1(n364),
	.B2(n92),
	.C1(n92),
	.C2(n89),
	.ZN(n363));
   OAI222_X1 U265 (.A1(n365),
	.A2(n448),
	.B1(n365),
	.B2(n447),
	.C1(n447),
	.C2(n448),
	.ZN(n364));
   INV_X1 U266 (.A(n96),
	.ZN(n447));
   INV_X1 U267 (.A(n93),
	.ZN(n448));
   INV_X1 U268 (.A(n99),
	.ZN(n446));
   NOR2_X1 U269 (.A1(n387),
	.A2(n473),
	.ZN(n152));
   OAI22_X1 U270 (.A1(n393),
	.A2(n374),
	.B1(n394),
	.B2(n456),
	.ZN(n171));
   OAI22_X1 U271 (.A1(n404),
	.A2(n403),
	.B1(FE_OFN2_n370),
	.B2(n405),
	.ZN(n161));
   INV_X1 U272 (.A(n403),
	.ZN(n459));
   OAI22_X1 U273 (.A1(n394),
	.A2(n374),
	.B1(n395),
	.B2(n456),
	.ZN(n170));
   OAI22_X1 U274 (.A1(n405),
	.A2(n403),
	.B1(FE_OFN2_n370),
	.B2(n406),
	.ZN(n160));
   OAI22_X1 U275 (.A1(n413),
	.A2(n386),
	.B1(n387),
	.B2(n414),
	.ZN(n150));
   NOR2_X1 U276 (.A1(n382),
	.A2(n473),
	.ZN(n141));
   OAI22_X1 U277 (.A1(n395),
	.A2(n374),
	.B1(n396),
	.B2(n456),
	.ZN(n169));
   OAI22_X1 U278 (.A1(n406),
	.A2(n403),
	.B1(FE_OFN2_n370),
	.B2(n407),
	.ZN(n159));
   INV_X1 U281 (.A(FE_OFN2_n370),
	.ZN(n458));
   NAND2_X1 U282 (.A1(n458),
	.A2(n373),
	.ZN(n372));
   OAI22_X1 U283 (.A1(n396),
	.A2(n374),
	.B1(n397),
	.B2(n456),
	.ZN(n168));
   OAI22_X1 U284 (.A1(n414),
	.A2(n386),
	.B1(n387),
	.B2(n415),
	.ZN(n149));
   OAI22_X1 U285 (.A1(n407),
	.A2(n403),
	.B1(FE_OFN2_n370),
	.B2(n408),
	.ZN(n158));
   OAI22_X1 U286 (.A1(n423),
	.A2(n381),
	.B1(n382),
	.B2(n424),
	.ZN(n139));
   OAI22_X1 U287 (.A1(n408),
	.A2(n403),
	.B1(FE_OFN2_n370),
	.B2(n409),
	.ZN(n157));
   NOR2_X1 U288 (.A1(n470),
	.A2(n473),
	.ZN(n130));
   OAI22_X1 U289 (.A1(n397),
	.A2(n374),
	.B1(n398),
	.B2(n456),
	.ZN(n167));
   OAI22_X1 U290 (.A1(n415),
	.A2(n386),
	.B1(n387),
	.B2(n416),
	.ZN(n148));
   OAI22_X1 U291 (.A1(n398),
	.A2(n374),
	.B1(n399),
	.B2(n456),
	.ZN(n166));
   OAI22_X1 U293 (.A1(n424),
	.A2(n381),
	.B1(n382),
	.B2(n425),
	.ZN(n138));
   OAI22_X1 U295 (.A1(n416),
	.A2(n386),
	.B1(n387),
	.B2(n417),
	.ZN(n147));
   OAI22_X1 U297 (.A1(n409),
	.A2(n403),
	.B1(FE_OFN2_n370),
	.B2(n410),
	.ZN(n156));
   INV_X1 U298 (.A(n358),
	.ZN(n470));
   OAI22_X1 U299 (.A1(n431),
	.A2(n391),
	.B1(n470),
	.B2(n432),
	.ZN(n128));
   OAI22_X1 U300 (.A1(n425),
	.A2(n381),
	.B1(n382),
	.B2(n380),
	.ZN(n137));
   AOI22_X1 U302 (.A1(n460),
	.A2(n459),
	.B1(n458),
	.B2(n378),
	.ZN(n377));
   INV_X1 U303 (.A(n379),
	.ZN(n460));
   OAI22_X1 U304 (.A1(n399),
	.A2(n374),
	.B1(n400),
	.B2(n456),
	.ZN(n165));
   OAI22_X1 U306 (.A1(n417),
	.A2(n386),
	.B1(n387),
	.B2(n418),
	.ZN(n146));
   OAI22_X1 U307 (.A1(n410),
	.A2(n403),
	.B1(FE_OFN2_n370),
	.B2(n379),
	.ZN(n155));
   OAI22_X1 U308 (.A1(n380),
	.A2(n381),
	.B1(n382),
	.B2(n383),
	.ZN(n376));
   INV_X1 U309 (.A(n401),
	.ZN(n455));
   OAI22_X1 U310 (.A1(n432),
	.A2(n391),
	.B1(n470),
	.B2(n433),
	.ZN(n127));
   OAI22_X1 U311 (.A1(n418),
	.A2(n386),
	.B1(n387),
	.B2(n419),
	.ZN(n145));
   AOI22_X1 U312 (.A1(n378),
	.A2(n459),
	.B1(n458),
	.B2(n384),
	.ZN(n51));
   OAI22_X1 U314 (.A1(n420),
	.A2(n386),
	.B1(n387),
	.B2(n385),
	.ZN(n143));
   INV_X1 U315 (.A(n51),
	.ZN(n457));
   OAI22_X1 U316 (.A1(n433),
	.A2(n391),
	.B1(n470),
	.B2(n434),
	.ZN(n126));
   OAI22_X1 U317 (.A1(n383),
	.A2(n381),
	.B1(n382),
	.B2(n426),
	.ZN(n135));
   OAI22_X1 U318 (.A1(n419),
	.A2(n386),
	.B1(n387),
	.B2(n420),
	.ZN(n144));
   OAI22_X1 U319 (.A1(n434),
	.A2(n391),
	.B1(n470),
	.B2(n435),
	.ZN(n125));
   OAI22_X1 U320 (.A1(n426),
	.A2(n381),
	.B1(n382),
	.B2(n427),
	.ZN(n134));
   OAI22_X1 U322 (.A1(n385),
	.A2(n386),
	.B1(n387),
	.B2(n388),
	.ZN(n36));
   OAI22_X1 U323 (.A1(n435),
	.A2(n391),
	.B1(n470),
	.B2(n436),
	.ZN(n124));
   OAI22_X1 U324 (.A1(n427),
	.A2(n381),
	.B1(n382),
	.B2(n428),
	.ZN(n133));
   INV_X1 U325 (.A(n36),
	.ZN(n462));
   OAI22_X1 U327 (.A1(n436),
	.A2(n391),
	.B1(n470),
	.B2(n437),
	.ZN(n123));
   OAI22_X1 U329 (.A1(n428),
	.A2(n381),
	.B1(n382),
	.B2(n389),
	.ZN(n132));
   INV_X1 U331 (.A(n421),
	.ZN(n463));
   OAI22_X1 U335 (.A1(n437),
	.A2(n391),
	.B1(n470),
	.B2(n438),
	.ZN(n122));
   INV_X1 U337 (.A(n26),
	.ZN(n466));
   OAI22_X1 U339 (.A1(n389),
	.A2(n381),
	.B1(n382),
	.B2(n390),
	.ZN(n26));
   OAI22_X1 U342 (.A1(n438),
	.A2(n391),
	.B1(n470),
	.B2(n392),
	.ZN(n121));
   INV_X1 U343 (.A(n429),
	.ZN(n467));
   INV_X1 U347 (.A(n391),
	.ZN(n469));
   AOI222_X1 U348 (.A1(n366),
	.A2(n97),
	.B1(n366),
	.B2(n98),
	.C1(n98),
	.C2(n97),
	.ZN(n365));
   OAI222_X1 U350 (.A1(n367),
	.A2(n446),
	.B1(n368),
	.B2(n367),
	.C1(n368),
	.C2(n446),
	.ZN(n366));
   AOI21_X1 U352 (.A(n369),
	.B1(a[3]),
	.B2(n459),
	.ZN(n368));
   NAND2_X1 U354 (.A1(FE_OFN2_n370),
	.A2(n411),
	.ZN(n403));
   OAI22_X1 U356 (.A1(n375),
	.A2(n374),
	.B1(n393),
	.B2(n456),
	.ZN(n172));
   OAI22_X1 U358 (.A1(n402),
	.A2(n403),
	.B1(FE_OFN2_n370),
	.B2(n404),
	.ZN(n162));
   AOI22_X1 U360 (.A1(n471),
	.A2(n469),
	.B1(n358),
	.B2(n357),
	.ZN(n21));
   INV_X1 U362 (.A(n392),
	.ZN(n471));
   NAND2_X1 U364 (.A1(n387),
	.A2(n440),
	.ZN(n386));
   OAI21_X1 U367 (.A(n439),
	.B1(n464),
	.B2(n386),
	.ZN(n117));
   OAI22_X1 U369 (.A1(n412),
	.A2(n386),
	.B1(n387),
	.B2(n413),
	.ZN(n151));
   OR3_X1 U370 (.A1(n387),
	.A2(b[0]),
	.A3(n464),
	.ZN(n439));
   NAND2_X1 U372 (.A1(a[1]),
	.A2(n456),
	.ZN(n374));
   XNOR2_X1 U374 (.A(b[3]),
	.B(a[1]),
	.ZN(n393));
   XNOR2_X1 U376 (.A(b[2]),
	.B(a[1]),
	.ZN(n375));
   NOR3_X1 U379 (.A1(FE_OFN2_n370),
	.A2(b[0]),
	.A3(n461),
	.ZN(n369));
   OAI22_X1 U381 (.A1(b[1]),
	.A2(n374),
	.B1(n375),
	.B2(n456),
	.ZN(n373));
   INV_X1 U383 (.A(b[0]),
	.ZN(n473));
   INV_X1 U385 (.A(a[3]),
	.ZN(n461));
   XNOR2_X1 U388 (.A(b[4]),
	.B(a[1]),
	.ZN(n394));
   INV_X1 U390 (.A(a[0]),
	.ZN(n456));
   INV_X1 U391 (.A(b[1]),
	.ZN(n474));
   XNOR2_X1 U393 (.A(b[6]),
	.B(a[1]),
	.ZN(n396));
   XNOR2_X1 U395 (.A(b[5]),
	.B(a[1]),
	.ZN(n395));
   INV_X1 U397 (.A(a[5]),
	.ZN(n464));
   NAND2_X1 U399 (.A1(n382),
	.A2(n442),
	.ZN(n381));
   OAI21_X1 U401 (.A(n441),
	.B1(n468),
	.B2(n381),
	.ZN(n116));
   OAI22_X1 U403 (.A1(n422),
	.A2(n381),
	.B1(n382),
	.B2(n423),
	.ZN(n140));
   OR3_X1 U405 (.A1(n382),
	.A2(b[0]),
	.A3(n468),
	.ZN(n441));
   XNOR2_X1 U407 (.A(b[7]),
	.B(a[1]),
	.ZN(n397));
   NAND2_X1 U410 (.A1(n470),
	.A2(n444),
	.ZN(n391));
   OAI21_X1 U411 (.A(n443),
	.B1(n472),
	.B2(n391),
	.ZN(n115));
   OAI22_X1 U412 (.A1(n430),
	.A2(n391),
	.B1(n470),
	.B2(n431),
	.ZN(n129));
   XNOR2_X1 U414 (.A(b[8]),
	.B(a[1]),
	.ZN(n398));
   INV_X1 U415 (.A(a[7]),
	.ZN(n468));
   XNOR2_X1 U416 (.A(b[9]),
	.B(a[1]),
	.ZN(n399));
   INV_X1 U418 (.A(a[10]),
	.ZN(n472));
   XNOR2_X1 U420 (.A(b[10]),
	.B(a[1]),
	.ZN(n400));
endmodule

module iir_DW_mult_tc_1 (
	a, 
	b, 
	product);
   input [10:0] a;
   input [10:0] b;
   output [21:0] product;

   // Internal wires
   wire FE_OFN0_n372;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n115;
   wire n116;
   wire n117;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n160;
   wire n161;
   wire n162;
   wire n165;
   wire n166;
   wire n167;
   wire n168;
   wire n169;
   wire n170;
   wire n171;
   wire n172;
   wire n357;
   wire n358;
   wire n359;
   wire n360;
   wire n361;
   wire n362;
   wire n363;
   wire n364;
   wire n365;
   wire n366;
   wire n367;
   wire n368;
   wire n369;
   wire n370;
   wire n371;
   wire n372;
   wire n373;
   wire n374;
   wire n375;
   wire n376;
   wire n377;
   wire n378;
   wire n379;
   wire n380;
   wire n381;
   wire n382;
   wire n383;
   wire n384;
   wire n385;
   wire n386;
   wire n387;
   wire n388;
   wire n389;
   wire n390;
   wire n391;
   wire n392;
   wire n393;
   wire n394;
   wire n395;
   wire n396;
   wire n397;
   wire n398;
   wire n399;
   wire n400;
   wire n401;
   wire n402;
   wire n403;
   wire n404;
   wire n405;
   wire n406;
   wire n407;
   wire n408;
   wire n409;
   wire n410;
   wire n411;
   wire n412;
   wire n413;
   wire n414;
   wire n415;
   wire n416;
   wire n417;
   wire n418;
   wire n419;
   wire n420;
   wire n421;
   wire n422;
   wire n423;
   wire n424;
   wire n425;
   wire n426;
   wire n427;
   wire n428;
   wire n429;
   wire n430;
   wire n431;
   wire n432;
   wire n433;
   wire n434;
   wire n435;
   wire n436;
   wire n437;
   wire n438;
   wire n439;
   wire n440;
   wire n441;
   wire n442;
   wire n443;
   wire n444;
   wire n445;
   wire n446;
   wire n448;
   wire n449;
   wire n450;
   wire n451;
   wire n452;
   wire n453;
   wire n454;
   wire n455;
   wire n456;
   wire n457;
   wire n458;
   wire n459;
   wire n460;
   wire n461;
   wire n462;
   wire n463;
   wire n464;
   wire n465;
   wire n466;
   wire n467;
   wire n468;
   wire n469;
   wire n470;
   wire n471;
   wire n472;
   wire n473;
   wire n474;
   wire n475;
   wire n476;

   OAI21_X1 FE_RC_16_0 (.A(n386),
	.B1(n460),
	.B2(n461),
	.ZN(n153));
   OAI21_X1 FE_RC_15_0 (.A(n359),
	.B1(n360),
	.B2(n471),
	.ZN(n358));
   AOI21_X1 FE_RC_9_0 (.A(n392),
	.B1(n384),
	.B2(n383),
	.ZN(n431));
   AOI21_X1 FE_RC_8_0 (.A(n390),
	.B1(n389),
	.B2(n388),
	.ZN(n423));
   AOI21_X1 FE_RC_7_0 (.A(n402),
	.B1(n458),
	.B2(n376),
	.ZN(n403));
   CLKBUF_X1 FE_OFC0_n372 (.A(n372),
	.Z(FE_OFN0_n372));
   FA_X1 U3 (.A(n22),
	.B(n21),
	.CI(n3),
	.CO(n2),
	.S(product[18]));
   FA_X1 U4 (.A(n24),
	.B(n23),
	.CI(n4),
	.CO(n3),
	.S(product[17]));
   FA_X1 U5 (.A(n25),
	.B(n28),
	.CI(n5),
	.CO(n4),
	.S(product[16]));
   FA_X1 U6 (.A(n29),
	.B(n32),
	.CI(n6),
	.CO(n5),
	.S(product[15]));
   FA_X1 U7 (.A(n33),
	.B(n38),
	.CI(n7),
	.CO(n6),
	.S(product[14]));
   FA_X1 U8 (.A(n39),
	.B(n44),
	.CI(n8),
	.CO(n7),
	.S(product[13]));
   FA_X1 U9 (.A(n45),
	.B(n52),
	.CI(n9),
	.CO(n8),
	.S(product[12]));
   FA_X1 U22 (.A(n121),
	.B(n26),
	.CI(n469),
	.CO(n22),
	.S(n23));
   FA_X1 U23 (.A(n468),
	.B(n122),
	.CI(n30),
	.CO(n24),
	.S(n25));
   FA_X1 U25 (.A(n34),
	.B(n123),
	.CI(n31),
	.CO(n28),
	.S(n29));
   FA_X1 U26 (.A(n132),
	.B(n36),
	.CI(n465),
	.CO(n30),
	.S(n31));
   FA_X1 U27 (.A(n35),
	.B(n42),
	.CI(n40),
	.CO(n32),
	.S(n33));
   FA_X1 U28 (.A(n124),
	.B(n133),
	.CI(n464),
	.CO(n34),
	.S(n35));
   FA_X1 U30 (.A(n46),
	.B(n43),
	.CI(n41),
	.CO(n38),
	.S(n39));
   FA_X1 U31 (.A(n459),
	.B(n143),
	.CI(n48),
	.CO(n40),
	.S(n41));
   FA_X1 U32 (.A(n134),
	.B(n125),
	.CI(n153),
	.CO(n42),
	.S(n43));
   FA_X1 U33 (.A(n54),
	.B(n49),
	.CI(n47),
	.CO(n44),
	.S(n45));
   FA_X1 U34 (.A(n58),
	.B(n51),
	.CI(n56),
	.CO(n46),
	.S(n47));
   FA_X1 U35 (.A(n135),
	.B(n126),
	.CI(n144),
	.CO(n48),
	.S(n49));
   FA_X1 U37 (.A(n62),
	.B(n57),
	.CI(n55),
	.CO(n52),
	.S(n53));
   FA_X1 U38 (.A(n59),
	.B(n66),
	.CI(n64),
	.CO(n54),
	.S(n55));
   FA_X1 U39 (.A(n145),
	.B(n127),
	.CI(n457),
	.CO(n56),
	.S(n57));
   FA_X1 U42 (.A(n70),
	.B(n65),
	.CI(n63),
	.CO(n60),
	.S(n61));
   FA_X1 U43 (.A(n67),
	.B(n74),
	.CI(n72),
	.CO(n62),
	.S(n63));
   FA_X1 U44 (.A(n155),
	.B(n146),
	.CI(n165),
	.CO(n64),
	.S(n65));
   HA_X1 U45 (.A(n128),
	.B(n137),
	.CO(n66),
	.S(n67));
   FA_X1 U46 (.A(n73),
	.B(n78),
	.CI(n71),
	.CO(n68),
	.S(n69));
   FA_X1 U47 (.A(n75),
	.B(n166),
	.CI(n80),
	.CO(n70),
	.S(n71));
   FA_X1 U48 (.A(n138),
	.B(n147),
	.CI(n156),
	.CO(n72),
	.S(n73));
   HA_X1 U49 (.A(n115),
	.B(n129),
	.CO(n74),
	.S(n75));
   FA_X1 U50 (.A(n81),
	.B(n84),
	.CI(n79),
	.CO(n76),
	.S(n77));
   FA_X1 U51 (.A(n139),
	.B(n157),
	.CI(n86),
	.CO(n78),
	.S(n79));
   FA_X1 U52 (.A(n148),
	.B(n130),
	.CI(n167),
	.CO(n80),
	.S(n81));
   FA_X1 U53 (.A(n90),
	.B(n87),
	.CI(n85),
	.CO(n82),
	.S(n83));
   FA_X1 U54 (.A(n149),
	.B(n168),
	.CI(n158),
	.CO(n84),
	.S(n85));
   HA_X1 U55 (.A(n116),
	.B(n140),
	.CO(n86),
	.S(n87));
   FA_X1 U56 (.A(n94),
	.B(n150),
	.CI(n91),
	.CO(n88),
	.S(n89));
   FA_X1 U57 (.A(n169),
	.B(n141),
	.CI(n159),
	.CO(n90),
	.S(n91));
   FA_X1 U58 (.A(n160),
	.B(n170),
	.CI(n95),
	.CO(n92),
	.S(n93));
   HA_X1 U59 (.A(n117),
	.B(n151),
	.CO(n94),
	.S(n95));
   FA_X1 U60 (.A(n171),
	.B(n152),
	.CI(n161),
	.CO(n96),
	.S(n97));
   HA_X1 U61 (.A(n162),
	.B(n172),
	.CO(n98),
	.S(n99));
   XNOR2_X2 U279 (.A(a[4]),
	.B(a[3]),
	.ZN(n389));
   XNOR2_X2 U280 (.A(a[6]),
	.B(a[5]),
	.ZN(n384));
   XOR2_X1 U282 (.A(n2),
	.B(n358),
	.Z(n357));
   MUX2_X1 U295 (.A(n373),
	.B(n374),
	.S(b[0]),
	.Z(n369));
   NAND3_X1 U297 (.A1(n375),
	.A2(n476),
	.A3(a[1]),
	.ZN(n373));
   XOR2_X1 U299 (.A(n378),
	.B(n379),
	.Z(n59));
   XOR2_X1 U304 (.A(b[9]),
	.B(a[3]),
	.Z(n380));
   XOR2_X1 U308 (.A(b[10]),
	.B(a[10]),
	.Z(n359));
   XOR2_X1 U329 (.A(n475),
	.B(a[3]),
	.Z(n404));
   XOR2_X1 U331 (.A(n476),
	.B(a[3]),
	.Z(n406));
   XOR2_X1 U333 (.A(b[2]),
	.B(n463),
	.Z(n407));
   XOR2_X1 U335 (.A(b[3]),
	.B(n463),
	.Z(n408));
   XOR2_X1 U337 (.A(b[4]),
	.B(n463),
	.Z(n409));
   XOR2_X1 U339 (.A(b[5]),
	.B(n463),
	.Z(n410));
   XOR2_X1 U341 (.A(b[6]),
	.B(n463),
	.Z(n411));
   XOR2_X1 U343 (.A(b[8]),
	.B(n463),
	.Z(n381));
   XOR2_X1 U344 (.A(b[7]),
	.B(n463),
	.Z(n412));
   XOR2_X1 U347 (.A(a[3]),
	.B(a[2]),
	.Z(n413));
   XOR2_X1 U349 (.A(b[10]),
	.B(a[3]),
	.Z(n386));
   XOR2_X1 U352 (.A(n475),
	.B(a[5]),
	.Z(n414));
   XOR2_X1 U354 (.A(n476),
	.B(a[5]),
	.Z(n415));
   XOR2_X1 U356 (.A(b[2]),
	.B(n466),
	.Z(n416));
   XOR2_X1 U358 (.A(b[3]),
	.B(n466),
	.Z(n417));
   XOR2_X1 U360 (.A(b[4]),
	.B(n466),
	.Z(n418));
   XOR2_X1 U362 (.A(b[5]),
	.B(n466),
	.Z(n419));
   XOR2_X1 U364 (.A(b[6]),
	.B(n466),
	.Z(n420));
   XOR2_X1 U366 (.A(b[7]),
	.B(n466),
	.Z(n421));
   XOR2_X1 U368 (.A(b[9]),
	.B(n466),
	.Z(n387));
   XOR2_X1 U369 (.A(b[8]),
	.B(n466),
	.Z(n422));
   XOR2_X1 U371 (.A(b[10]),
	.B(n466),
	.Z(n390));
   XOR2_X1 U374 (.A(n475),
	.B(a[7]),
	.Z(n424));
   XOR2_X1 U376 (.A(n476),
	.B(a[7]),
	.Z(n425));
   XOR2_X1 U378 (.A(b[2]),
	.B(n470),
	.Z(n426));
   XOR2_X1 U380 (.A(b[4]),
	.B(n470),
	.Z(n382));
   XOR2_X1 U381 (.A(b[3]),
	.B(n470),
	.Z(n427));
   XOR2_X1 U383 (.A(b[5]),
	.B(n470),
	.Z(n385));
   XOR2_X1 U385 (.A(b[6]),
	.B(n470),
	.Z(n428));
   XOR2_X1 U387 (.A(b[7]),
	.B(n470),
	.Z(n429));
   XOR2_X1 U389 (.A(b[9]),
	.B(n470),
	.Z(n391));
   XOR2_X1 U390 (.A(b[8]),
	.B(n470),
	.Z(n430));
   XOR2_X1 U392 (.A(b[10]),
	.B(n470),
	.Z(n392));
   XOR2_X1 U395 (.A(n475),
	.B(a[10]),
	.Z(n432));
   XOR2_X1 U397 (.A(n476),
	.B(a[10]),
	.Z(n433));
   XOR2_X1 U399 (.A(b[2]),
	.B(n474),
	.Z(n434));
   XOR2_X1 U401 (.A(b[3]),
	.B(n474),
	.Z(n435));
   XOR2_X1 U403 (.A(b[4]),
	.B(n474),
	.Z(n436));
   XOR2_X1 U405 (.A(b[5]),
	.B(n474),
	.Z(n437));
   XOR2_X1 U407 (.A(b[6]),
	.B(n474),
	.Z(n438));
   XOR2_X1 U409 (.A(b[7]),
	.B(n474),
	.Z(n439));
   XOR2_X1 U411 (.A(b[9]),
	.B(n474),
	.Z(n394));
   XOR2_X1 U412 (.A(b[8]),
	.B(n474),
	.Z(n440));
   XOR2_X1 U416 (.A(a[5]),
	.B(a[4]),
	.Z(n442));
   XOR2_X1 U420 (.A(a[7]),
	.B(a[6]),
	.Z(n444));
   NAND3_X1 U422 (.A1(n360),
	.A2(n475),
	.A3(a[10]),
	.ZN(n445));
   XOR2_X1 U424 (.A(a[10]),
	.B(a[8]),
	.Z(n446));
   XOR2_X1 U425 (.A(a[8]),
	.B(a[7]),
	.Z(n360));
   XNOR2_X1 U250 (.A(a[2]),
	.B(a[1]),
	.ZN(n372));
   AOI222_X1 U251 (.A1(n362),
	.A2(n61),
	.B1(n362),
	.B2(n68),
	.C1(n68),
	.C2(n61),
	.ZN(n361));
   OAI222_X1 U252 (.A1(n363),
	.A2(n455),
	.B1(n363),
	.B2(n453),
	.C1(n453),
	.C2(n455),
	.ZN(n362));
   INV_X1 U253 (.A(n76),
	.ZN(n453));
   INV_X1 U254 (.A(n69),
	.ZN(n455));
   OAI222_X1 U255 (.A1(n361),
	.A2(n456),
	.B1(n361),
	.B2(n454),
	.C1(n454),
	.C2(n456),
	.ZN(n9));
   INV_X1 U256 (.A(n60),
	.ZN(n454));
   INV_X1 U257 (.A(n53),
	.ZN(n456));
   AOI222_X1 U258 (.A1(n364),
	.A2(n77),
	.B1(n364),
	.B2(n82),
	.C1(n82),
	.C2(n77),
	.ZN(n363));
   OAI222_X1 U259 (.A1(n365),
	.A2(n451),
	.B1(n365),
	.B2(n452),
	.C1(n452),
	.C2(n451),
	.ZN(n364));
   INV_X1 U260 (.A(n88),
	.ZN(n452));
   INV_X1 U261 (.A(n83),
	.ZN(n451));
   NAND2_X1 U262 (.A1(n467),
	.A2(n379),
	.ZN(n58));
   INV_X1 U263 (.A(n378),
	.ZN(n467));
   AOI222_X1 U264 (.A1(n366),
	.A2(n89),
	.B1(n366),
	.B2(n92),
	.C1(n92),
	.C2(n89),
	.ZN(n365));
   OAI222_X1 U265 (.A1(n367),
	.A2(n450),
	.B1(n367),
	.B2(n449),
	.C1(n449),
	.C2(n450),
	.ZN(n366));
   INV_X1 U266 (.A(n96),
	.ZN(n449));
   INV_X1 U267 (.A(n93),
	.ZN(n450));
   XNOR2_X1 U268 (.A(n21),
	.B(n357),
	.ZN(product[19]));
   INV_X1 U270 (.A(n99),
	.ZN(n448));
   NOR2_X1 U271 (.A1(n389),
	.A2(n475),
	.ZN(n152));
   OAI22_X1 U272 (.A1(n395),
	.A2(n376),
	.B1(n396),
	.B2(n458),
	.ZN(n171));
   OAI22_X1 U273 (.A1(n406),
	.A2(n405),
	.B1(FE_OFN0_n372),
	.B2(n407),
	.ZN(n161));
   INV_X1 U274 (.A(n405),
	.ZN(n461));
   OAI22_X1 U275 (.A1(n396),
	.A2(n376),
	.B1(n397),
	.B2(n458),
	.ZN(n170));
   OAI22_X1 U276 (.A1(n407),
	.A2(n405),
	.B1(FE_OFN0_n372),
	.B2(n408),
	.ZN(n160));
   OAI22_X1 U277 (.A1(n415),
	.A2(n388),
	.B1(n389),
	.B2(n416),
	.ZN(n150));
   NOR2_X1 U278 (.A1(n384),
	.A2(n475),
	.ZN(n141));
   OAI22_X1 U281 (.A1(n397),
	.A2(n376),
	.B1(n398),
	.B2(n458),
	.ZN(n169));
   OAI22_X1 U283 (.A1(n408),
	.A2(n405),
	.B1(FE_OFN0_n372),
	.B2(n409),
	.ZN(n159));
   INV_X1 U284 (.A(FE_OFN0_n372),
	.ZN(n460));
   NAND2_X1 U285 (.A1(n460),
	.A2(n375),
	.ZN(n374));
   OAI22_X1 U286 (.A1(n398),
	.A2(n376),
	.B1(n399),
	.B2(n458),
	.ZN(n168));
   OAI22_X1 U287 (.A1(n416),
	.A2(n388),
	.B1(n389),
	.B2(n417),
	.ZN(n149));
   OAI22_X1 U288 (.A1(n409),
	.A2(n405),
	.B1(FE_OFN0_n372),
	.B2(n410),
	.ZN(n158));
   OAI22_X1 U289 (.A1(n425),
	.A2(n383),
	.B1(n384),
	.B2(n426),
	.ZN(n139));
   OAI22_X1 U290 (.A1(n410),
	.A2(n405),
	.B1(FE_OFN0_n372),
	.B2(n411),
	.ZN(n157));
   NOR2_X1 U291 (.A1(n472),
	.A2(n475),
	.ZN(n130));
   OAI22_X1 U292 (.A1(n399),
	.A2(n376),
	.B1(n400),
	.B2(n458),
	.ZN(n167));
   OAI22_X1 U293 (.A1(n417),
	.A2(n388),
	.B1(n389),
	.B2(n418),
	.ZN(n148));
   OAI22_X1 U294 (.A1(n400),
	.A2(n376),
	.B1(n401),
	.B2(n458),
	.ZN(n166));
   INV_X1 U296 (.A(n360),
	.ZN(n472));
   OAI22_X1 U298 (.A1(n426),
	.A2(n383),
	.B1(n384),
	.B2(n427),
	.ZN(n138));
   OAI22_X1 U300 (.A1(n418),
	.A2(n388),
	.B1(n389),
	.B2(n419),
	.ZN(n147));
   OAI22_X1 U301 (.A1(n411),
	.A2(n405),
	.B1(FE_OFN0_n372),
	.B2(n412),
	.ZN(n156));
   OAI22_X1 U302 (.A1(n433),
	.A2(n393),
	.B1(n472),
	.B2(n434),
	.ZN(n128));
   OAI22_X1 U303 (.A1(n427),
	.A2(n383),
	.B1(n384),
	.B2(n382),
	.ZN(n137));
   AOI22_X1 U305 (.A1(n462),
	.A2(n461),
	.B1(n460),
	.B2(n380),
	.ZN(n379));
   INV_X1 U306 (.A(n381),
	.ZN(n462));
   OAI22_X1 U307 (.A1(n401),
	.A2(n376),
	.B1(n402),
	.B2(n458),
	.ZN(n165));
   OAI22_X1 U309 (.A1(n419),
	.A2(n388),
	.B1(n389),
	.B2(n420),
	.ZN(n146));
   OAI22_X1 U310 (.A1(n412),
	.A2(n405),
	.B1(FE_OFN0_n372),
	.B2(n381),
	.ZN(n155));
   OAI22_X1 U311 (.A1(n382),
	.A2(n383),
	.B1(n384),
	.B2(n385),
	.ZN(n378));
   INV_X1 U312 (.A(n403),
	.ZN(n457));
   OAI22_X1 U313 (.A1(n434),
	.A2(n393),
	.B1(n472),
	.B2(n435),
	.ZN(n127));
   OAI22_X1 U314 (.A1(n420),
	.A2(n388),
	.B1(n389),
	.B2(n421),
	.ZN(n145));
   AOI22_X1 U315 (.A1(n380),
	.A2(n461),
	.B1(n460),
	.B2(n386),
	.ZN(n51));
   OAI22_X1 U317 (.A1(n422),
	.A2(n388),
	.B1(n389),
	.B2(n387),
	.ZN(n143));
   INV_X1 U318 (.A(n51),
	.ZN(n459));
   OAI22_X1 U319 (.A1(n435),
	.A2(n393),
	.B1(n472),
	.B2(n436),
	.ZN(n126));
   OAI22_X1 U320 (.A1(n385),
	.A2(n383),
	.B1(n384),
	.B2(n428),
	.ZN(n135));
   OAI22_X1 U321 (.A1(n421),
	.A2(n388),
	.B1(n389),
	.B2(n422),
	.ZN(n144));
   OAI22_X1 U322 (.A1(n436),
	.A2(n393),
	.B1(n472),
	.B2(n437),
	.ZN(n125));
   OAI22_X1 U323 (.A1(n428),
	.A2(n383),
	.B1(n384),
	.B2(n429),
	.ZN(n134));
   OAI22_X1 U325 (.A1(n387),
	.A2(n388),
	.B1(n389),
	.B2(n390),
	.ZN(n36));
   OAI22_X1 U326 (.A1(n437),
	.A2(n393),
	.B1(n472),
	.B2(n438),
	.ZN(n124));
   OAI22_X1 U327 (.A1(n429),
	.A2(n383),
	.B1(n384),
	.B2(n430),
	.ZN(n133));
   INV_X1 U328 (.A(n36),
	.ZN(n464));
   OAI22_X1 U330 (.A1(n438),
	.A2(n393),
	.B1(n472),
	.B2(n439),
	.ZN(n123));
   OAI22_X1 U332 (.A1(n430),
	.A2(n383),
	.B1(n384),
	.B2(n391),
	.ZN(n132));
   INV_X1 U334 (.A(n423),
	.ZN(n465));
   OAI22_X1 U338 (.A1(n439),
	.A2(n393),
	.B1(n472),
	.B2(n440),
	.ZN(n122));
   INV_X1 U340 (.A(n26),
	.ZN(n468));
   OAI22_X1 U342 (.A1(n391),
	.A2(n383),
	.B1(n384),
	.B2(n392),
	.ZN(n26));
   OAI22_X1 U345 (.A1(n440),
	.A2(n393),
	.B1(n472),
	.B2(n394),
	.ZN(n121));
   INV_X1 U346 (.A(n431),
	.ZN(n469));
   AOI22_X1 U350 (.A1(n473),
	.A2(n471),
	.B1(n360),
	.B2(n359),
	.ZN(n21));
   INV_X1 U351 (.A(n394),
	.ZN(n473));
   INV_X1 U353 (.A(n393),
	.ZN(n471));
   AOI222_X1 U355 (.A1(n368),
	.A2(n97),
	.B1(n368),
	.B2(n98),
	.C1(n98),
	.C2(n97),
	.ZN(n367));
   OAI222_X1 U357 (.A1(n369),
	.A2(n448),
	.B1(n370),
	.B2(n369),
	.C1(n370),
	.C2(n448),
	.ZN(n368));
   AOI21_X1 U359 (.A(n371),
	.B1(a[3]),
	.B2(n461),
	.ZN(n370));
   NAND2_X1 U361 (.A1(FE_OFN0_n372),
	.A2(n413),
	.ZN(n405));
   OAI22_X1 U363 (.A1(n377),
	.A2(n376),
	.B1(n395),
	.B2(n458),
	.ZN(n172));
   OAI22_X1 U365 (.A1(n404),
	.A2(n405),
	.B1(FE_OFN0_n372),
	.B2(n406),
	.ZN(n162));
   NAND2_X1 U367 (.A1(n389),
	.A2(n442),
	.ZN(n388));
   OAI21_X1 U370 (.A(n441),
	.B1(n466),
	.B2(n388),
	.ZN(n117));
   OAI22_X1 U372 (.A1(n414),
	.A2(n388),
	.B1(n389),
	.B2(n415),
	.ZN(n151));
   OR3_X1 U373 (.A1(n389),
	.A2(b[0]),
	.A3(n466),
	.ZN(n441));
   NAND2_X1 U375 (.A1(a[1]),
	.A2(n458),
	.ZN(n376));
   XNOR2_X1 U377 (.A(b[3]),
	.B(a[1]),
	.ZN(n395));
   XNOR2_X1 U379 (.A(b[2]),
	.B(a[1]),
	.ZN(n377));
   NOR3_X1 U382 (.A1(FE_OFN0_n372),
	.A2(b[0]),
	.A3(n463),
	.ZN(n371));
   OAI22_X1 U384 (.A1(b[1]),
	.A2(n376),
	.B1(n377),
	.B2(n458),
	.ZN(n375));
   INV_X1 U386 (.A(b[0]),
	.ZN(n475));
   INV_X1 U388 (.A(a[3]),
	.ZN(n463));
   XNOR2_X1 U391 (.A(b[4]),
	.B(a[1]),
	.ZN(n396));
   INV_X1 U393 (.A(a[0]),
	.ZN(n458));
   INV_X1 U394 (.A(b[1]),
	.ZN(n476));
   XNOR2_X1 U396 (.A(b[6]),
	.B(a[1]),
	.ZN(n398));
   XNOR2_X1 U398 (.A(b[5]),
	.B(a[1]),
	.ZN(n397));
   INV_X1 U400 (.A(a[5]),
	.ZN(n466));
   NAND2_X1 U402 (.A1(n384),
	.A2(n444),
	.ZN(n383));
   OAI21_X1 U404 (.A(n443),
	.B1(n470),
	.B2(n383),
	.ZN(n116));
   OAI22_X1 U406 (.A1(n424),
	.A2(n383),
	.B1(n384),
	.B2(n425),
	.ZN(n140));
   OR3_X1 U408 (.A1(n384),
	.A2(b[0]),
	.A3(n470),
	.ZN(n443));
   XNOR2_X1 U410 (.A(b[7]),
	.B(a[1]),
	.ZN(n399));
   NAND2_X1 U413 (.A1(n472),
	.A2(n446),
	.ZN(n393));
   OAI21_X1 U414 (.A(n445),
	.B1(n474),
	.B2(n393),
	.ZN(n115));
   OAI22_X1 U415 (.A1(n432),
	.A2(n393),
	.B1(n472),
	.B2(n433),
	.ZN(n129));
   XNOR2_X1 U417 (.A(b[8]),
	.B(a[1]),
	.ZN(n400));
   INV_X1 U418 (.A(a[7]),
	.ZN(n470));
   XNOR2_X1 U419 (.A(b[9]),
	.B(a[1]),
	.ZN(n401));
   INV_X1 U421 (.A(a[10]),
	.ZN(n474));
   XNOR2_X1 U423 (.A(b[10]),
	.B(a[1]),
	.ZN(n402));
endmodule

module iir_DW_mult_tc_0 (
	a, 
	b, 
	product);
   input [10:0] a;
   input [10:0] b;
   output [21:0] product;

   // Internal wires
   wire FE_OFN1_n370;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n115;
   wire n116;
   wire n117;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n160;
   wire n161;
   wire n162;
   wire n165;
   wire n166;
   wire n167;
   wire n168;
   wire n169;
   wire n170;
   wire n171;
   wire n172;
   wire n357;
   wire n358;
   wire n359;
   wire n360;
   wire n361;
   wire n362;
   wire n363;
   wire n364;
   wire n365;
   wire n366;
   wire n367;
   wire n368;
   wire n369;
   wire n370;
   wire n371;
   wire n372;
   wire n373;
   wire n374;
   wire n375;
   wire n376;
   wire n377;
   wire n378;
   wire n379;
   wire n380;
   wire n381;
   wire n382;
   wire n383;
   wire n384;
   wire n385;
   wire n386;
   wire n387;
   wire n388;
   wire n389;
   wire n390;
   wire n391;
   wire n392;
   wire n393;
   wire n394;
   wire n395;
   wire n396;
   wire n397;
   wire n398;
   wire n399;
   wire n400;
   wire n401;
   wire n402;
   wire n403;
   wire n404;
   wire n405;
   wire n406;
   wire n407;
   wire n408;
   wire n409;
   wire n410;
   wire n411;
   wire n412;
   wire n413;
   wire n414;
   wire n415;
   wire n416;
   wire n417;
   wire n418;
   wire n419;
   wire n420;
   wire n421;
   wire n422;
   wire n423;
   wire n424;
   wire n425;
   wire n426;
   wire n427;
   wire n428;
   wire n429;
   wire n430;
   wire n431;
   wire n432;
   wire n433;
   wire n434;
   wire n435;
   wire n436;
   wire n437;
   wire n438;
   wire n439;
   wire n440;
   wire n441;
   wire n442;
   wire n443;
   wire n444;
   wire n446;
   wire n447;
   wire n448;
   wire n449;
   wire n450;
   wire n451;
   wire n452;
   wire n453;
   wire n454;
   wire n455;
   wire n456;
   wire n457;
   wire n458;
   wire n459;
   wire n460;
   wire n461;
   wire n462;
   wire n463;
   wire n464;
   wire n465;
   wire n466;
   wire n467;
   wire n468;
   wire n469;
   wire n470;
   wire n471;
   wire n472;
   wire n473;
   wire n474;

   OAI21_X1 FE_RC_17_0 (.A(n384),
	.B1(n458),
	.B2(n459),
	.ZN(n153));
   AOI21_X1 FE_RC_12_0 (.A(n390),
	.B1(n382),
	.B2(n381),
	.ZN(n429));
   AOI21_X1 FE_RC_11_0 (.A(n388),
	.B1(n387),
	.B2(n386),
	.ZN(n421));
   AOI21_X1 FE_RC_10_0 (.A(n400),
	.B1(n456),
	.B2(n374),
	.ZN(n401));
   CLKBUF_X1 FE_OFC1_n370 (.A(n370),
	.Z(FE_OFN1_n370));
   FA_X1 U3 (.A(n22),
	.B(n21),
	.CI(n3),
	.S(product[18]));
   FA_X1 U4 (.A(n24),
	.B(n23),
	.CI(n4),
	.CO(n3),
	.S(product[17]));
   FA_X1 U5 (.A(n25),
	.B(n28),
	.CI(n5),
	.CO(n4),
	.S(product[16]));
   FA_X1 U6 (.A(n29),
	.B(n32),
	.CI(n6),
	.CO(n5),
	.S(product[15]));
   FA_X1 U7 (.A(n33),
	.B(n38),
	.CI(n7),
	.CO(n6),
	.S(product[14]));
   FA_X1 U8 (.A(n39),
	.B(n44),
	.CI(n8),
	.CO(n7),
	.S(product[13]));
   FA_X1 U9 (.A(n45),
	.B(n52),
	.CI(n9),
	.CO(n8),
	.S(product[12]));
   FA_X1 U22 (.A(n121),
	.B(n26),
	.CI(n467),
	.CO(n22),
	.S(n23));
   FA_X1 U23 (.A(n466),
	.B(n122),
	.CI(n30),
	.CO(n24),
	.S(n25));
   FA_X1 U25 (.A(n34),
	.B(n123),
	.CI(n31),
	.CO(n28),
	.S(n29));
   FA_X1 U26 (.A(n132),
	.B(n36),
	.CI(n463),
	.CO(n30),
	.S(n31));
   FA_X1 U27 (.A(n35),
	.B(n42),
	.CI(n40),
	.CO(n32),
	.S(n33));
   FA_X1 U28 (.A(n124),
	.B(n133),
	.CI(n462),
	.CO(n34),
	.S(n35));
   FA_X1 U30 (.A(n46),
	.B(n43),
	.CI(n41),
	.CO(n38),
	.S(n39));
   FA_X1 U31 (.A(n457),
	.B(n143),
	.CI(n48),
	.CO(n40),
	.S(n41));
   FA_X1 U32 (.A(n134),
	.B(n125),
	.CI(n153),
	.CO(n42),
	.S(n43));
   FA_X1 U33 (.A(n54),
	.B(n49),
	.CI(n47),
	.CO(n44),
	.S(n45));
   FA_X1 U34 (.A(n58),
	.B(n51),
	.CI(n56),
	.CO(n46),
	.S(n47));
   FA_X1 U35 (.A(n135),
	.B(n126),
	.CI(n144),
	.CO(n48),
	.S(n49));
   FA_X1 U37 (.A(n62),
	.B(n57),
	.CI(n55),
	.CO(n52),
	.S(n53));
   FA_X1 U38 (.A(n59),
	.B(n66),
	.CI(n64),
	.CO(n54),
	.S(n55));
   FA_X1 U39 (.A(n145),
	.B(n127),
	.CI(n455),
	.CO(n56),
	.S(n57));
   FA_X1 U42 (.A(n70),
	.B(n65),
	.CI(n63),
	.CO(n60),
	.S(n61));
   FA_X1 U43 (.A(n67),
	.B(n74),
	.CI(n72),
	.CO(n62),
	.S(n63));
   FA_X1 U44 (.A(n155),
	.B(n146),
	.CI(n165),
	.CO(n64),
	.S(n65));
   HA_X1 U45 (.A(n128),
	.B(n137),
	.CO(n66),
	.S(n67));
   FA_X1 U46 (.A(n73),
	.B(n78),
	.CI(n71),
	.CO(n68),
	.S(n69));
   FA_X1 U47 (.A(n75),
	.B(n166),
	.CI(n80),
	.CO(n70),
	.S(n71));
   FA_X1 U48 (.A(n138),
	.B(n147),
	.CI(n156),
	.CO(n72),
	.S(n73));
   HA_X1 U49 (.A(n115),
	.B(n129),
	.CO(n74),
	.S(n75));
   FA_X1 U50 (.A(n81),
	.B(n84),
	.CI(n79),
	.CO(n76),
	.S(n77));
   FA_X1 U51 (.A(n139),
	.B(n157),
	.CI(n86),
	.CO(n78),
	.S(n79));
   FA_X1 U52 (.A(n148),
	.B(n130),
	.CI(n167),
	.CO(n80),
	.S(n81));
   FA_X1 U53 (.A(n90),
	.B(n87),
	.CI(n85),
	.CO(n82),
	.S(n83));
   FA_X1 U54 (.A(n149),
	.B(n168),
	.CI(n158),
	.CO(n84),
	.S(n85));
   HA_X1 U55 (.A(n116),
	.B(n140),
	.CO(n86),
	.S(n87));
   FA_X1 U56 (.A(n94),
	.B(n150),
	.CI(n91),
	.CO(n88),
	.S(n89));
   FA_X1 U57 (.A(n169),
	.B(n141),
	.CI(n159),
	.CO(n90),
	.S(n91));
   FA_X1 U58 (.A(n160),
	.B(n170),
	.CI(n95),
	.CO(n92),
	.S(n93));
   HA_X1 U59 (.A(n117),
	.B(n151),
	.CO(n94),
	.S(n95));
   FA_X1 U60 (.A(n171),
	.B(n152),
	.CI(n161),
	.CO(n96),
	.S(n97));
   HA_X1 U61 (.A(n162),
	.B(n172),
	.CO(n98),
	.S(n99));
   XNOR2_X2 U279 (.A(a[4]),
	.B(a[3]),
	.ZN(n387));
   XNOR2_X2 U280 (.A(a[6]),
	.B(a[5]),
	.ZN(n382));
   MUX2_X1 U292 (.A(n371),
	.B(n372),
	.S(b[0]),
	.Z(n367));
   NAND3_X1 U294 (.A1(n373),
	.A2(n474),
	.A3(a[1]),
	.ZN(n371));
   XOR2_X1 U296 (.A(n376),
	.B(n377),
	.Z(n59));
   XOR2_X1 U301 (.A(b[9]),
	.B(a[3]),
	.Z(n378));
   XOR2_X1 U305 (.A(b[10]),
	.B(a[10]),
	.Z(n357));
   XOR2_X1 U326 (.A(n473),
	.B(a[3]),
	.Z(n402));
   XOR2_X1 U328 (.A(n474),
	.B(a[3]),
	.Z(n404));
   XOR2_X1 U330 (.A(b[2]),
	.B(n461),
	.Z(n405));
   XOR2_X1 U332 (.A(b[3]),
	.B(n461),
	.Z(n406));
   XOR2_X1 U334 (.A(b[4]),
	.B(n461),
	.Z(n407));
   XOR2_X1 U336 (.A(b[5]),
	.B(n461),
	.Z(n408));
   XOR2_X1 U338 (.A(b[6]),
	.B(n461),
	.Z(n409));
   XOR2_X1 U340 (.A(b[8]),
	.B(n461),
	.Z(n379));
   XOR2_X1 U341 (.A(b[7]),
	.B(n461),
	.Z(n410));
   XOR2_X1 U344 (.A(a[3]),
	.B(a[2]),
	.Z(n411));
   XOR2_X1 U346 (.A(b[10]),
	.B(a[3]),
	.Z(n384));
   XOR2_X1 U349 (.A(n473),
	.B(a[5]),
	.Z(n412));
   XOR2_X1 U351 (.A(n474),
	.B(a[5]),
	.Z(n413));
   XOR2_X1 U353 (.A(b[2]),
	.B(n464),
	.Z(n414));
   XOR2_X1 U355 (.A(b[3]),
	.B(n464),
	.Z(n415));
   XOR2_X1 U357 (.A(b[4]),
	.B(n464),
	.Z(n416));
   XOR2_X1 U359 (.A(b[5]),
	.B(n464),
	.Z(n417));
   XOR2_X1 U361 (.A(b[6]),
	.B(n464),
	.Z(n418));
   XOR2_X1 U363 (.A(b[7]),
	.B(n464),
	.Z(n419));
   XOR2_X1 U365 (.A(b[9]),
	.B(n464),
	.Z(n385));
   XOR2_X1 U366 (.A(b[8]),
	.B(n464),
	.Z(n420));
   XOR2_X1 U368 (.A(b[10]),
	.B(n464),
	.Z(n388));
   XOR2_X1 U371 (.A(n473),
	.B(a[7]),
	.Z(n422));
   XOR2_X1 U373 (.A(n474),
	.B(a[7]),
	.Z(n423));
   XOR2_X1 U375 (.A(b[2]),
	.B(n468),
	.Z(n424));
   XOR2_X1 U377 (.A(b[4]),
	.B(n468),
	.Z(n380));
   XOR2_X1 U378 (.A(b[3]),
	.B(n468),
	.Z(n425));
   XOR2_X1 U380 (.A(b[5]),
	.B(n468),
	.Z(n383));
   XOR2_X1 U382 (.A(b[6]),
	.B(n468),
	.Z(n426));
   XOR2_X1 U384 (.A(b[7]),
	.B(n468),
	.Z(n427));
   XOR2_X1 U386 (.A(b[9]),
	.B(n468),
	.Z(n389));
   XOR2_X1 U387 (.A(b[8]),
	.B(n468),
	.Z(n428));
   XOR2_X1 U389 (.A(b[10]),
	.B(n468),
	.Z(n390));
   XOR2_X1 U392 (.A(n473),
	.B(a[10]),
	.Z(n430));
   XOR2_X1 U394 (.A(n474),
	.B(a[10]),
	.Z(n431));
   XOR2_X1 U396 (.A(b[2]),
	.B(n472),
	.Z(n432));
   XOR2_X1 U398 (.A(b[3]),
	.B(n472),
	.Z(n433));
   XOR2_X1 U400 (.A(b[4]),
	.B(n472),
	.Z(n434));
   XOR2_X1 U402 (.A(b[5]),
	.B(n472),
	.Z(n435));
   XOR2_X1 U404 (.A(b[6]),
	.B(n472),
	.Z(n436));
   XOR2_X1 U406 (.A(b[7]),
	.B(n472),
	.Z(n437));
   XOR2_X1 U408 (.A(b[9]),
	.B(n472),
	.Z(n392));
   XOR2_X1 U409 (.A(b[8]),
	.B(n472),
	.Z(n438));
   XOR2_X1 U413 (.A(a[5]),
	.B(a[4]),
	.Z(n440));
   XOR2_X1 U417 (.A(a[7]),
	.B(a[6]),
	.Z(n442));
   NAND3_X1 U419 (.A1(n358),
	.A2(n473),
	.A3(a[10]),
	.ZN(n443));
   XOR2_X1 U421 (.A(a[10]),
	.B(a[8]),
	.Z(n444));
   XOR2_X1 U422 (.A(a[8]),
	.B(a[7]),
	.Z(n358));
   XNOR2_X1 U250 (.A(a[2]),
	.B(a[1]),
	.ZN(n370));
   AOI222_X1 U251 (.A1(n360),
	.A2(n61),
	.B1(n360),
	.B2(n68),
	.C1(n68),
	.C2(n61),
	.ZN(n359));
   OAI222_X1 U252 (.A1(n361),
	.A2(n453),
	.B1(n361),
	.B2(n451),
	.C1(n451),
	.C2(n453),
	.ZN(n360));
   INV_X1 U253 (.A(n76),
	.ZN(n451));
   INV_X1 U254 (.A(n69),
	.ZN(n453));
   OAI222_X1 U255 (.A1(n359),
	.A2(n454),
	.B1(n359),
	.B2(n452),
	.C1(n452),
	.C2(n454),
	.ZN(n9));
   INV_X1 U256 (.A(n60),
	.ZN(n452));
   INV_X1 U257 (.A(n53),
	.ZN(n454));
   AOI222_X1 U258 (.A1(n362),
	.A2(n77),
	.B1(n362),
	.B2(n82),
	.C1(n82),
	.C2(n77),
	.ZN(n361));
   OAI222_X1 U259 (.A1(n363),
	.A2(n449),
	.B1(n363),
	.B2(n450),
	.C1(n450),
	.C2(n449),
	.ZN(n362));
   INV_X1 U260 (.A(n88),
	.ZN(n450));
   INV_X1 U261 (.A(n83),
	.ZN(n449));
   NAND2_X1 U262 (.A1(n465),
	.A2(n377),
	.ZN(n58));
   INV_X1 U263 (.A(n376),
	.ZN(n465));
   AOI222_X1 U264 (.A1(n364),
	.A2(n89),
	.B1(n364),
	.B2(n92),
	.C1(n92),
	.C2(n89),
	.ZN(n363));
   OAI222_X1 U265 (.A1(n365),
	.A2(n448),
	.B1(n365),
	.B2(n447),
	.C1(n447),
	.C2(n448),
	.ZN(n364));
   INV_X1 U266 (.A(n96),
	.ZN(n447));
   INV_X1 U267 (.A(n93),
	.ZN(n448));
   INV_X1 U268 (.A(n99),
	.ZN(n446));
   NOR2_X1 U269 (.A1(n387),
	.A2(n473),
	.ZN(n152));
   OAI22_X1 U270 (.A1(n393),
	.A2(n374),
	.B1(n394),
	.B2(n456),
	.ZN(n171));
   OAI22_X1 U271 (.A1(n404),
	.A2(n403),
	.B1(FE_OFN1_n370),
	.B2(n405),
	.ZN(n161));
   INV_X1 U272 (.A(n403),
	.ZN(n459));
   OAI22_X1 U273 (.A1(n394),
	.A2(n374),
	.B1(n395),
	.B2(n456),
	.ZN(n170));
   OAI22_X1 U274 (.A1(n405),
	.A2(n403),
	.B1(FE_OFN1_n370),
	.B2(n406),
	.ZN(n160));
   OAI22_X1 U275 (.A1(n413),
	.A2(n386),
	.B1(n387),
	.B2(n414),
	.ZN(n150));
   NOR2_X1 U276 (.A1(n382),
	.A2(n473),
	.ZN(n141));
   OAI22_X1 U277 (.A1(n395),
	.A2(n374),
	.B1(n396),
	.B2(n456),
	.ZN(n169));
   OAI22_X1 U278 (.A1(n406),
	.A2(n403),
	.B1(FE_OFN1_n370),
	.B2(n407),
	.ZN(n159));
   INV_X1 U281 (.A(FE_OFN1_n370),
	.ZN(n458));
   NAND2_X1 U282 (.A1(n458),
	.A2(n373),
	.ZN(n372));
   OAI22_X1 U283 (.A1(n396),
	.A2(n374),
	.B1(n397),
	.B2(n456),
	.ZN(n168));
   OAI22_X1 U284 (.A1(n414),
	.A2(n386),
	.B1(n387),
	.B2(n415),
	.ZN(n149));
   OAI22_X1 U285 (.A1(n407),
	.A2(n403),
	.B1(FE_OFN1_n370),
	.B2(n408),
	.ZN(n158));
   OAI22_X1 U286 (.A1(n423),
	.A2(n381),
	.B1(n382),
	.B2(n424),
	.ZN(n139));
   OAI22_X1 U287 (.A1(n408),
	.A2(n403),
	.B1(FE_OFN1_n370),
	.B2(n409),
	.ZN(n157));
   NOR2_X1 U288 (.A1(n470),
	.A2(n473),
	.ZN(n130));
   OAI22_X1 U289 (.A1(n397),
	.A2(n374),
	.B1(n398),
	.B2(n456),
	.ZN(n167));
   OAI22_X1 U290 (.A1(n415),
	.A2(n386),
	.B1(n387),
	.B2(n416),
	.ZN(n148));
   OAI22_X1 U291 (.A1(n398),
	.A2(n374),
	.B1(n399),
	.B2(n456),
	.ZN(n166));
   OAI22_X1 U293 (.A1(n424),
	.A2(n381),
	.B1(n382),
	.B2(n425),
	.ZN(n138));
   OAI22_X1 U295 (.A1(n416),
	.A2(n386),
	.B1(n387),
	.B2(n417),
	.ZN(n147));
   OAI22_X1 U297 (.A1(n409),
	.A2(n403),
	.B1(FE_OFN1_n370),
	.B2(n410),
	.ZN(n156));
   INV_X1 U298 (.A(n358),
	.ZN(n470));
   OAI22_X1 U299 (.A1(n431),
	.A2(n391),
	.B1(n470),
	.B2(n432),
	.ZN(n128));
   OAI22_X1 U300 (.A1(n425),
	.A2(n381),
	.B1(n382),
	.B2(n380),
	.ZN(n137));
   AOI22_X1 U302 (.A1(n460),
	.A2(n459),
	.B1(n458),
	.B2(n378),
	.ZN(n377));
   INV_X1 U303 (.A(n379),
	.ZN(n460));
   OAI22_X1 U304 (.A1(n399),
	.A2(n374),
	.B1(n400),
	.B2(n456),
	.ZN(n165));
   OAI22_X1 U306 (.A1(n417),
	.A2(n386),
	.B1(n387),
	.B2(n418),
	.ZN(n146));
   OAI22_X1 U307 (.A1(n410),
	.A2(n403),
	.B1(FE_OFN1_n370),
	.B2(n379),
	.ZN(n155));
   OAI22_X1 U308 (.A1(n380),
	.A2(n381),
	.B1(n382),
	.B2(n383),
	.ZN(n376));
   INV_X1 U309 (.A(n401),
	.ZN(n455));
   OAI22_X1 U310 (.A1(n432),
	.A2(n391),
	.B1(n470),
	.B2(n433),
	.ZN(n127));
   OAI22_X1 U311 (.A1(n418),
	.A2(n386),
	.B1(n387),
	.B2(n419),
	.ZN(n145));
   AOI22_X1 U312 (.A1(n378),
	.A2(n459),
	.B1(n458),
	.B2(n384),
	.ZN(n51));
   OAI22_X1 U314 (.A1(n420),
	.A2(n386),
	.B1(n387),
	.B2(n385),
	.ZN(n143));
   INV_X1 U315 (.A(n51),
	.ZN(n457));
   OAI22_X1 U316 (.A1(n433),
	.A2(n391),
	.B1(n470),
	.B2(n434),
	.ZN(n126));
   OAI22_X1 U317 (.A1(n383),
	.A2(n381),
	.B1(n382),
	.B2(n426),
	.ZN(n135));
   OAI22_X1 U318 (.A1(n419),
	.A2(n386),
	.B1(n387),
	.B2(n420),
	.ZN(n144));
   OAI22_X1 U319 (.A1(n434),
	.A2(n391),
	.B1(n470),
	.B2(n435),
	.ZN(n125));
   OAI22_X1 U320 (.A1(n426),
	.A2(n381),
	.B1(n382),
	.B2(n427),
	.ZN(n134));
   OAI22_X1 U322 (.A1(n385),
	.A2(n386),
	.B1(n387),
	.B2(n388),
	.ZN(n36));
   OAI22_X1 U323 (.A1(n435),
	.A2(n391),
	.B1(n470),
	.B2(n436),
	.ZN(n124));
   OAI22_X1 U324 (.A1(n427),
	.A2(n381),
	.B1(n382),
	.B2(n428),
	.ZN(n133));
   INV_X1 U325 (.A(n36),
	.ZN(n462));
   OAI22_X1 U327 (.A1(n436),
	.A2(n391),
	.B1(n470),
	.B2(n437),
	.ZN(n123));
   OAI22_X1 U329 (.A1(n428),
	.A2(n381),
	.B1(n382),
	.B2(n389),
	.ZN(n132));
   INV_X1 U331 (.A(n421),
	.ZN(n463));
   OAI22_X1 U335 (.A1(n437),
	.A2(n391),
	.B1(n470),
	.B2(n438),
	.ZN(n122));
   INV_X1 U337 (.A(n26),
	.ZN(n466));
   OAI22_X1 U339 (.A1(n389),
	.A2(n381),
	.B1(n382),
	.B2(n390),
	.ZN(n26));
   OAI22_X1 U342 (.A1(n438),
	.A2(n391),
	.B1(n470),
	.B2(n392),
	.ZN(n121));
   INV_X1 U343 (.A(n429),
	.ZN(n467));
   INV_X1 U347 (.A(n391),
	.ZN(n469));
   AOI222_X1 U348 (.A1(n366),
	.A2(n97),
	.B1(n366),
	.B2(n98),
	.C1(n98),
	.C2(n97),
	.ZN(n365));
   OAI222_X1 U350 (.A1(n367),
	.A2(n446),
	.B1(n368),
	.B2(n367),
	.C1(n368),
	.C2(n446),
	.ZN(n366));
   AOI21_X1 U352 (.A(n369),
	.B1(a[3]),
	.B2(n459),
	.ZN(n368));
   NAND2_X1 U354 (.A1(FE_OFN1_n370),
	.A2(n411),
	.ZN(n403));
   OAI22_X1 U356 (.A1(n375),
	.A2(n374),
	.B1(n393),
	.B2(n456),
	.ZN(n172));
   OAI22_X1 U358 (.A1(n402),
	.A2(n403),
	.B1(FE_OFN1_n370),
	.B2(n404),
	.ZN(n162));
   AOI22_X1 U360 (.A1(n471),
	.A2(n469),
	.B1(n358),
	.B2(n357),
	.ZN(n21));
   INV_X1 U362 (.A(n392),
	.ZN(n471));
   NAND2_X1 U364 (.A1(n387),
	.A2(n440),
	.ZN(n386));
   OAI21_X1 U367 (.A(n439),
	.B1(n464),
	.B2(n386),
	.ZN(n117));
   OAI22_X1 U369 (.A1(n412),
	.A2(n386),
	.B1(n387),
	.B2(n413),
	.ZN(n151));
   OR3_X1 U370 (.A1(n387),
	.A2(b[0]),
	.A3(n464),
	.ZN(n439));
   NAND2_X1 U372 (.A1(a[1]),
	.A2(n456),
	.ZN(n374));
   XNOR2_X1 U374 (.A(b[3]),
	.B(a[1]),
	.ZN(n393));
   XNOR2_X1 U376 (.A(b[2]),
	.B(a[1]),
	.ZN(n375));
   NOR3_X1 U379 (.A1(FE_OFN1_n370),
	.A2(b[0]),
	.A3(n461),
	.ZN(n369));
   OAI22_X1 U381 (.A1(b[1]),
	.A2(n374),
	.B1(n375),
	.B2(n456),
	.ZN(n373));
   INV_X1 U383 (.A(a[3]),
	.ZN(n461));
   XNOR2_X1 U385 (.A(b[4]),
	.B(a[1]),
	.ZN(n394));
   INV_X1 U388 (.A(a[0]),
	.ZN(n456));
   INV_X1 U390 (.A(b[0]),
	.ZN(n473));
   INV_X1 U391 (.A(b[1]),
	.ZN(n474));
   XNOR2_X1 U393 (.A(b[6]),
	.B(a[1]),
	.ZN(n396));
   XNOR2_X1 U395 (.A(b[5]),
	.B(a[1]),
	.ZN(n395));
   INV_X1 U397 (.A(a[5]),
	.ZN(n464));
   NAND2_X1 U399 (.A1(n382),
	.A2(n442),
	.ZN(n381));
   OAI21_X1 U401 (.A(n441),
	.B1(n468),
	.B2(n381),
	.ZN(n116));
   OAI22_X1 U403 (.A1(n422),
	.A2(n381),
	.B1(n382),
	.B2(n423),
	.ZN(n140));
   OR3_X1 U405 (.A1(n382),
	.A2(b[0]),
	.A3(n468),
	.ZN(n441));
   XNOR2_X1 U407 (.A(b[7]),
	.B(a[1]),
	.ZN(n397));
   NAND2_X1 U410 (.A1(n470),
	.A2(n444),
	.ZN(n391));
   OAI21_X1 U411 (.A(n443),
	.B1(n472),
	.B2(n391),
	.ZN(n115));
   OAI22_X1 U412 (.A1(n430),
	.A2(n391),
	.B1(n470),
	.B2(n431),
	.ZN(n129));
   XNOR2_X1 U414 (.A(b[8]),
	.B(a[1]),
	.ZN(n398));
   INV_X1 U415 (.A(a[7]),
	.ZN(n468));
   XNOR2_X1 U416 (.A(b[9]),
	.B(a[1]),
	.ZN(n399));
   INV_X1 U418 (.A(a[10]),
	.ZN(n472));
   XNOR2_X1 U420 (.A(b[10]),
	.B(a[1]),
	.ZN(n400));
endmodule

module SNPS_CLOCK_GATE_HIGH_iir_0 (
	CLK, 
	EN, 
	ENCLK, 
	TE);
   input CLK;
   input EN;
   output ENCLK;
   input TE;

   CLKGATETST_X4 latch (.CK(CLK),
	.E(EN),
	.SE(TE),
	.GCK(ENCLK));
endmodule

module iir (
	CLK, 
	RST_N, 
	VIN, 
	A1, 
	A1_2, 
	B0, 
	B1, 
	X, 
	Y, 
	VOUT);
   input CLK;
   input RST_N;
   input VIN;
   input [9:0] A1;
   input [9:0] A1_2;
   input [9:0] B0;
   input [9:0] B1;
   input [9:0] X;
   output [9:0] Y;
   output VOUT;

   // Internal wires
   wire CTS_1;
   wire FE_OFN3_RST_N;
   wire n84;
   wire n91;
   wire n108;
   wire n187;
   wire n195;
   wire n208;
   wire n371;
   wire n429;
   wire n430;
   wire n442;
   wire n443;
   wire n444;
   wire n445;
   wire SYNOPSYS_UNCONNECTED_1;
   wire SYNOPSYS_UNCONNECTED_2;
   wire SYNOPSYS_UNCONNECTED_3;
   wire SYNOPSYS_UNCONNECTED_4;
   wire SYNOPSYS_UNCONNECTED_5;
   wire SYNOPSYS_UNCONNECTED_6;
   wire SYNOPSYS_UNCONNECTED_7;
   wire SYNOPSYS_UNCONNECTED_8;
   wire SYNOPSYS_UNCONNECTED_9;
   wire SYNOPSYS_UNCONNECTED_10;
   wire SYNOPSYS_UNCONNECTED_11;
   wire SYNOPSYS_UNCONNECTED_12;
   wire SYNOPSYS_UNCONNECTED_13;
   wire SYNOPSYS_UNCONNECTED_14;
   wire SYNOPSYS_UNCONNECTED_15;
   wire SYNOPSYS_UNCONNECTED_16;
   wire SYNOPSYS_UNCONNECTED_17;
   wire SYNOPSYS_UNCONNECTED_18;
   wire SYNOPSYS_UNCONNECTED_19;
   wire SYNOPSYS_UNCONNECTED_20;
   wire SYNOPSYS_UNCONNECTED_21;
   wire SYNOPSYS_UNCONNECTED_22;
   wire SYNOPSYS_UNCONNECTED_23;
   wire SYNOPSYS_UNCONNECTED_24;
   wire SYNOPSYS_UNCONNECTED_25;
   wire SYNOPSYS_UNCONNECTED_26;
   wire SYNOPSYS_UNCONNECTED_27;
   wire SYNOPSYS_UNCONNECTED_28;
   wire SYNOPSYS_UNCONNECTED_29;
   wire SYNOPSYS_UNCONNECTED_30;
   wire SYNOPSYS_UNCONNECTED_31;
   wire SYNOPSYS_UNCONNECTED_32;
   wire SYNOPSYS_UNCONNECTED_33;
   wire SYNOPSYS_UNCONNECTED_34;
   wire SYNOPSYS_UNCONNECTED_35;
   wire SYNOPSYS_UNCONNECTED_36;
   wire SYNOPSYS_UNCONNECTED_37;
   wire SYNOPSYS_UNCONNECTED_38;
   wire SYNOPSYS_UNCONNECTED_39;
   wire SYNOPSYS_UNCONNECTED_40;
   wire SYNOPSYS_UNCONNECTED_41;
   wire SYNOPSYS_UNCONNECTED_42;
   wire SYNOPSYS_UNCONNECTED_43;
   wire SYNOPSYS_UNCONNECTED_44;
   wire SYNOPSYS_UNCONNECTED_45;
   wire SYNOPSYS_UNCONNECTED_46;
   wire SYNOPSYS_UNCONNECTED_47;
   wire SYNOPSYS_UNCONNECTED_48;
   wire SYNOPSYS_UNCONNECTED_49;
   wire SYNOPSYS_UNCONNECTED_50;
   wire SYNOPSYS_UNCONNECTED_51;
   wire SYNOPSYS_UNCONNECTED_52;
   wire SYNOPSYS_UNCONNECTED_53;
   wire SYNOPSYS_UNCONNECTED_54;
   wire SYNOPSYS_UNCONNECTED_55;
   wire SYNOPSYS_UNCONNECTED_56;
   wire SYNOPSYS_UNCONNECTED_57;
   wire SYNOPSYS_UNCONNECTED_58;
   wire SYNOPSYS_UNCONNECTED_59;
   wire SYNOPSYS_UNCONNECTED_60;
   wire SYNOPSYS_UNCONNECTED_61;
   wire SYNOPSYS_UNCONNECTED_62;
   wire SYNOPSYS_UNCONNECTED_63;
   wire SYNOPSYS_UNCONNECTED_64;
   wire [9:0] a1_tmp;
   wire [9:0] b0_tmp;
   wire [9:0] b1_tmp;
   wire [9:0] a1_2_tmp;
   wire [9:3] x_o_tmp;
   wire [10:3] f1_i;
   wire [10:3] f1_o;
   wire [10:3] w_i;
   wire [10:0] w_o;
   wire [10:3] s_i;
   wire [10:0] s_o;
   wire [10:3] fb_i;
   wire [10:3] fb_o;
   wire [10:0] s2_o;
   wire [9:3] f3_i;
   wire [9:4] f3_o;
   wire [9:3] f2_i;
   wire [9:4] f2_o;
   wire [9:3] y_i;
   wire [9:4] add_287_carry;

   assign Y[2] = 1'b0 ;
   assign Y[1] = 1'b0 ;
   assign Y[0] = 1'b0 ;

   CLKBUF_X3 CTS_ccl_a_buf_00003 (.A(CLK),
	.Z(CTS_1));
   BUF_X4 FE_OFC3_RST_N (.A(RST_N),
	.Z(FE_OFN3_RST_N));
   DFFR_X1 count_vin_reg_2_ (.D(1'b1),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(n430));
   DFF_X1 VOUT_reg (.D(n187),
	.CK(CTS_1),
	.Q(VOUT),
	.QN(n108));
   DFFR_X1 A1_IN_REG_data_out_reg_0_ (.D(A1[0]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(a1_tmp[0]));
   DFFR_X1 A1_IN_REG_data_out_reg_1_ (.D(A1[1]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(a1_tmp[1]));
   DFFR_X1 A1_IN_REG_data_out_reg_2_ (.D(A1[2]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(a1_tmp[2]));
   DFFR_X1 A1_IN_REG_data_out_reg_3_ (.D(A1[3]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(a1_tmp[3]));
   DFFR_X1 A1_IN_REG_data_out_reg_4_ (.D(A1[4]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(a1_tmp[4]));
   DFFR_X1 A1_2_IN_REG_data_out_reg_0_ (.D(A1_2[0]),
	.RN(RST_N),
	.CK(CTS_1),
	.Q(a1_2_tmp[0]));
   DFFR_X1 A1_2_IN_REG_data_out_reg_1_ (.D(A1_2[1]),
	.RN(RST_N),
	.CK(CTS_1),
	.Q(a1_2_tmp[1]));
   DFFR_X1 A1_2_IN_REG_data_out_reg_2_ (.D(A1_2[2]),
	.RN(RST_N),
	.CK(CTS_1),
	.Q(a1_2_tmp[2]));
   DFFR_X1 A1_2_IN_REG_data_out_reg_3_ (.D(A1_2[3]),
	.RN(RST_N),
	.CK(CTS_1),
	.Q(a1_2_tmp[3]));
   DFFR_X1 A1_2_IN_REG_data_out_reg_4_ (.D(A1_2[4]),
	.RN(RST_N),
	.CK(CTS_1),
	.Q(a1_2_tmp[4]));
   DFFR_X1 A1_2_IN_REG_data_out_reg_5_ (.D(A1_2[5]),
	.RN(RST_N),
	.CK(CTS_1),
	.Q(a1_2_tmp[5]));
   DFFR_X1 A1_2_IN_REG_data_out_reg_6_ (.D(A1_2[6]),
	.RN(RST_N),
	.CK(CTS_1),
	.Q(a1_2_tmp[6]));
   DFFR_X1 A1_2_IN_REG_data_out_reg_7_ (.D(A1_2[7]),
	.RN(RST_N),
	.CK(CTS_1),
	.Q(a1_2_tmp[7]));
   DFFR_X1 A1_2_IN_REG_data_out_reg_8_ (.D(A1_2[8]),
	.RN(RST_N),
	.CK(CTS_1),
	.Q(a1_2_tmp[8]));
   DFFR_X1 A1_2_IN_REG_data_out_reg_9_ (.D(A1_2[9]),
	.RN(RST_N),
	.CK(CTS_1),
	.Q(a1_2_tmp[9]));
   DFFR_X1 IN_REG_data_out_reg_0_ (.D(X[0]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(n444));
   DFFR_X1 IN_REG_data_out_reg_1_ (.D(X[1]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(n443));
   DFFR_X1 IN_REG_data_out_reg_2_ (.D(X[2]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(n442));
   DFFR_X1 SW2_REG_data_out_reg_7_ (.D(s_i[7]),
	.RN(RST_N),
	.CK(n445),
	.Q(s_o[7]));
   DFFR_X1 SW2_REG_data_out_reg_8_ (.D(s_i[8]),
	.RN(RST_N),
	.CK(n445),
	.Q(s_o[8]));
   DFFR_X1 SW2_REG_data_out_reg_9_ (.D(s_i[9]),
	.RN(RST_N),
	.CK(n445),
	.Q(s_o[9]));
   DFFR_X1 SW2_REG_data_out_reg_10_ (.D(s_i[10]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(s_o[10]));
   DFFR_X1 OUT_REG_data_out_reg_8_ (.D(y_i[8]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(Y[8]));
   DFFR_X1 OUT_REG_data_out_reg_9_ (.D(y_i[9]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(Y[9]));
   FA_X1 add_287_U1_4 (.A(f3_o[4]),
	.B(f2_o[4]),
	.CI(add_287_carry[4]),
	.CO(add_287_carry[5]),
	.S(y_i[4]));
   FA_X1 add_287_U1_5 (.A(f3_o[5]),
	.B(f2_o[5]),
	.CI(add_287_carry[5]),
	.CO(add_287_carry[6]),
	.S(y_i[5]));
   FA_X1 add_287_U1_6 (.A(f3_o[6]),
	.B(f2_o[6]),
	.CI(add_287_carry[6]),
	.CO(add_287_carry[7]),
	.S(y_i[6]));
   FA_X1 add_287_U1_7 (.A(f3_o[7]),
	.B(f2_o[7]),
	.CI(add_287_carry[7]),
	.CO(add_287_carry[8]),
	.S(y_i[7]));
   FA_X1 add_287_U1_8 (.A(f3_o[8]),
	.B(f2_o[8]),
	.CI(add_287_carry[8]),
	.CO(add_287_carry[9]),
	.S(y_i[8]));
   FA_X1 add_287_U1_9 (.A(f3_o[9]),
	.B(f2_o[9]),
	.CI(add_287_carry[9]),
	.S(y_i[9]));
   DFFR_X1 SW1_REG_data_out_reg_7_ (.D(w_i[7]),
	.RN(RST_N),
	.CK(n445),
	.Q(w_o[7]));
   DFFR_X1 SW1_REG_data_out_reg_8_ (.D(w_i[8]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(w_o[8]));
   DFFR_X1 SW1_REG_data_out_reg_9_ (.D(w_i[9]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(w_o[9]));
   DFFR_X1 SW1_REG_data_out_reg_10_ (.D(w_i[10]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(w_o[10]));
   DFFR_X1 SW6_REG_data_out_reg_3_ (.D(f2_i[3]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.QN(n84));
   DFFR_X1 SW5_REG_data_out_reg_3_ (.D(f3_i[3]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.QN(n91));
   DFFR_X1 SW3_REG_data_out_reg_3_ (.D(fb_i[3]),
	.RN(RST_N),
	.CK(n445),
	.Q(fb_o[3]));
   DFFR_X1 SW0_REG_data_out_reg_3_ (.D(f1_i[3]),
	.RN(RST_N),
	.CK(n445),
	.Q(f1_o[3]));
   DFFR_X1 SW6_REG_data_out_reg_4_ (.D(f2_i[4]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(f2_o[4]));
   DFFR_X1 SW5_REG_data_out_reg_4_ (.D(f3_i[4]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(f3_o[4]));
   DFFR_X1 SW3_REG_data_out_reg_4_ (.D(fb_i[4]),
	.RN(RST_N),
	.CK(n445),
	.Q(fb_o[4]));
   DFFR_X1 SW0_REG_data_out_reg_4_ (.D(f1_i[4]),
	.RN(RST_N),
	.CK(n445),
	.Q(f1_o[4]));
   DFFR_X1 SW5_REG_data_out_reg_5_ (.D(f3_i[5]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(f3_o[5]));
   DFFR_X1 SW3_REG_data_out_reg_5_ (.D(fb_i[5]),
	.RN(RST_N),
	.CK(n445),
	.Q(fb_o[5]));
   DFFR_X1 SW6_REG_data_out_reg_5_ (.D(f2_i[5]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(f2_o[5]));
   DFFR_X1 SW0_REG_data_out_reg_5_ (.D(f1_i[5]),
	.RN(RST_N),
	.CK(n445),
	.Q(f1_o[5]));
   DFFR_X1 SW6_REG_data_out_reg_6_ (.D(f2_i[6]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(f2_o[6]));
   DFFR_X1 SW5_REG_data_out_reg_6_ (.D(f3_i[6]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(f3_o[6]));
   DFFR_X1 SW3_REG_data_out_reg_6_ (.D(fb_i[6]),
	.RN(RST_N),
	.CK(n445),
	.Q(fb_o[6]));
   DFFR_X1 SW0_REG_data_out_reg_6_ (.D(f1_i[6]),
	.RN(RST_N),
	.CK(n445),
	.Q(f1_o[6]));
   DFFR_X1 SW5_REG_data_out_reg_7_ (.D(f3_i[7]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(f3_o[7]));
   DFFR_X1 SW3_REG_data_out_reg_7_ (.D(fb_i[7]),
	.RN(RST_N),
	.CK(n445),
	.Q(fb_o[7]));
   DFFR_X1 SW6_REG_data_out_reg_7_ (.D(f2_i[7]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(f2_o[7]));
   DFFR_X1 SW0_REG_data_out_reg_7_ (.D(f1_i[7]),
	.RN(RST_N),
	.CK(n445),
	.Q(f1_o[7]));
   DFFR_X1 SW6_REG_data_out_reg_8_ (.D(f2_i[8]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(f2_o[8]));
   DFFR_X1 SW5_REG_data_out_reg_8_ (.D(f3_i[8]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(f3_o[8]));
   DFFR_X1 SW3_REG_data_out_reg_8_ (.D(fb_i[8]),
	.RN(RST_N),
	.CK(n445),
	.Q(fb_o[8]));
   DFFR_X1 SW0_REG_data_out_reg_8_ (.D(f1_i[8]),
	.RN(RST_N),
	.CK(n445),
	.Q(f1_o[8]));
   DFFR_X1 SW6_REG_data_out_reg_9_ (.D(f2_i[9]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(f2_o[9]));
   DFFR_X1 SW5_REG_data_out_reg_9_ (.D(f3_i[9]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(f3_o[9]));
   DFFR_X1 SW3_REG_data_out_reg_9_ (.D(fb_i[9]),
	.RN(RST_N),
	.CK(n445),
	.Q(fb_o[9]));
   DFFR_X1 SW0_REG_data_out_reg_10_ (.D(f1_i[10]),
	.RN(RST_N),
	.CK(n445),
	.Q(f1_o[10]));
   DFFR_X1 SW0_REG_data_out_reg_9_ (.D(f1_i[9]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(f1_o[9]));
   DFFR_X1 SW3_REG_data_out_reg_10_ (.D(fb_i[10]),
	.RN(RST_N),
	.CK(n445),
	.Q(fb_o[10]));
   XOR2_X1 U302 (.A(n91),
	.B(n84),
	.Z(y_i[3]));
   NAND3_X1 U303 (.A1(n195),
	.A2(n208),
	.A3(FE_OFN3_RST_N),
	.ZN(n371));
   iir_DW01_add_1 add_283 (.A(w_o),
	.B({ fb_o,
		1'b0,
		1'b0,
		1'b0 }),
	.CI(1'b0),
	.SUM({ s_i,
		SYNOPSYS_UNCONNECTED_1,
		SYNOPSYS_UNCONNECTED_2,
		SYNOPSYS_UNCONNECTED_3 }));
   iir_DW01_add_2 add_282 (.A({ f1_o,
		1'b0,
		1'b0,
		1'b0 }),
	.B({ x_o_tmp[9],
		x_o_tmp,
		n442,
		n443,
		n444 }),
	.CI(1'b0),
	.SUM({ w_i,
		SYNOPSYS_UNCONNECTED_4,
		SYNOPSYS_UNCONNECTED_5,
		SYNOPSYS_UNCONNECTED_6 }));
   iir_DW_mult_tc_3 mult_281 (.a({ a1_tmp[9],
		a1_tmp }),
	.b({ x_o_tmp[9],
		x_o_tmp,
		n442,
		n443,
		n444 }),
	.product({ SYNOPSYS_UNCONNECTED_7,
		SYNOPSYS_UNCONNECTED_8,
		f1_i,
		SYNOPSYS_UNCONNECTED_9,
		SYNOPSYS_UNCONNECTED_10,
		SYNOPSYS_UNCONNECTED_11,
		SYNOPSYS_UNCONNECTED_12,
		SYNOPSYS_UNCONNECTED_13,
		SYNOPSYS_UNCONNECTED_14,
		SYNOPSYS_UNCONNECTED_15,
		SYNOPSYS_UNCONNECTED_16,
		SYNOPSYS_UNCONNECTED_17,
		SYNOPSYS_UNCONNECTED_18,
		SYNOPSYS_UNCONNECTED_19,
		SYNOPSYS_UNCONNECTED_20 }));
   iir_DW_mult_tc_2 mult_285 (.a({ b0_tmp[9],
		b0_tmp }),
	.b(s_o),
	.product({ SYNOPSYS_UNCONNECTED_21,
		SYNOPSYS_UNCONNECTED_22,
		SYNOPSYS_UNCONNECTED_23,
		f3_i,
		SYNOPSYS_UNCONNECTED_24,
		SYNOPSYS_UNCONNECTED_25,
		SYNOPSYS_UNCONNECTED_26,
		SYNOPSYS_UNCONNECTED_27,
		SYNOPSYS_UNCONNECTED_28,
		SYNOPSYS_UNCONNECTED_29,
		SYNOPSYS_UNCONNECTED_30,
		SYNOPSYS_UNCONNECTED_31,
		SYNOPSYS_UNCONNECTED_32,
		SYNOPSYS_UNCONNECTED_33,
		SYNOPSYS_UNCONNECTED_34,
		SYNOPSYS_UNCONNECTED_35 }));
   iir_DW_mult_tc_1 mult_284 (.a({ a1_2_tmp[9],
		a1_2_tmp }),
	.b(s_o),
	.product({ SYNOPSYS_UNCONNECTED_36,
		SYNOPSYS_UNCONNECTED_37,
		fb_i,
		SYNOPSYS_UNCONNECTED_38,
		SYNOPSYS_UNCONNECTED_39,
		SYNOPSYS_UNCONNECTED_40,
		SYNOPSYS_UNCONNECTED_41,
		SYNOPSYS_UNCONNECTED_42,
		SYNOPSYS_UNCONNECTED_43,
		SYNOPSYS_UNCONNECTED_44,
		SYNOPSYS_UNCONNECTED_45,
		SYNOPSYS_UNCONNECTED_46,
		SYNOPSYS_UNCONNECTED_47,
		SYNOPSYS_UNCONNECTED_48,
		SYNOPSYS_UNCONNECTED_49 }));
   iir_DW_mult_tc_0 mult_286 (.a({ b1_tmp[9],
		b1_tmp }),
	.b(s2_o),
	.product({ SYNOPSYS_UNCONNECTED_50,
		SYNOPSYS_UNCONNECTED_51,
		SYNOPSYS_UNCONNECTED_52,
		f2_i,
		SYNOPSYS_UNCONNECTED_53,
		SYNOPSYS_UNCONNECTED_54,
		SYNOPSYS_UNCONNECTED_55,
		SYNOPSYS_UNCONNECTED_56,
		SYNOPSYS_UNCONNECTED_57,
		SYNOPSYS_UNCONNECTED_58,
		SYNOPSYS_UNCONNECTED_59,
		SYNOPSYS_UNCONNECTED_60,
		SYNOPSYS_UNCONNECTED_61,
		SYNOPSYS_UNCONNECTED_62,
		SYNOPSYS_UNCONNECTED_63,
		SYNOPSYS_UNCONNECTED_64 }));
   SNPS_CLOCK_GATE_HIGH_iir_0 clk_gate_SW3_REG_data_out_reg (.CLK(CLK),
	.EN(n208),
	.ENCLK(n445),
	.TE(1'b0));
   DFFR_X1 SW1_REG_data_out_reg_2_ (.D(n442),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(w_o[2]));
   DFFR_X1 SW1_REG_data_out_reg_1_ (.D(n443),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(w_o[1]));
   DFFR_X1 SW1_REG_data_out_reg_0_ (.D(n444),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(w_o[0]));
   DFFR_X1 count_vin_reg_1_ (.D(n430),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(n429));
   DFFR_X1 count_vin_reg_0_ (.D(n429),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(n195));
   DFFR_X1 SW2_REG_data_out_reg_2_ (.D(w_o[2]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(s_o[2]));
   DFFR_X1 SW2_REG_data_out_reg_1_ (.D(w_o[1]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(s_o[1]));
   DFFR_X1 SW2_REG_data_out_reg_0_ (.D(w_o[0]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(s_o[0]));
   DFFR_X1 OUT_REG_data_out_reg_3_ (.D(y_i[3]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(Y[3]));
   DFFR_X1 SW4_REG_data_out_reg_1_ (.D(s_o[1]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(s2_o[1]));
   DFFR_X1 SW2_REG_data_out_reg_3_ (.D(s_i[3]),
	.RN(RST_N),
	.CK(n445),
	.Q(s_o[3]));
   DFFR_X1 SW4_REG_data_out_reg_0_ (.D(s_o[0]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(s2_o[0]));
   DFFR_X1 SW1_REG_data_out_reg_3_ (.D(w_i[3]),
	.RN(RST_N),
	.CK(n445),
	.Q(w_o[3]));
   DFFR_X1 SW4_REG_data_out_reg_10_ (.D(s_o[10]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(s2_o[10]));
   DFFR_X1 SW4_REG_data_out_reg_9_ (.D(s_o[9]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(s2_o[9]));
   DFFR_X1 SW4_REG_data_out_reg_8_ (.D(s_o[8]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(s2_o[8]));
   DFFR_X1 SW4_REG_data_out_reg_7_ (.D(s_o[7]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(s2_o[7]));
   DFFR_X1 SW4_REG_data_out_reg_6_ (.D(s_o[6]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(s2_o[6]));
   DFFR_X1 SW4_REG_data_out_reg_5_ (.D(s_o[5]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(s2_o[5]));
   DFFR_X1 SW4_REG_data_out_reg_4_ (.D(s_o[4]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(s2_o[4]));
   DFFR_X1 SW4_REG_data_out_reg_3_ (.D(s_o[3]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(s2_o[3]));
   DFFR_X1 SW4_REG_data_out_reg_2_ (.D(s_o[2]),
	.RN(FE_OFN3_RST_N),
	.CK(n445),
	.Q(s2_o[2]));
   DFFR_X1 OUT_REG_data_out_reg_4_ (.D(y_i[4]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(Y[4]));
   DFFR_X1 SW2_REG_data_out_reg_4_ (.D(s_i[4]),
	.RN(RST_N),
	.CK(n445),
	.Q(s_o[4]));
   DFFR_X1 SW1_REG_data_out_reg_4_ (.D(w_i[4]),
	.RN(RST_N),
	.CK(n445),
	.Q(w_o[4]));
   DFFR_X1 OUT_REG_data_out_reg_5_ (.D(y_i[5]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(Y[5]));
   DFFR_X1 SW2_REG_data_out_reg_5_ (.D(s_i[5]),
	.RN(RST_N),
	.CK(n445),
	.Q(s_o[5]));
   DFFR_X1 SW1_REG_data_out_reg_5_ (.D(w_i[5]),
	.RN(RST_N),
	.CK(n445),
	.Q(w_o[5]));
   DFFR_X1 OUT_REG_data_out_reg_6_ (.D(y_i[6]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(Y[6]));
   DFFR_X1 SW2_REG_data_out_reg_6_ (.D(s_i[6]),
	.RN(RST_N),
	.CK(n445),
	.Q(s_o[6]));
   DFFR_X1 SW1_REG_data_out_reg_6_ (.D(w_i[6]),
	.RN(RST_N),
	.CK(n445),
	.Q(w_o[6]));
   DFFR_X1 OUT_REG_data_out_reg_7_ (.D(y_i[7]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(Y[7]));
   DFFR_X1 vin_d1_reg (.D(VIN),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(n208));
   DFFR_X1 IN_REG_data_out_reg_9_ (.D(X[9]),
	.RN(RST_N),
	.CK(CTS_1),
	.Q(x_o_tmp[9]));
   DFFR_X1 IN_REG_data_out_reg_8_ (.D(X[8]),
	.RN(RST_N),
	.CK(CTS_1),
	.Q(x_o_tmp[8]));
   DFFR_X1 IN_REG_data_out_reg_7_ (.D(X[7]),
	.RN(RST_N),
	.CK(CTS_1),
	.Q(x_o_tmp[7]));
   DFFR_X1 IN_REG_data_out_reg_6_ (.D(X[6]),
	.RN(RST_N),
	.CK(CTS_1),
	.Q(x_o_tmp[6]));
   DFFR_X1 IN_REG_data_out_reg_5_ (.D(X[5]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(x_o_tmp[5]));
   DFFR_X1 IN_REG_data_out_reg_4_ (.D(X[4]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(x_o_tmp[4]));
   DFFR_X1 IN_REG_data_out_reg_3_ (.D(X[3]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(x_o_tmp[3]));
   DFFR_X1 B1_IN_REG_data_out_reg_9_ (.D(B1[9]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(b1_tmp[9]));
   DFFR_X1 B1_IN_REG_data_out_reg_8_ (.D(B1[8]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(b1_tmp[8]));
   DFFR_X1 B1_IN_REG_data_out_reg_7_ (.D(B1[7]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(b1_tmp[7]));
   DFFR_X1 B1_IN_REG_data_out_reg_6_ (.D(B1[6]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(b1_tmp[6]));
   DFFR_X1 B1_IN_REG_data_out_reg_5_ (.D(B1[5]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(b1_tmp[5]));
   DFFR_X1 B1_IN_REG_data_out_reg_4_ (.D(B1[4]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(b1_tmp[4]));
   DFFR_X1 B1_IN_REG_data_out_reg_3_ (.D(B1[3]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(b1_tmp[3]));
   DFFR_X1 B1_IN_REG_data_out_reg_2_ (.D(B1[2]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(b1_tmp[2]));
   DFFR_X1 B1_IN_REG_data_out_reg_1_ (.D(B1[1]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(b1_tmp[1]));
   DFFR_X1 B1_IN_REG_data_out_reg_0_ (.D(B1[0]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(b1_tmp[0]));
   DFFR_X1 B0_IN_REG_data_out_reg_9_ (.D(B0[9]),
	.RN(RST_N),
	.CK(CTS_1),
	.Q(b0_tmp[9]));
   DFFR_X1 B0_IN_REG_data_out_reg_8_ (.D(B0[8]),
	.RN(RST_N),
	.CK(CTS_1),
	.Q(b0_tmp[8]));
   DFFR_X1 B0_IN_REG_data_out_reg_7_ (.D(B0[7]),
	.RN(RST_N),
	.CK(CTS_1),
	.Q(b0_tmp[7]));
   DFFR_X1 B0_IN_REG_data_out_reg_6_ (.D(B0[6]),
	.RN(RST_N),
	.CK(CTS_1),
	.Q(b0_tmp[6]));
   DFFR_X1 B0_IN_REG_data_out_reg_5_ (.D(B0[5]),
	.RN(RST_N),
	.CK(CTS_1),
	.Q(b0_tmp[5]));
   DFFR_X1 B0_IN_REG_data_out_reg_4_ (.D(B0[4]),
	.RN(RST_N),
	.CK(CTS_1),
	.Q(b0_tmp[4]));
   DFFR_X1 B0_IN_REG_data_out_reg_3_ (.D(B0[3]),
	.RN(RST_N),
	.CK(CTS_1),
	.Q(b0_tmp[3]));
   DFFR_X1 B0_IN_REG_data_out_reg_2_ (.D(B0[2]),
	.RN(RST_N),
	.CK(CTS_1),
	.Q(b0_tmp[2]));
   DFFR_X1 B0_IN_REG_data_out_reg_1_ (.D(B0[1]),
	.RN(RST_N),
	.CK(CTS_1),
	.Q(b0_tmp[1]));
   DFFR_X1 B0_IN_REG_data_out_reg_0_ (.D(B0[0]),
	.RN(RST_N),
	.CK(CTS_1),
	.Q(b0_tmp[0]));
   DFFR_X1 A1_IN_REG_data_out_reg_9_ (.D(A1[9]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(a1_tmp[9]));
   DFFR_X1 A1_IN_REG_data_out_reg_8_ (.D(A1[8]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(a1_tmp[8]));
   DFFR_X1 A1_IN_REG_data_out_reg_7_ (.D(A1[7]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(a1_tmp[7]));
   DFFR_X1 A1_IN_REG_data_out_reg_6_ (.D(A1[6]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(a1_tmp[6]));
   DFFR_X1 A1_IN_REG_data_out_reg_5_ (.D(A1[5]),
	.RN(FE_OFN3_RST_N),
	.CK(CTS_1),
	.Q(a1_tmp[5]));
   OAI21_X1 U315 (.A(n371),
	.B1(n108),
	.B2(FE_OFN3_RST_N),
	.ZN(n187));
   NOR2_X1 U318 (.A1(n91),
	.A2(n84),
	.ZN(add_287_carry[4]));
endmodule

