#ifndef FLEXFLOAT_CONFIG_H_INCLUDED
#define FLEXFLOAT_CONFIG_H_INCLUDED

/* #undef FLEXFLOAT_ON_SINGLE */
/* #undef FLEXFLOAT_ON_QUAD */
#define FLEXFLOAT_ON_DOUBLE
/* #undef FLEXFLOAT_NO_ROUNDING */
/* #undef FLEXFLOAT_FLAGS */
/* #undef FLEXFLOAT_STATS */
/* #undef FLEXFLOAT_TRACKING */
#define FLEXFLOAT_FLOAT128

#endif
